// GENERATED by CMakeLists.txt -- do not edit. One sweep unit = one shape, all stage counts.
#define UNIT_NAME    q3
#define UNIT_FN      moe_unit_q3_tn128_wn64_tm128_wm64
#define UNIT_2PLANE  1
#define UNIT_LOELEM  uint2_t
#define UNIT_HIELEM  uint1_t
#define UNIT_LOB     2
#define UNIT_HIB     1
#define UNIT_TM      128
#define UNIT_TN      128
#define UNIT_WM      64
#define UNIT_WN      64
#include "moe_bench_unit.inc"
