// GENERATED by CMakeLists.txt -- do not edit. One sweep unit = one shape, all stage counts.
#define UNIT_NAME    i2
#define UNIT_FN      moe_unit_i2_tn32_wn32_tm32_wm16
#define UNIT_2PLANE  0
#define UNIT_LOELEM  uint2_t
#define UNIT_HIELEM  half_t
#define UNIT_LOB     2
#define UNIT_HIB     0
#define UNIT_TM      32
#define UNIT_TN      32
#define UNIT_WM      16
#define UNIT_WN      32
#include "moe_bench_unit.inc"
