// GENERATED by CMakeLists.txt -- do not edit. One sweep unit = one shape, all stage counts.
#define UNIT_NAME    q6
#define UNIT_FN      moe_unit_q6_tn16_wn32_tm256_wm16
#define UNIT_2PLANE  1
#define UNIT_LOELEM  int4_t
#define UNIT_HIELEM  uint2_t
#define UNIT_LOB     4
#define UNIT_HIB     2
#define UNIT_TM      256
#define UNIT_TN      16
#define UNIT_WM      16
#define UNIT_WN      32
#include "moe_bench_unit.inc"
