// GENERATED by CMakeLists.txt -- do not edit. One sweep unit = one shape, all stage counts.
#define UNIT_NAME    q5
#define UNIT_FN      moe_unit_q5_tn16_wn64_tm64_wm64
#define UNIT_2PLANE  1
#define UNIT_LOELEM  int4_t
#define UNIT_HIELEM  uint1_t
#define UNIT_LOB     4
#define UNIT_HIB     1
#define UNIT_TM      64
#define UNIT_TN      16
#define UNIT_WM      64
#define UNIT_WN      64
#include "moe_bench_unit.inc"
