// GENERATED by CMakeLists.txt -- do not edit. One sweep unit = one shape, all stage counts.
#define UNIT_NAME    i4
#define UNIT_FN      moe_unit_i4_tn16_wn16_tm16_wm16
#define UNIT_2PLANE  0
#define UNIT_LOELEM  int4_t
#define UNIT_HIELEM  half_t
#define UNIT_LOB     4
#define UNIT_HIB     0
#define UNIT_TM      16
#define UNIT_TN      16
#define UNIT_WM      16
#define UNIT_WN      16
#include "moe_bench_unit.inc"
