set(CMAKE_CURRENT_BINARY_DIR "/root/marlin_ppu/Kernels/general/w4a16_gemm/cutlass_w4a16/fold_derivation/.moe_units_check_bad")
file(REMOVE_RECURSE "${CMAKE_CURRENT_BINARY_DIR}/moe_units")
set(_MOE_FORMATS
  "q3|1|uint2_t|uint1_t|2|1|64"
  "q5|1|int4_t|uint1_t|4|1|64"
  "q6|1|int4_t|uint2_t|4|2|32;64"
  "i2|0|uint2_t|half_t|2|0|32,64"
  "i4|0|int4_t|half_t|4|0|32,64"
)
# 16 IS THE HARDWARE FLOOR, and it was missing. Every MMA atom in cute/atom/mma_traits_ppu0015.hpp has M = 16
# (Shape_MNK = Shape<_16,...>, all eight of them), so TileM must be a multiple of 16 and TileM=8 is not reachable with these
# instructions -- the FA path's ppu.mma.m8n16 is raw asm in a different kernel family, not a cute atom here. TileM=16 IS
# reachable and this project has run it (the Q3 B-concat sweep used 16x32 warps at TM=16, which fold_traits.hpp still notes),
# but the list started at 32 so the whole row was absent from every sweep.
#
# At decode it is the largest smem term: A = TM*TK*2 is 2048 of 3328 B/stage at (32,64,32), so TM=16 takes ifl from 78 to 113
# and TM=16 with TileN=32 to 157 -- roughly 2x the in-flight loads -- while the CTA count does NOT change, because at one row
# per expert mt = ceil(1/TM) = 1 whatever TileM is.
set(_MOE_TM_LIST 16 32 64 128 256)
# 32 is here for DECODE. At batch 1 the grid is 8 m-tiles x (N/TN), so TileN is the only knob that adds CTAs, and the decode
# measurement says the band is latency/occupancy-bound rather than bandwidth-bound. It self-filters where WarpN > TileN.
set(_MOE_TN_LIST 32 64 128)
# WarpM=16 comes with it (TileM=16 admits no other), and is offered at every TileM rather than only at 16: cvt/mma = 128/WM
# is 8 there, which the skill records as a ~13-point cliff on PREFILL -- but decode runs at 0.4% MFU where the converter is
# not the bottleneck, so that cost is a prediction to test, not a reason to exclude the axis.
set(_MOE_WM_LIST 16 32 64)

set(_MOE_UNIT_SRCS "")
set(_MOE_LAST_NM "")
set(_MOE_FMT_NAMES "")
set(_MOE_FMT_IDX -1)
set(_MOE_UNIT_DECLS "")
set(_MOE_UNIT_CALLS "")
set(_MOE_GEN_DIR "${CMAKE_CURRENT_BINARY_DIR}/moe_units")
file(MAKE_DIRECTORY "${_MOE_GEN_DIR}")
foreach(_row IN LISTS _MOE_FORMATS)
  string(REPLACE "|" ";" _f "${_row}")
  list(LENGTH _f _nf)
  if(NOT _nf EQUAL 7)
    message(FATAL_ERROR "_MOE_FORMATS row '${_row}' has ${_nf} fields, expected 7 "
                        "(name|2plane|lo_elem|hi_elem|lo_bits|hi_bits|WarpN,list). A ';' anywhere in a row splits it.")
  endif()
  list(GET _f 0 _nm)
  list(GET _f 1 _2p)
  list(GET _f 2 _lo)
  list(GET _f 3 _hi)
  list(GET _f 4 _lob)
  list(GET _f 5 _hib)
  list(GET _f 6 _wns)
  string(REPLACE "," ";" _wns "${_wns}")   # comma -> real CMake list, only now that the row is safely split
  foreach(_wn IN LISTS _wns)
    foreach(_tn IN LISTS _MOE_TN_LIST)
      foreach(_wm IN LISTS _MOE_WM_LIST)
        foreach(_tm IN LISTS _MOE_TM_LIST)
          set(_fn "moe_unit_${_nm}_tn${_tn}_wn${_wn}_tm${_tm}_wm${_wm}")
          set(_src "${_MOE_GEN_DIR}/${_fn}.cu")
          # CONFIGURE_DEPENDS is not needed: the content is a pure function of this loop, so a changed table means a
          # re-configure, and file(WRITE) leaves the timestamp alone when the bytes are identical... it does not, so
          # write through a compare to keep make from rebuilding all 128 units on every configure.
          file(WRITE "${_src}.in"
            "// GENERATED by CMakeLists.txt -- do not edit. One sweep unit = one shape, all stage counts.\n"
            "#define UNIT_NAME    ${_nm}\n"
            "#define UNIT_FN      ${_fn}\n"
            "#define UNIT_2PLANE  ${_2p}\n"
            "#define UNIT_LOELEM  ${_lo}\n"
            "#define UNIT_HIELEM  ${_hi}\n"
            "#define UNIT_LOB     ${_lob}\n"
            "#define UNIT_HIB     ${_hib}\n"
            "#define UNIT_TM      ${_tm}\n"
            "#define UNIT_TN      ${_tn}\n"
            "#define UNIT_WM      ${_wm}\n"
            "#define UNIT_WN      ${_wn}\n"
            "#include \"moe_bench_unit.inc\"\n")
          execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${_src}.in" "${_src}")
          list(APPEND _MOE_UNIT_SRCS "${_src}")
          set(_MOE_UNIT_DECLS "${_MOE_UNIT_DECLS}void ${_fn}(const Band&, Best&);\n")
          # A section header when the format changes, so 336 rows are still readable. Emitted by the generator rather
          # than by the units: only the generator knows the order they will be called in.
          if(NOT _nm STREQUAL _MOE_LAST_NM)
            set(_MOE_UNIT_CALLS "${_MOE_UNIT_CALLS}  std::printf(\"  --- ${_nm} ---\\n\");\n")
            set(_MOE_LAST_NM "${_nm}")
            # ONE Best PER NUMERIC PRECISION. The verdict used to be "two-plane best" and "single-plane best", which is a
            # grouping by IMPLEMENTATION, not by anything a caller chooses: nobody picks "a two-plane format", they pick
            # Q5 or Q6. And it hid the interesting result -- with i2 and i4 sharing one slot, i4's own best never printed.
            math(EXPR _MOE_FMT_IDX "${_MOE_FMT_IDX} + 1")
            list(APPEND _MOE_FMT_NAMES "${_nm}")
          endif()
          set(_MOE_UNIT_CALLS "${_MOE_UNIT_CALLS}  ${_fn}(bd, b[${_MOE_FMT_IDX}]);\n")
        endforeach()
      endforeach()
    endforeach()
  endforeach()
endforeach()
list(LENGTH _MOE_UNIT_SRCS _MOE_UNIT_N)
message(STATUS "MoE sweep: ${_MOE_UNIT_N} generated units in ${_MOE_GEN_DIR}")
# main() includes this instead of naming 128 functions by hand. PLAIN CODE, not a multi-line macro: that needs a trailing
# backslash on EVERY line and the first version emitted one, which would have been a build break generated by the build.
# MOE_UNIT_COUNT is compiled in so the binary prints how many units it was linked against -- a silently shrunk
# enumeration then shows up in the log instead of as a quietly smaller sweep.
list(LENGTH _MOE_FMT_NAMES _MOE_FMT_N)
string(REPLACE ";" "\", \"" _MOE_FMT_INIT "${_MOE_FMT_NAMES}")
file(WRITE "${_MOE_GEN_DIR}/moe_bench_units.inc.in"
     "// GENERATED by CMakeLists.txt -- do not edit.\n"
     "#define MOE_UNIT_COUNT ${_MOE_UNIT_N}\n"
     "#define MOE_FMT_COUNT ${_MOE_FMT_N}\n"
     "static const char* const moe_fmt_names[] = {\"${_MOE_FMT_INIT}\"};\n"
     "${_MOE_UNIT_DECLS}"
     "static inline void moe_run_all(const Band& bd, Best* b) {\n"
     "  (void)bd; (void)b;\n"
     "${_MOE_UNIT_CALLS}"
     "}\n")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different
                "${_MOE_GEN_DIR}/moe_bench_units.inc.in" "${_MOE_GEN_DIR}/moe_bench_units.inc")

# -I must go through DEV_COMPILE_FLAGS, NOT target_include_directories: the device compiles are add_custom_commands that
# never see target properties (the same reason PPU_DEFS has to be forwarded twice). The generated units find the .inc via
# the custom command's own -I<source dir of the file>, but test_lowbit_moe_bench.cu lives in the source tree and would
# not find moe_bench_units.inc in the binary tree without this.
# DERIVE every expectation from the same lists the slice defines -- writing 128 in here went stale the moment TileN gained
# a third value, and a gate whose expected value is hand-maintained fails for the wrong reason.
list(LENGTH _MOE_TM_LIST _ntm)
list(LENGTH _MOE_TN_LIST _ntn)
list(LENGTH _MOE_WM_LIST _nwm)
list(LENGTH _MOE_FORMATS  _nfmt)
set(_exp 0)
foreach(_row IN LISTS _MOE_FORMATS)
  string(REPLACE "|" ";" _f "${_row}")
  list(GET _f 6 _w)
  string(REPLACE "," ";" _w "${_w}")
  list(LENGTH _w _nwn)
  math(EXPR _exp "${_exp} + ${_nwn} * ${_ntn} * ${_nwm} * ${_ntm}")
endforeach()
file(GLOB _gen "${_MOE_GEN_DIR}/*.cu")
list(LENGTH _gen _ngen)
message(STATUS "generated .cu files on disk: ${_ngen} (derived expectation ${_exp}, generator said ${_MOE_UNIT_N})")
# two independent comparisons: vs the derived product (catches a loop that skipped rows) and vs the generator's own list
# length (catches a file that failed to write).
if(NOT _ngen EQUAL _exp)
  message(FATAL_ERROR "expected ${_exp} generated units from the axis lists, got ${_ngen} on disk")
endif()
if(NOT _ngen EQUAL _MOE_UNIT_N)
  message(FATAL_ERROR "generator listed ${_MOE_UNIT_N} sources but ${_ngen} are on disk")
endif()
# DERIVED, like the total. This said 8 (4 TileM x 2 WarpM) and went stale the moment TileM gained 16 and WarpM gained 16 --
# the same hand-maintained-expectation failure the total count already had, one check further down.
math(EXPR _per_slice "${_ntm} * ${_nwm}")
foreach(_pat q6_tn64_wn32 q6_tn64_wn64 i4_tn128_wn64 i2_tn64_wn32)
  file(GLOB _hit "${_MOE_GEN_DIR}/moe_unit_${_pat}_*.cu")
  list(LENGTH _hit _nh)
  if(NOT _nh EQUAL _per_slice)
    message(FATAL_ERROR "moe_unit_${_pat}_* : expected ${_per_slice} (TileM x WarpM), got ${_nh}")
  endif()
endforeach()
file(GLOB _stray "${_MOE_GEN_DIR}/moe_unit_64_*.cu")
list(LENGTH _stray _nstray)
if(NOT _nstray EQUAL 0)
  message(FATAL_ERROR "the semicolon bug is back: ${_nstray} units named after a stray WarpN field")
endif()
# the dispatcher must declare and call every unit, and name one Best slot per FORMAT
file(READ "${_MOE_GEN_DIR}/moe_bench_units.inc" _d)
string(REGEX MATCHALL "\nvoid moe_unit_" _dc "${_d}")
list(LENGTH _dc _ndc)
string(REGEX MATCHALL "\n  moe_unit_" _cc "${_d}")
list(LENGTH _cc _ncc)
if(NOT _ndc EQUAL _exp OR NOT _ncc EQUAL _exp)
  message(FATAL_ERROR "dispatcher has ${_ndc} declarations and ${_ncc} calls, expected ${_exp} of each")
endif()
foreach(_need "MOE_UNIT_COUNT ${_exp}" "MOE_FMT_COUNT ${_nfmt}" "moe_fmt_names")
  string(FIND "${_d}" "${_need}" _f)
  if(_f EQUAL -1)
    message(FATAL_ERROR "dispatcher is missing '${_need}' -- main will not compile against it")
  endif()
endforeach()
message(STATUS "OK: ${_exp} units, both WarpN for q6/i2/i4, no stray-format units, dispatcher ${_exp}/${_exp} with ${_nfmt} format slots")
