include_guard(GLOBAL)

# Read one positive decimal scalar from a generated tactic table. This is intentionally separate from the X-macro
# parser: ArtifactTileK is a property of the resident table, not a per-tactic row field, and copying it into every row
# would turn one invariant into hundreds of opportunities to disagree.
function(qz_parse_tactic_scalar OUT_VALUE)
  cmake_parse_arguments(PARSE "" "FILE;MACRO" "" ${ARGN})
  foreach(_arg FILE MACRO)
    if(NOT PARSE_${_arg})
      message(FATAL_ERROR "qz_parse_tactic_scalar: ${_arg} is required")
    endif()
  endforeach()
  if(NOT PARSE_MACRO MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
    message(FATAL_ERROR "qz_parse_tactic_scalar: invalid macro name '${PARSE_MACRO}'")
  endif()

  get_filename_component(_file "${PARSE_FILE}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "qz_parse_tactic_scalar: table does not exist: ${_file}")
  endif()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_file}")
  file(STRINGS "${_file}" _definitions
       REGEX "^[ \t]*#define[ \t]+${PARSE_MACRO}([ \t]|$)")
  list(LENGTH _definitions _definition_count)
  if(NOT _definition_count EQUAL 1)
    message(FATAL_ERROR
      "${_file}: found ${_definition_count} definitions of ${PARSE_MACRO}, expected exactly one")
  endif()
  list(GET _definitions 0 _definition)
  if(NOT _definition MATCHES "^[ \t]*#define[ \t]+${PARSE_MACRO}[ \t]+([1-9][0-9]*)[ \t]*$")
    message(FATAL_ERROR
      "${_file}: malformed ${PARSE_MACRO} definition '${_definition}'; expected one positive decimal integer")
  endif()
  set(${OUT_VALUE} "${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()

# Parse an emitted tactic X-macro without evaluating it. Rows are returned as
# comma-separated integer tuples so callers can generate operator-specific units.
function(qz_parse_tactic_xmacro OUT_ROWS)
  # THIS FUNCTION INDEXES PHYSICAL LINES, so it needs CMP0007 NEW -- under OLD, list() drops empty elements and every
  # blank line in the table shifts the indices, which shows up as "parsed 201 rows, declares 202" and NOT as anything
  # pointing at a policy. The real configure has it (the project requires 3.19) and never noticed; a `cmake -P` slice
  # of the generator does not, which is how dev/fold_derivation/gen_moe_units_check.sh found it. Set it HERE rather
  # than asking callers to: a helper whose answer depends on the ambient policy of whoever called it is one that can
  # be right in the build and wrong in the gate that checks the build.
  cmake_policy(SET CMP0007 NEW)
  cmake_parse_arguments(PARSE "" "FILE;LIST_MACRO;COUNT_MACRO" "" ${ARGN})
  foreach(_arg FILE LIST_MACRO COUNT_MACRO)
    if(NOT PARSE_${_arg})
      message(FATAL_ERROR "qz_parse_tactic_xmacro: ${_arg} is required")
    endif()
  endforeach()

  get_filename_component(_file "${PARSE_FILE}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "qz_parse_tactic_xmacro: table does not exist: ${_file}")
  endif()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_file}")
  # file(STRINGS) folds C preprocessor continuation lines into one value, which would make a multi-row macro look
  # like one declaration. Hide backslashes before turning physical newlines into a CMake list, then restore each
  # line as it is inspected.
  file(READ "${_file}" _text)
  string(REPLACE "\\" "@QZ_TACTIC_BACKSLASH@" _text "${_text}")
  string(REPLACE "\r" "" _text "${_text}")
  string(REPLACE "\n" ";" _lines "${_text}")

  set(_list_defs 0)
  set(_count_defs 0)
  set(_decl_index -1)
  set(_expected_decl "#define ${PARSE_LIST_MACRO}(X, B) \\")
  set(_count_re "^#define[ \t]+${PARSE_COUNT_MACRO}[ \t]+([0-9][0-9]*)[ \t]*$")
  set(_index 0)
  foreach(_line IN LISTS _lines)
    string(REPLACE "@QZ_TACTIC_BACKSLASH@" "\\" _line "${_line}")
    if(_line MATCHES "^#define[ \t]+${PARSE_LIST_MACRO}\\(")
      math(EXPR _list_defs "${_list_defs} + 1")
      if(NOT _line STREQUAL _expected_decl)
        message(FATAL_ERROR
          "${_file}: malformed ${PARSE_LIST_MACRO} declaration '${_line}'; expected exactly '#define ${PARSE_LIST_MACRO}(X, B) \\'")
      endif()
      set(_decl_index ${_index})
    endif()
    if(_line MATCHES "^#define[ \t]+${PARSE_COUNT_MACRO}([ \t]|$)")
      math(EXPR _count_defs "${_count_defs} + 1")
      if(NOT _line MATCHES "${_count_re}")
        message(FATAL_ERROR "${_file}: malformed ${PARSE_COUNT_MACRO} definition: '${_line}'")
      endif()
      set(_declared_count "${CMAKE_MATCH_1}")
    endif()
    math(EXPR _index "${_index} + 1")
  endforeach()
  if(NOT _list_defs EQUAL 1)
    message(FATAL_ERROR "${_file}: found ${_list_defs} definitions of ${PARSE_LIST_MACRO}, expected exactly one")
  endif()
  if(NOT _count_defs EQUAL 1)
    message(FATAL_ERROR "${_file}: found ${_count_defs} definitions of ${PARSE_COUNT_MACRO}, expected exactly one")
  endif()

  # A row has seven decimal integer fields and the literal body placeholder B.
  # The continuation slash is mandatory except on the final row.
  set(_row_re "^[ \t]*X\\(([0-9][0-9]*),([0-9][0-9]*),([0-9][0-9]*),([0-9][0-9]*),([0-9][0-9]*),([0-9][0-9]*),([0-9][0-9]*),B\\)[ \t]*$")
  set(_rows "")
  set(_terminated FALSE)
  math(EXPR _first "${_decl_index} + 1")
  list(LENGTH _lines _line_count)
  math(EXPR _last "${_line_count} - 1")
  foreach(_index RANGE ${_first} ${_last})
    list(GET _lines ${_index} _line)
    string(REPLACE "@QZ_TACTIC_BACKSLASH@" "\\" _line "${_line}")
    string(LENGTH "${_line}" _row_length)
    math(EXPR _last_char_index "${_row_length} - 1")
    string(SUBSTRING "${_line}" ${_last_char_index} 1 _last_char)
    if(_last_char STREQUAL "\\")
      set(_continues TRUE)
      string(SUBSTRING "${_line}" 0 ${_last_char_index} _row_text)
    else()
      set(_continues FALSE)
      set(_row_text "${_line}")
    endif()
    if(NOT _row_text MATCHES "${_row_re}")
      math(EXPR _line_no "${_index} + 1")
      message(FATAL_ERROR
        "${_file}:${_line_no}: malformed tactic row; expected X(TM,TN,TK,WM,WN,ST,BC,B) with seven decimal integers: '${_line}'")
    endif()

    set(_row "${CMAKE_MATCH_1},${CMAKE_MATCH_2},${CMAKE_MATCH_3},${CMAKE_MATCH_4},${CMAKE_MATCH_5},${CMAKE_MATCH_6},${CMAKE_MATCH_7}")
    list(FIND _rows "${_row}" _duplicate)
    if(NOT _duplicate EQUAL -1)
      math(EXPR _line_no "${_index} + 1")
      message(FATAL_ERROR "${_file}:${_line_no}: duplicate tactic row: X(${_row},B)")
    endif()
    list(APPEND _rows "${_row}")
    if(NOT _continues)
      set(_terminated TRUE)
      math(EXPR _after "${_index} + 1")
      break()
    endif()
  endforeach()
  if(NOT _terminated)
    message(FATAL_ERROR "${_file}: ${PARSE_LIST_MACRO} has no final row without a continuation slash")
  endif()

  if(_after LESS _line_count)
    foreach(_index RANGE ${_after} ${_last})
      list(GET _lines ${_index} _line)
      string(REPLACE "@QZ_TACTIC_BACKSLASH@" "\\" _line "${_line}")
      if(_line MATCHES "^[ \t]*X\\(")
        math(EXPR _line_no "${_index} + 1")
        message(FATAL_ERROR "${_file}:${_line_no}: X(...) row appears after ${PARSE_LIST_MACRO} ended: '${_line}'")
      endif()
    endforeach()
  endif()

  list(LENGTH _rows _parsed_count)
  if(NOT _parsed_count EQUAL _declared_count)
    message(FATAL_ERROR
      "${_file}: parsed ${_parsed_count} tactic rows, but ${PARSE_COUNT_MACRO} declares ${_declared_count}")
  endif()
  set(${OUT_ROWS} "${_rows}" PARENT_SCOPE)
endfunction()

# Split a tuple list into batches. Each output element contains one or more
# tuples joined by '|', which is outside the decimal/comma row grammar.
function(qz_batch_tactic_rows OUT_BATCHES ROWS_VAR BATCH_SIZE)
  if(NOT "${BATCH_SIZE}" MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "qz_batch_tactic_rows: batch size must be a positive integer, got '${BATCH_SIZE}'")
  endif()
  set(_batches "")
  set(_batch "")
  foreach(_row IN LISTS ${ROWS_VAR})
    if(_row MATCHES "\\|")
      message(FATAL_ERROR "qz_batch_tactic_rows: row contains reserved separator '|': '${_row}'")
    endif()
    list(APPEND _batch "${_row}")
    list(LENGTH _batch _batch_count)
    if(_batch_count EQUAL BATCH_SIZE)
      string(JOIN "|" _encoded ${_batch})
      list(APPEND _batches "${_encoded}")
      set(_batch "")
    endif()
  endforeach()
  if(_batch)
    string(JOIN "|" _encoded ${_batch})
    list(APPEND _batches "${_encoded}")
  endif()
  set(${OUT_BATCHES} "${_batches}" PARENT_SCOPE)
endfunction()
