#!/usr/bin/env python3
"""Bounded B-transport/reference comparison; immutable controls and no JIT."""
import argparse
import csv
import ctypes as C
from functools import lru_cache
import hashlib
import json
import math
from pathlib import Path
import statistics
import subprocess
import sys
import time
import traceback
import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from dev.gemv_cuda.build import digest
from dev.gemv_ppu.bload_source import RECIPES
from dev.gemv_ppu.build_bload import PAYLOAD, verify
from dev.gemv_ppu.campaign import parse_cells
from dev.gemv_ppu.h800_port import IMPLEMENTATIONS, REFERENCE_RECIPES, XPLANE_RECIPES, selection, verify as verify_controls
from dev.gemv_ppu.run import Bench, SDK, SHAPES, checked, load_library, device_identity
from tools.run_kpack_grouped_decode_probe import Replay
from tools.profile_kpack_gpu_compact import AcuRange, acu_launch_command

VARIANTS = ("xplane", "kpack-current", "raw-reference", "fragment-global", "fragment-aiu")
ROUNDS = 4
CONTROL_RECEIPT = ROOT / "docs/measurements/q4_h800_port_ppu_20260911/summary.json"


def read_control_recipes(path):
    """Reuse selected *recipes*, never historical timings, from the PPU retest."""
    report = json.loads(path.read_text())
    if report.get("status") != "PASS" or report.get("failures"):
        raise ValueError("control receipt is incomplete")
    expected = {(n, k, mode) for n, k in SHAPES for mode in ("warm", "rotating")}
    result = {}
    for case in report["cases"]:
        if len(case["shape"]) != 3 or case["shape"][0] != 1:
            raise ValueError("control receipt is not M1")
        _, n, k = case["shape"]
        key = (n, k, case["mode"])
        if key not in expected or key in result or set(case["winners"]) != {"xplane", "raw-reference", "kpack"}:
            raise ValueError("control receipt has duplicate/missing/unexpected cells")
        chosen = {arm: tuple(row["recipe"]) for arm, row in case["winners"].items()}
        if (chosen["xplane"] not in XPLANE_RECIPES or chosen["raw-reference"] not in REFERENCE_RECIPES
                or chosen["kpack"] != tuple(selection(n, k)[1])):
            raise ValueError("control recipe is not present in its compiled implementation")
        result[key] = chosen
    if set(result) != expected:
        raise ValueError("control receipt shape/cache denominator differs")
    return result


@lru_cache(maxsize=1)
def control_recipes():
    return read_control_recipes(CONTROL_RECEIPT)


def verify_packages(candidate, baseline, controls, *, sources=True):
    manifest = verify(candidate, baseline, sources=sources)
    verify_controls(controls, baseline, sources=sources)
    receipt = json.loads(CONTROL_RECEIPT.read_text())
    if (receipt["authority"]["candidate"] != digest(controls / "manifest.json")
            or receipt["authority"]["baseline"] != digest(baseline / "manifest.json")):
        raise ValueError("selected controls and prebuilt images differ")
    read_control_recipes(CONTROL_RECEIPT)
    return manifest


def recipes(variant, n, k, mode):
    fixed = control_recipes()[(n, k, mode)]
    if variant in ("xplane", "raw-reference"): return [fixed[variant]]
    if variant == "kpack-current": return [fixed["kpack"]]
    if variant in ("fragment-global", "fragment-aiu"): return list(RECIPES)
    raise ValueError("unknown variant")


def arithmetic(variant, n, k):
    if variant == "kpack-current" and IMPLEMENTATIONS[selection(n, k)[0]].startswith("affine"):
        return "FP32_GROUP_AFFINE"
    return "PER_WEIGHT_FP16"


def transport_expected():
    # Independent coordinate tags, not generated by the packer. The local
    # CuTe proof checks the arithmetic owner map against partition_fragment_B.
    tags = (np.arange(512 * 64, dtype=np.uint16) ^ np.uint16(0x936d)).reshape(512, 64)
    expected = np.empty((4, 32, 32, 4), dtype="<u4")
    for tile in range(4):
        for micro in range(32):
            for lane in range(32):
                for reg in range(4):
                    nn = tile * 16 + lane // 4 + (reg // 2) * 8
                    kg = micro * 16 + 2 * (lane % 4) + (reg % 2) * 8
                    expected[tile, micro, lane, reg] = int(tags[kg, nn]) | (int(tags[kg+1, nn]) << 16)
    return tags, expected


def exact_bits(a, b, label):
    if len(a) != len(b) or not a or len(a) % 4: raise ValueError(label + ": extent differs")
    av, bv = np.frombuffer(a, dtype="<u4"), np.frombuffer(b, dtype="<u4")
    bad = np.flatnonzero(av != bv)
    if bad.size:
        i = int(bad[0])
        raise ValueError(f"{label}: bad={bad.size}/{av.size} first={i} want=0x{av[i]:08x} got=0x{bv[i]:08x}")
    return hashlib.sha256(a).hexdigest()


class ExperimentBench(Bench):
    def __init__(self, args):
        super().__init__(args)
        self.variant = args.variant
        if self.variant == "raw-reference":
            library = args.controls / "libq4_ppu_port_reference.so"
        elif self.variant == "kpack-current":
            library = args.controls / f"libq4_ppu_port_{selection(self.n, self.k)[0]}.so"
        else:
            library = args.candidate / PAYLOAD
        self.extra = C.CDLL(str(library), mode=C.RTLD_LOCAL)
        marker = self.extra.q4_ppu_probe
        marker.argtypes = [C.POINTER(C.c_int)] * 3 + [C.c_char_p]; marker.restype = C.c_int
        l2, sm, warp, name = C.c_int(), C.c_int(), C.c_int(), C.create_string_buffer(256)
        checked(marker(C.byref(l2), C.byref(sm), C.byref(warp), name), "B-load native marker")
        if (sm.value, warp.value, name.value.decode()) != (self.device["sm"], self.device["warp"], self.device["name"]):
            raise ValueError("candidate device differs")
        if self.variant == "raw-reference":
            self.raw_launch = self.extra.q4_ref_fp32_run_v2
            self.raw_launch.argtypes = [C.c_int] * 5 + [C.c_void_p] * 4; self.raw_launch.restype = C.c_int
        elif self.variant == "kpack-current":
            self.current_launch = self.extra.q4_h800_port_run
            self.current_launch.argtypes = [C.c_int] * 2 + [C.c_void_p] * 5; self.current_launch.restype = C.c_int
        else:
            self.blaunch = self.extra.q4_bload_run
            self.blaunch.argtypes = [C.c_int] * 5 + [C.c_void_p] * 5; self.blaunch.restype = C.c_int
            self.transport = self.extra.q4_bload_transport
            self.transport.argtypes = [C.c_int] * 2 + [C.c_void_p] * 3; self.transport.restype = C.c_int
        self.raw_weight = None
        if self.variant == "raw-reference":
            self.raw_weight = np.ascontiguousarray(self.data["raw"]).view("u1").reshape(-1)
            if self.raw_weight.nbytes != self.weight_bytes: raise ValueError("raw reference byte count differs")
            raw_base = self.r.alloc(self.weight_bytes * self.copies)
            self.weight_pointers = []
            for i in range(self.copies):
                ptr = raw_base + i * self.weight_bytes
                checked(self.sdk.lib.hggcMemcpy(ptr, self.raw_weight.ctypes.data, self.weight_bytes, 1), "raw GGUF upload")
                self.weight_pointers.append((ptr, 0))
            self.sdk.synchronize(None)

    def transport_check(self, recipe):
        tags, expected = transport_expected()
        src = self.r.upload(tags)
        self.sdk.synchronize(None) # default-stream H2D precedes the nonblocking consumer
        base = self.r.alloc(expected.nbytes + 64); dst = base + 32
        self.r.fill(base, 0xa5, expected.nbytes + 64)
        self.sdk.synchronize(self.r.stream)
        checked(self.transport(recipe[0], recipe[1], src, dst, self.r.stream), "AIU b16 coordinate gate")
        self.sdk.synchronize(self.r.stream)
        raw = self.sdk.download(base, expected.nbytes + 64)
        if raw[:32] != b"\xa5" * 32 or raw[-32:] != b"\xa5" * 32: raise ValueError("transport output guard changed")
        fingerprint = exact_bits(expected.tobytes(), raw[32:-32], "AIU raw b16 coordinates")
        observed = np.frombuffer(raw[32:-32], dtype="<u4").reshape(expected.shape)
        # Incorrect N half and stale K stage must not explain a green result.
        if np.array_equal(observed, expected[..., [2, 3, 0, 1]]) or np.array_equal(observed, np.roll(expected, 4, axis=1)):
            raise ValueError("transport wrong-N/stale-stage negative escaped")
        return fingerprint

    def invoke(self, recipe, index=0, force_aiu=None):
        lp, up = self.weight_pointers[index % self.copies]
        if self.variant == "raw-reference":
            return self.raw_launch(*recipe, self.n, self.k, self.a, lp, self.output, self.r.stream)
        if self.variant == "kpack-current":
            return self.current_launch(self.n, self.k, self.a, lp, up, self.output, self.r.stream)
        aiu = int(self.variant == "fragment-aiu") if force_aiu is None else force_aiu
        return self.blaunch(aiu, recipe[0], recipe[1], self.n, self.k, self.a, lp, up, self.output, self.r.stream)

    def direct(self, recipe, force_aiu=None):
        self.r.fill(self.output_base, 0xff, self.output_bytes + 32)
        checked(self.invoke(recipe, force_aiu=force_aiu), "B-load/reference correctness launch")
        error = self.error()
        if not math.isfinite(error) or error >= .005: raise ValueError(f"independent GGUF dot failed: {error:.8g}")
        return self.sdk.download(self.output, self.output_bytes), error

    def measure(self, recipe):
        gate_hash, matched = None, None
        if self.variant.startswith("fragment-"):
            gate_hash = self.transport_check(recipe)
            control, _ = self.direct(recipe, force_aiu=0)
            matched = exact_bits(control, self.direct(recipe, force_aiu=1)[0], "AIU/direct same-topology FP32")
        original, error = self.direct(recipe)
        # Only code bytes change; raw-reference headers remain bit-identical.
        if self.raw_weight is not None:
            fault = self.raw_weight.copy().reshape(-1, 144)
            fault[:, 16:] = 0
            source, changed = self.raw_weight, fault
        else:
            source, changed = self.host_low, np.zeros_like(self.host_low)
        ptr = self.weight_pointers[0][0]
        checked(self.sdk.lib.hggcMemcpy(ptr, changed.ctypes.data, changed.nbytes, 1), "zero code upload")
        self.sdk.synchronize(None)
        self.r.fill(self.output_base, 0xff, self.output_bytes + 32)
        checked(self.invoke(recipe), "zero-code negative")
        if self.error() <= .005: raise ValueError("zero-code negative escaped")
        checked(self.sdk.lib.hggcMemcpy(ptr, source.ctypes.data, source.nbytes, 1), "restore codes")
        self.r.fill(self.a, 0, self.data["a"].nbytes)
        self.sdk.synchronize(None)
        checked(self.invoke(recipe), "zero-A negative")
        self.sdk.synchronize(self.r.stream)
        zero = np.frombuffer(self.sdk.download(self.output, self.output_bytes), dtype="<f4")
        if not np.any(np.frombuffer(original, dtype="<f4") != 0) or not np.all(zero == 0):
            raise ValueError("zero-A control failed")
        checked(self.sdk.lib.hggcMemcpy(self.a, self.data["a"].ctypes.data, self.data["a"].nbytes, 1), "restore A")
        self.sdk.synchronize(None)
        self.r.fill(self.workspace_base, 0xff, self.workspace_bytes + 256)
        for _ in range(5):
            for i in range(self.copies): checked(self.invoke(recipe, i), "cache setup")
        self.sdk.synchronize(self.r.stream)
        calls = max(2, (32 + self.copies - 1) // self.copies) * self.copies
        cursor = 0
        def launch():
            nonlocal cursor
            rc = self.invoke(recipe, cursor); cursor += 1
            return rc
        samples = []
        if self.args.profile:
            with AcuRange(self.sdk):
                checked(self.invoke(recipe), "profile selected call")
                self.sdk.synchronize(self.r.stream)
        else:
            graph = Replay(self.sdk, self.r.stream, launch, calls)
            try:
                self.r.samples(graph, 5) # first launch/upload is not a timing sample
                samples = [t / calls for t in self.r.samples(graph, self.args.samples)]
            finally: graph.close()
        error = max(error, self.error())
        exact_bits(original, self.sdk.download(self.output, self.output_bytes), "post-replay deterministic FP32")
        if error >= .005: raise ValueError("post-replay independent oracle failed")
        if self.sdk.download(self.workspace_base, self.workspace_bytes + 256) != b"\xff" * (self.workspace_bytes + 256):
            raise ValueError("S1 arm unexpectedly wrote workspace")
        return dict(status="PASS", arm=self.variant, variant=self.variant, shape=[1, self.n, self.k], mode=self.args.mode,
            recipe=recipe, error=error, zero_code_negative="PASS", zero_a_check="PASS", device=self.device,
            copies=self.copies, weight_bytes=self.weight_bytes, calls_per_graph=calls, samples_us=samples,
            median_us=statistics.median(samples) if samples else None, output_type="F32", reducer_check="NOT_APPLICABLE",
            transport_b16_sha256=gate_hash, matched_fp32_sha256=matched,
            storage="RAW_GGUF" if self.raw_weight is not None else "CANONICAL_KPACK4",
            weight_arithmetic=arithmetic(self.variant, self.n, self.k),
            launches_per_call=1, inter_cta_split=1,
            timing_scope="RESIDENT_COMPLETE_CALL_INCLUDING_REDUCER_NO_HOST_PACK_OR_JIT")


def parse_result(text, variant, recipe, shape, mode, samples):
    row = parse_cells(text, variant, [recipe], shape, mode, samples)[0]
    if (row.get("variant") != variant or row.get("output_type") != "F32"
            or tuple(recipe) not in recipes(variant, *shape[1:], mode)):
        raise ValueError("B-load/reference arm or precision differs")
    # Raw-reference's third field is intra-CTA K-warps, NOT inter-CTA split.
    if variant != "xplane":
        if row.get("zero_a_check") != "PASS" or row.get("storage") != ("RAW_GGUF" if variant == "raw-reference" else "CANONICAL_KPACK4"):
            raise ValueError("missing A check or wrong input format")
        if (row.get("weight_arithmetic") != arithmetic(variant, *shape[1:])
                or row.get("launches_per_call") != 1 or row.get("inter_cta_split") != 1):
            raise ValueError("arithmetic or single-kernel scope differs")
    if variant.startswith("fragment-"):
        for key in ("transport_b16_sha256", "matched_fp32_sha256"):
            if not isinstance(row.get(key), str) or len(row[key]) != 64 or any(c not in "0123456789abcdef" for c in row[key]):
                raise ValueError("missing raw-transport/matched-FP32 proof")
    return row


def child(args):
    verify_packages(args.candidate, args.bundle, args.controls, sources=False)
    args.arm = "xplane" if args.variant == "xplane" else "new"
    bench = None
    failed = False
    try:
        bench = Bench(args) if args.variant == "xplane" else ExperimentBench(args)
        for recipe in json.loads(args.recipes):
            if tuple(recipe) not in recipes(args.variant, bench.n, bench.k, args.mode):
                raise ValueError("recipe outside bounded experiment")
            try:
                row = bench.measure(recipe) | dict(variant=args.variant)
                print("Q4_PPU_CELL " + json.dumps(row), flush=True)
            except Exception as exc:
                failed = True
                traceback.print_exc()
                print("Q4_BLOAD_FAILURE " + json.dumps(dict(variant=args.variant, recipe=recipe, error=str(exc))), flush=True)
                break # CUDA execution failure can poison this process; other arms use fresh children.
    finally:
        if bench: bench.close()
    return 1 if failed else 0


def summarize(n, k, mode, records):
    all_medians, winners = {}, {}
    for variant, by_recipe in records.items():
        values = {key: statistics.median(r["median_us"] for r in rows) for key, rows in by_recipe.items() if len(rows) == ROUNDS}
        all_medians[variant] = values
        if values:
            selected = min(values, key=values.get)
            winners[variant] = dict(recipe=json.loads(selected), median_us=values[selected])
    full = all(len(all_medians[v]) == len(recipes(v, n, k, mode)) for v in VARIANTS)
    result = dict(shape=[1,n,k], mode=mode, status="PASS" if full else "INCOMPLETE", winners=winners,
                  scope="THREE_TRANSPORT_RECIPES_VS_PPU_SELECTED_CONTROLS_NOT_GLOBAL_OPTIMUM", matched_transport=[],
                  candidate_deltas={})
    for recipe in RECIPES:
        key = json.dumps(recipe)
        if key in all_medians["fragment-aiu"] and key in all_medians["fragment-global"]:
            a, b = all_medians["fragment-aiu"][key], all_medians["fragment-global"][key]
            result["matched_transport"].append(dict(recipe=recipe, aiu_us=a, direct_us=b, delta_pct=100*(a/b-1)))
    for arm in ("fragment-global", "fragment-aiu"):
        if arm not in winners: continue
        deltas = {v: 100*(winners[arm]["median_us"]/winners[v]["median_us"]-1)
                  for v in ("xplane", "kpack-current", "raw-reference") if v in winners}
        result["candidate_deltas"][arm] = dict(delta_pct=deltas,
            parity_verdict="INCOMPLETE" if not full else "WITHIN_5_PERCENT" if max(deltas.values()) <= 5 else "PARITY_OPEN")
    return result


def probe_device(args):
    """End the probe context before timing/profiling children start."""
    command = [sys.executable, "-u", str(Path(__file__).resolve()), "--probe", "--sdk", str(args.sdk),
               "--bundle", str(args.bundle), "--l2-bytes", str(args.l2_bytes)]
    proc = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    rows = [line.split(" ", 1)[1] for line in proc.stdout.splitlines() if line.startswith("Q4_BLOAD_PROBE ")]
    if proc.returncode or len(rows) != 1:
        raise ValueError(f"native device probe rc={proc.returncode}: {proc.stdout}")
    return json.loads(rows[0])


def run(args):
    m = verify_packages(args.candidate, args.bundle, args.controls)
    device = probe_device(args)
    cases = [(n, k, mode) for n, k in SHAPES if args.all_shapes or (n, k) == (5120,8192)
             for mode in ("warm", "rotating")]
    authority = dict(candidate=digest(args.candidate / "manifest.json"), baseline=digest(args.bundle / "manifest.json"),
        controls=digest(args.controls / "manifest.json"), control_selection=digest(CONTROL_RECEIPT),
        runner=digest(Path(__file__)), protocol=digest(ROOT / "dev/gemv_ppu/run.py"), parser=digest(ROOT / "dev/gemv_ppu/campaign.py"),
        cases=cases, samples=args.samples, rounds=ROUNDS, device=device, l2_override=args.l2_bytes,
        runtime={name:digest(args.sdk / "lib" / name) for name in m["runtime"]},
        fixtures={f"{n}x{k}":digest(args.fixtures / f"q12-n{n}-k{k}-e1-c1.npz") for n,k,_ in cases})
    authority = json.loads(json.dumps(authority))
    args.output.mkdir(parents=True, exist_ok=True)
    identity_path = args.output / "authority.json"
    if identity_path.exists() and json.loads(identity_path.read_text()) != authority:
        raise ValueError("resume identity changed; use a fresh result directory")
    identity_path.write_text(json.dumps(authority, indent=2) + "\n")
    changed = [name for name, sha in authority["runtime"].items() if sha != m["runtime"][name]]
    if changed: print("Q4_BLOAD_SDK_DIFFERENCE recorded=" + ",".join(changed) + " marker_and_numeric_required=1", flush=True)
    started = time.monotonic(); summaries, profiles, failures = [], [], []
    def cmd(n,k,mode,variant,wanted,profile=False):
        result = [sys.executable,"-u",str(Path(__file__).resolve()),"--child","--sdk",str(args.sdk),
            "--bundle",str(args.bundle),"--candidate",str(args.candidate),"--controls",str(args.controls),"--fixture",
            str(args.fixtures/f"q12-n{n}-k{k}-e1-c1.npz"),"--variant",variant,"--mode",mode,
            "--recipes",json.dumps(wanted),"--samples",str(args.samples),"--l2-bytes",str(args.l2_bytes)]
        return result + (["--profile"] if profile else [])
    def collect(n,k,mode,variant,turn):
        prefix = f"n{n}-k{k}-{mode}-{variant}-r{turn}"
        wanted = recipes(variant,n,k,mode); cached = {}
        receipt = args.output / (prefix + ".json")
        if receipt.exists():
            for key, entry in json.loads(receipt.read_text()).items():
                path = args.output / entry["log"]
                if path.parent != args.output or digest(path) != entry["log_sha256"]: raise ValueError("cached log changed")
                row = parse_result("Q4_PPU_CELL " + json.dumps(entry["row"]),variant,json.loads(key),[1,n,k],mode,args.samples)
                if row["device"] != device or "Q4_PPU_CELL " + json.dumps(entry["row"]) not in path.read_text():
                    raise ValueError("cached row not present in its device log")
                cached[key] = entry
        missing = [r for r in wanted if json.dumps(r) not in cached]
        if missing:
            log = args.output / (prefix + f".{time.time_ns()}.log")
            print(f"Q4_BLOAD_PROGRESS shape=1x{n}x{k} mode={mode} arm={variant} round={turn+1}/{ROUNDS} recipes={len(missing)} elapsed_s={time.monotonic()-started:.1f}",flush=True)
            with log.open("w") as stream:
                rc = subprocess.run(cmd(n,k,mode,variant,missing),stdout=stream,stderr=subprocess.STDOUT).returncode
            lines = [line for line in log.read_text().splitlines() if line.startswith("Q4_PPU_CELL ")]
            seen, errors = set(), []
            for line in lines:
                key = None
                try:
                    raw = json.loads(line.split(" ",1)[1]); key = json.dumps(raw["recipe"])
                    if key in seen or tuple(raw["recipe"]) not in missing:
                        raise ValueError("duplicate/unrequested child recipe")
                    seen.add(key)
                    row = parse_result(line,variant,raw["recipe"],[1,n,k],mode,args.samples)
                    if row["device"] != device: raise ValueError("child device differs")
                    cached[key] = dict(row=row,log=log.name,log_sha256=digest(log))
                except (ValueError, KeyError, TypeError) as exc:
                    if key is not None: cached.pop(key, None)
                    errors.append(str(exc))
            receipt.write_text(json.dumps(cached,indent=2)+"\n")
            if rc or errors or any(json.dumps(r) not in cached for r in wanted):
                failures.append(dict(shape=[1,n,k],mode=mode,variant=variant,round=turn,rc=rc,log=log.name,errors=errors))
                print(f"Q4_BLOAD_CHILD_FAIL arm={variant} rc={rc} log={log} successful_cells_retained=1",flush=True)
        return {key:entry["row"] for key,entry in cached.items()}
    for n,k,mode in cases:
        records = {v:{} for v in VARIANTS}
        for turn in range(ROUNDS):
            for v in (VARIANTS if turn%2==0 else VARIANTS[::-1]):
                for key,row in collect(n,k,mode,v,turn).items(): records[v].setdefault(key,[]).append(row)
        summary = summarize(n,k,mode,records)
        if any(f["shape"] == [1,n,k] and f["mode"] == mode for f in failures):
            summary["status"] = "INCOMPLETE"
            for result in summary["candidate_deltas"].values(): result["parity_verdict"] = "INCOMPLETE"
        summaries.append(summary)
        print("Q4_BLOAD_RESULT " + json.dumps(summary),flush=True)
        (args.output / "summary.json").write_text(json.dumps(dict(cases=summaries,failures=failures),indent=2)+"\n")
    if not args.skip_acu:
        anchor = next(s for s in summaries if s["shape"] == [1,5120,8192] and s["mode"] == "rotating")
        for v in VARIANTS:
            if v not in anchor["winners"]: continue
            chosen = anchor["winners"][v]["recipe"]
            if v == "fragment-global" and "fragment-aiu" in anchor["winners"]: chosen = anchor["winners"]["fragment-aiu"]["recipe"]
            prefix = args.output / (v + f".{time.time_ns()}.acu")
            log = prefix.with_suffix(".acu.log")
            command = acu_launch_command(args.acu or args.sdk/"asight/bin/acu",prefix,cmd(5120,8192,"warm",v,[chosen],True))
            print(f"Q4_BLOAD_ACU arm={v} recipe={chosen} cache=FORCED_COLD timing_authority=0",flush=True)
            try:
                with log.open("w") as stream: rc=subprocess.run(command,stdout=stream,stderr=subprocess.STDOUT).returncode
                if rc: raise ValueError(f"ACU process rc={rc}")
                parse_result(log.read_text(),v,chosen,[1,5120,8192],"warm",0)
                files=[p for p in args.output.glob(prefix.name+"*") if p.suffix in (".acurep",".report")]
                if not files: raise ValueError("ACU report missing")
                profiles.append(dict(variant=v,status="PASS",recipe=chosen,files=[p.name for p in files]))
            except Exception as exc:
                profiles.append(dict(variant=v,status="FAIL",error=str(exc),log=log.name))
    verify_packages(args.candidate,args.bundle,args.controls)
    if digest(CONTROL_RECEIPT) != authority["control_selection"]:
        raise ValueError("selected control receipt changed during run")
    if any(digest(args.sdk/"lib"/name)!=sha for name,sha in authority["runtime"].items()): raise ValueError("runtime changed during run")
    report=dict(status="PASS" if all(r["status"]=="PASS" for r in summaries) and not failures and all(p["status"]=="PASS" for p in profiles) else "INCOMPLETE",
                cases=summaries,failures=failures,profiles=profiles,seconds=time.monotonic()-started)
    (args.output/"summary.json").write_text(json.dumps(report,indent=2)+"\n")
    with (args.output/"summary.tsv").open("w") as f:
        writer=csv.writer(f,delimiter="\t"); writer.writerow(["N","K","mode","arm","recipe","median_us","case_status"])
        for row in summaries:
            for variant,win in row["winners"].items(): writer.writerow([*row["shape"][1:],row["mode"],variant,win["recipe"],win["median_us"],row["status"]])
    print(f"Q4_BLOAD_COMPLETE status={report['status']} results={args.output}",flush=True)
    return 0 if report["status"]=="PASS" else 1


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument("--sdk",type=Path,required=True)
    p.add_argument("--bundle",type=Path,default=ROOT/"prebuilt/ppu0010/q4-simt-ab-v1")
    p.add_argument("--candidate",type=Path,default=ROOT/"prebuilt/ppu0010/q4-bload-v1")
    p.add_argument("--controls",type=Path,default=ROOT/"prebuilt/ppu0010/q4-h800-port-v1")
    p.add_argument("--fixtures",type=Path);p.add_argument("--output",type=Path)
    p.add_argument("--fixture",type=Path);p.add_argument("--child",action="store_true")
    p.add_argument("--variant",choices=VARIANTS);p.add_argument("--recipes")
    p.add_argument("--mode",choices=("warm","rotating"));p.add_argument("--samples",type=int,default=15)
    p.add_argument("--all-shapes",action="store_true");p.add_argument("--profile",action="store_true")
    p.add_argument("--skip-acu",action="store_true");p.add_argument("--acu",type=Path)
    p.add_argument("--l2-bytes",type=int,default=0)
    p.add_argument("--probe",action="store_true")
    a=p.parse_args()
    a.sdk=a.sdk.resolve(strict=True);a.bundle=a.bundle.resolve(strict=True);a.candidate=a.candidate.resolve(strict=True)
    a.controls=a.controls.resolve(strict=True)
    if a.samples<3 or a.l2_bytes<0:p.error("invalid samples/L2 size")
    if a.probe:
        sdk=SDK(a.sdk);device=device_identity(sdk)
        _,geometry=load_library(a,"new");device.update(geometry)
        print("Q4_BLOAD_PROBE " + json.dumps(device),flush=True)
        return 0
    if a.child:return child(a)
    if a.fixtures is None or a.output is None:p.error("--fixtures and --output required")
    a.fixtures=a.fixtures.resolve(strict=True);a.output=a.output.resolve()
    return run(a)


if __name__=="__main__":
    try:raise SystemExit(main())
    except Exception:
        traceback.print_exc();raise SystemExit(1)
