// GENERATED by CMakeLists.txt -- do not edit. One sweep unit = one shape, all stage counts.
#define UNIT_NAME    q5
#define UNIT_FN      moe_unit_q5_tn64_wn64_tm32_wm16
#define UNIT_2PLANE  1
#define UNIT_LOELEM  int4_t
#define UNIT_HIELEM  uint1_t
#define UNIT_LOB     4
#define UNIT_HIB     1
#define UNIT_TM      32
#define UNIT_TN      64
#define UNIT_WM      16
#define UNIT_WN      64
#include "moe_bench_unit.inc"
