#!/usr/bin/env python3
"""Reject a stale lowbit dense generated table before the device compiler sees it."""

import argparse
import hashlib
import os
import re
import shutil
import subprocess
from itertools import zip_longest
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SPACE = ROOT / "quactlize" / "include" / "ppu_tactic_space.hpp"
EMITTER = ROOT / "benchmarks" / "emit_tactic_configs.cpp"
DEFAULT_TABLE = ROOT / "benchmarks" / "lowbit_dense_configs.inc"
# THE INVOCATION IS READ OFF THE TABLE'S OWN HEADER, not restated here. The header's first lines are
#   //   space=dense bits=4 artifact_tile_k=64   293 configs (...) over 6 stage(s)
#   //   tactic_tile_k: 64 128 256
#   //   stages: 2 3 4 6 8 12
# and the emitter writes them from the arguments it was actually given, so they ARE the invocation.
#
# THIS IS NOT A CONVENIENCE. With the arguments hardcoded, the gate could only ever validate one table: a table
# emitted for a different width, TileK or SPACE regenerates as the dense/int4/TK64 one and is reported stale, and
# build.sh runs this before every dense build, so a hardcoded invocation made any table but one impossible to
# validate -- and at the time that blocked the single experiment the project needed. A safety check that has to
# be switched off to run the diagnostic it protects gets switched off and stays off. (The experiment in question
# was a --space=quarantined build; that mode has since been deleted along with the exclusion it worked around,
# but the hardcoding would have blocked the NEXT one just as well, which is why this stayed.)
#
# The property is unchanged: the table must be byte-identical to what the current emitter produces FOR THE
# ARGUMENTS THE TABLE ITSELF DECLARES. A header claiming a space the emitter does not accept fails, and a header
# edited to match hand-edited rows fails on the next line, because the rows are compared too.
HEADER_RE = re.compile(r"^//\s+space=(\w+)\s+bits=(\d+)\s+artifact_tile_k=(\d+)", re.M)
STAGES_RE = re.compile(r"^//\s+stages:\s+([\d ]+?)\s+<", re.M)
# TacticTileK became a row field on 2026-08-05, so the header lists the CONSUMER TileKs separately from the
# artifact's. Both are needed to reproduce the table: the artifact one is a positional argument, the tactic list
# is --tactic-tk. A header carrying only the old `tile_k=` is from before the split and cannot be regenerated by
# this emitter, which is why the parse fails loudly instead of assuming they were the same number.
TACTIC_RE = re.compile(r"^//\s+tactic_tile_k:\s+([\d ]+?)\s+<", re.M)
# The regeneration line is the only place the compact-A capacities appear, because they are not a header
# summary field: today only 0 is emitted, so there is nothing for a reader to be told. The gate still needs them
# to reproduce the file, and reading them off the command the file prints keeps this from being a second copy.
# Pruning is opt-in as of 2026-08-06. Read it off the regeneration line for the same reason as the
# capacities: a table emitted with --prune=primary-guard is not reproducible without it, and the
# default silently reproducing a DIFFERENT file is the failure this gate exists to prevent.
PRUNE_RE = re.compile(r"--prune=([a-z-]+)", re.M)
# --format IS WHY THIS GATE WAS DENSE-ONLY. The five grouped tables carry full provenance and this parser simply
# never learned the one argument that selects which of them to emit, so pointing it at lowbit_grouped_i4 rebuilt a
# DIFFERENT table and failed -- and the easiest reading of that failure is "the gate does not do grouped", which is
# how five tables went ungated long enough to each be emitted with a single --tactic-tk while dense got three.
# Read off the regeneration line, same as --prune: it is the only place it appears.
FORMAT_RE = re.compile(r"--format=([A-Za-z0-9_]+)", re.M)
# --m-max IS PART OF THE TABLE'S IDENTITY, not a preference. A decode table is the same space, same format, same
# tactic list, pruned to the TileM a small band can fill -- so replaying its arguments WITHOUT --m-max rebuilds the
# unpruned table and reports drift that is entirely this parser's. codex hit exactly that: a 46-row Q3 decode table
# checked against a 404-row rebuild. Read off the regeneration line, same as --prune and --format; absent means
# unpruned, which is what every table before 2026-08-07 was.
M_MAX_RE = re.compile(r"--m-max=(\d+)", re.M)
# WHAT WAS REQUESTED IS NOT WHAT WAS EMITTED, since 2026-08-07. A --tactic-tk list may name members with no legal
# grid under TacticSpace, and the emitter now emits the legal subset instead of dying. Artifact tiling is one reason;
# a consumer-map or producer-map boundary can remove a whole member too, so the header deliberately does not lie
# about which one was decisive. The table therefore carries TWO lists and both are true of different things:
# `tactic_tile_k:` is what the table COVERS, and
# this line is what was ASKED FOR and refused. Reproducing the file needs the UNION -- regenerating from the
# surviving members alone produces a file with no SKIPPED line, i.e. a different file, which is exactly the
# "declared args do not reproduce the table" failure this gate exists to catch. It caught it on itself.
SKIPPED_RE = re.compile(r"^//\s+tactic_tk SKIPPED \(no legal grid under TacticSpace\):\s+([\d ]+)\s*$", re.M)
OUTPUT_RE = re.compile(
    r"^//\s+/workspace/quactlize-tactic-gen/emit_tactic\b.*>\s+(\S+\.inc)\s*$", re.M)


def declared_args(text: str):
    """-> (argv, description) for the emitter, or (None, why) if the header does not declare them."""
    h = HEADER_RE.search(text)
    if not h:
        return None, "header does not declare `space=... bits=... artifact_tile_k=...`"
    s = STAGES_RE.search(text)
    if not s:
        return None, "header does not declare a `stages:` line"
    space, bits, artifact_tk = h.group(1), h.group(2), h.group(3)
    stages = s.group(1).split()
    k = TACTIC_RE.search(text)
    if not k:
        return None, "header does not declare a `tactic_tile_k:` line"
    tactic = k.group(1).split()
    sk = SKIPPED_RE.search(text)
    requested = sorted(set(tactic) | set(sk.group(1).split() if sk else []), key=int)
    pr = PRUNE_RE.search(text)
    if not pr:
        return None, "header does not declare `--prune=` in its regeneration line"
    fmt = FORMAT_RE.search(text)
    fmt_arg = [f"--format={fmt.group(1)}"] if fmt else []
    mm = M_MAX_RE.search(text)
    mm_arg = [f"--m-max={mm.group(1)}"] if mm else []
    return ([bits, artifact_tk, f"--space={space}", "--tactic-tk=" + ",".join(requested),
             f"--prune={pr.group(1)}", *fmt_arg, *mm_arg, *stages],
            f"space={space} bits={bits} artifact_tile_k={artifact_tk} "
            f"tactic_tile_k={' '.join(tactic)}"
            + (f" m-max={mm.group(1)}" if mm else "")
            + (f" (requested {' '.join(requested)}, {len(requested) - len(tactic)} with no legal grid)"
               if len(requested) != len(tactic) else "")
            + f" stages={' '.join(stages)}")


def fnv1a64(data: bytes) -> str:
    value = 14695981039346656037
    for byte in data:
        value ^= byte
        value = (value * 1099511628211) & 0xFFFFFFFFFFFFFFFF
    return f"{value:016x}"


def macro(text: str, name: str):
    match = re.search(rf'^#define\s+{re.escape(name)}\s+(?:"([0-9a-f]+)"|(\d+))\s*$', text, re.M)
    return next((value for value in match.groups() if value is not None), None) if match else None


def fail(message: str, argv=None, table=None) -> int:
    # The hint quotes the arguments THIS table declares. Printing a fixed dense/int4/TK64 line next to a failure
    # about some other table is how an operator regenerates the wrong file and reports the gate as broken.
    #
    # AND THE FALLBACK MUST NOT LOOK RUNNABLE. It used to be the literal `4 64 --space=dense 2 3 4 6 8 12`, which
    # omits --tactic-tk, --compact-rows and --prune -- so it emits a DIFFERENT table from the one it is offered as
    # the repair for. Three call sites below had argv in scope and did not pass it, so on 2026-08-06 an emitter-hash
    # failure printed that line and it was one paste away from silently replacing 1164 rows with a narrower set. A
    # wrong command that looks right is worse than no command.
    args = " ".join(argv) if argv else "<the table declares no arguments -- see its provenance header>"
    out = table or "benchmarks/lowbit_dense_configs.inc"
    print(f"[dense-table] ERROR: {message}")
    print("[dense-table] regenerate from the repository root:")
    print("  mkdir -p /workspace/quactlize-tactic-gen && \\")
    print("  c++ -std=c++17 -Iquactlize/include benchmarks/emit_tactic_configs.cpp \\")
    print("    -o /workspace/quactlize-tactic-gen/emit_tactic && \\")
    print(f"  /workspace/quactlize-tactic-gen/emit_tactic {args} > {out}")
    return 1


def first_difference(expected: bytes, actual: bytes) -> str:
    for line, (want, got) in enumerate(
            zip_longest(expected.splitlines(), actual.splitlines(), fillvalue=b"<end>"), 1):
        if want != got:
            return (f"first difference at line {line}: expected {want[:100]!r}, "
                    f"found {got[:100]!r}")
    return "byte content differs"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--table", type=Path, default=DEFAULT_TABLE,
                        help="table to validate (default: the committed dense table)")
    parser.add_argument(
        "--q8-metadata-negative", action="store_true",
        help="also prove the legacy gs16/two-plane Q8 metadata charge removes exactly 48 rows")
    args = parser.parse_args()
    table = args.table.resolve()

    for path in (SPACE, EMITTER, table):
        if not path.is_file():
            return fail(f"missing {path}")

    actual = table.read_bytes()
    text = actual.decode()
    output = OUTPUT_RE.search(text)
    if output is None:
        return fail(f"{table}: regeneration command has no .inc output target", table=table)
    expected_output = Path("benchmarks") / table.name
    if Path(output.group(1)) != expected_output:
        return fail(f"{table}: regeneration command writes {output.group(1)}, not {table.name}", table=table)
    argv, declared = declared_args(text)
    if argv is None:
        return fail(f"{table}: {declared}; the gate regenerates using the arguments the table declares, "
                    f"so a table that declares none cannot be checked")
    # THE MACRO PREFIX IS THE TABLE'S, not a constant. Hardcoding LOWBIT_DENSE_CFG_ made every grouped table report
    # "predates the durability guard" -- a message about the FILE that was actually about this parser -- so the five
    # grouped tables read as ungateable rather than ungated. Derive it from the one macro every table defines.
    prefix_m = re.search(r"^#define (LOWBIT_[A-Z0-9_]+_CFG)_ROWS\s", text, re.M)
    if prefix_m is None:
        return fail(f"{table} defines no *_CFG_ROWS macro; it predates the durability guard", argv, table)
    prefix = prefix_m.group(1)
    stamped_rows = macro(text, f"{prefix}_ROWS")
    stamped_space = macro(text, f"{prefix}_SPACE_FNV1A64")
    stamped_emitter = macro(text, f"{prefix}_EMITTER_FNV1A64")
    missing = [name for name, value in (("row count", stamped_rows), ("space hash", stamped_space),
                                        ("emitter hash", stamped_emitter)) if value is None]
    if missing:
        return fail(f"{table} has no {', '.join(missing)} provenance; it predates the durability guard", argv, table)

    listed_rows = len(re.findall(rb'^\s*X\(', actual, re.M))
    if int(stamped_rows) != listed_rows:
        return fail(f"{table} stamps {stamped_rows} rows but its X-macro contains {listed_rows}", argv, table)

    current_space = fnv1a64(SPACE.read_bytes())
    current_emitter = fnv1a64(EMITTER.read_bytes())
    if stamped_space != current_space:
        return fail(f"{table} space hash is {stamped_space}, current ppu_tactic_space.hpp is {current_space}", argv, table)
    if stamped_emitter != current_emitter:
        return fail(f"{table} emitter hash is {stamped_emitter}, current emit_tactic_configs.cpp is {current_emitter}", argv, table)

    compiler = os.environ.get("CXX", "c++")
    temp_dir = Path("/workspace") / f"quactlize-dense-table-check-{os.getpid()}"
    if temp_dir.exists():
        return fail(f"refusing to reuse stale checker directory {temp_dir}", argv, table)
    temp_dir.mkdir(parents=True)
    try:
        binary = temp_dir / "emit_tactic"
        built = subprocess.run(
            [compiler, "-std=c++17", f"-I{ROOT / 'quactlize' / 'include'}", str(EMITTER), "-o", str(binary)],
            cwd=ROOT, capture_output=True, text=True)
        if built.returncode:
            detail = built.stderr.strip().splitlines()
            return fail(f"current emitter does not compile with {compiler}: {detail[-1] if detail else 'no diagnostic'}", argv, table)
        emitted = subprocess.run([str(binary), *argv], cwd=ROOT, capture_output=True)
        if emitted.returncode:
            detail = emitted.stderr.decode(errors="replace").strip().splitlines()
            return fail(f"current emitter rejected the table's own declared arguments "
                        f"({' '.join(argv)}): {detail[-1] if detail else 'no diagnostic'}", argv, table)
        expected = emitted.stdout
        if args.q8_metadata_negative:
            if "--format=i8" not in argv:
                return fail("--q8-metadata-negative requires the I8 table", argv, table)
            planted = subprocess.run(
                [str(binary), *argv, "--plant-q8-legacy-metadata"],
                cwd=ROOT, capture_output=True)
            if planted.returncode:
                detail = planted.stderr.decode(errors="replace").strip().splitlines()
                return fail(
                    "I8 legacy-metadata negative control did not run: "
                    f"{detail[-1] if detail else 'no diagnostic'}", argv, table)
            planted_rows = len(re.findall(rb'^\s*X\(', planted.stdout, re.M))
            live_rows = len(re.findall(rb'^\s*X\(', expected, re.M))
            witness = b"  X(16,128,128,16,16,12,0,B)"
            if live_rows != 2501 or planted_rows != 2453 or live_rows - planted_rows != 48:
                return fail(
                    "I8 metadata negative changed the wrong denominator: "
                    f"live={live_rows} planted={planted_rows} delta={live_rows - planted_rows}",
                    argv, table)
            if witness not in expected or witness in planted.stdout:
                return fail(
                    "I8 metadata negative did not remove the stage-12 A32 witness "
                    "16x128x128/w16x16", argv, table)
    finally:
        shutil.rmtree(temp_dir)

    if actual != expected:
        return fail(
            f"{table} does not exactly match a freshly built emitter; {first_difference(expected, actual)}; "
            f"expected md5={hashlib.md5(expected).hexdigest()}, found md5={hashlib.md5(actual).hexdigest()}",
            argv, table)

    print(f"[dense-table] verified {declared} rows={listed_rows} space_fnv1a64={current_space} "
          f"emitter_fnv1a64={current_emitter}; exact regeneration matches")
    if args.q8_metadata_negative:
        print("[dense-table] Q8 metadata negative: live=2501 legacy-gs16-two-plane=2453 "
              "delta=48; stage-12 A32 witness removed as required")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
