#!/usr/bin/env python3
"""Reject a stale lowbit dense generated table before the device compiler sees it."""

import argparse
import hashlib
import os
import re
import subprocess
import tempfile
from itertools import zip_longest
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SPACE = ROOT / "quactlize" / "include" / "ppu_tactic_space.hpp"
EMITTER = ROOT / "benchmarks" / "emit_tactic_configs.cpp"
DEFAULT_TABLE = ROOT / "benchmarks" / "lowbit_dense_configs.inc"
# THE INVOCATION IS READ OFF THE TABLE'S OWN HEADER, not restated here. The header's first lines are
#   //   space=dense bits=4 artifact_tile_k=64   293 configs (...) over 6 stage(s)
#   //   tactic_tile_k: 64 128 256
#   //   stages: 2 3 4 6 8 12
# and the emitter writes them from the arguments it was actually given, so they ARE the invocation.
#
# THIS IS NOT A CONVENIENCE. With the arguments hardcoded, the gate could only ever validate one table: a table
# emitted for a different width, TileK or SPACE regenerates as the dense/int4/TK64 one and is reported stale, and
# build.sh runs this before every dense build, so a hardcoded invocation made any table but one impossible to
# validate -- and at the time that blocked the single experiment the project needed. A safety check that has to
# be switched off to run the diagnostic it protects gets switched off and stays off. (The experiment in question
# was a --space=quarantined build; that mode has since been deleted along with the exclusion it worked around,
# but the hardcoding would have blocked the NEXT one just as well, which is why this stayed.)
#
# The property is unchanged: the table must be byte-identical to what the current emitter produces FOR THE
# ARGUMENTS THE TABLE ITSELF DECLARES. A header claiming a space the emitter does not accept fails, and a header
# edited to match hand-edited rows fails on the next line, because the rows are compared too.
HEADER_RE = re.compile(r"^//\s+space=(\w+)\s+bits=(\d+)\s+artifact_tile_k=(\d+)", re.M)
STAGES_RE = re.compile(r"^//\s+stages:\s+([\d ]+?)\s+<", re.M)
# TacticTileK became a row field on 2026-08-05, so the header lists the CONSUMER TileKs separately from the
# artifact's. Both are needed to reproduce the table: the artifact one is a positional argument, the tactic list
# is --tactic-tk. A header carrying only the old `tile_k=` is from before the split and cannot be regenerated by
# this emitter, which is why the parse fails loudly instead of assuming they were the same number.
TACTIC_RE = re.compile(r"^//\s+tactic_tile_k:\s+([\d ]+?)\s+<", re.M)
# The regeneration line is the only place the compact-A capacities appear, because they are not a header
# summary field: today only 0 is emitted, so there is nothing for a reader to be told. The gate still needs them
# to reproduce the file, and reading them off the command the file prints keeps this from being a second copy.
COMPACT_RE = re.compile(r"--compact-rows=([\d,]+)", re.M)
# Pruning is opt-in as of 2026-08-06. Read it off the regeneration line for the same reason as the
# capacities: a table emitted with --prune=primary-guard is not reproducible without it, and the
# default silently reproducing a DIFFERENT file is the failure this gate exists to prevent.
PRUNE_RE = re.compile(r"--prune=([a-z-]+)", re.M)


def declared_args(text: str):
    """-> (argv, description) for the emitter, or (None, why) if the header does not declare them."""
    h = HEADER_RE.search(text)
    if not h:
        return None, "header does not declare `space=... bits=... artifact_tile_k=...`"
    s = STAGES_RE.search(text)
    if not s:
        return None, "header does not declare a `stages:` line"
    space, bits, artifact_tk = h.group(1), h.group(2), h.group(3)
    stages = s.group(1).split()
    k = TACTIC_RE.search(text)
    if not k:
        return None, "header does not declare a `tactic_tile_k:` line"
    tactic = k.group(1).split()
    c = COMPACT_RE.search(text)
    if not c:
        return None, "header does not declare `--compact-rows=` in its regeneration line"
    pr = PRUNE_RE.search(text)
    if not pr:
        return None, "header does not declare `--prune=` in its regeneration line"
    return ([bits, artifact_tk, f"--space={space}", "--tactic-tk=" + ",".join(tactic),
             f"--compact-rows={c.group(1)}", f"--prune={pr.group(1)}", *stages],
            f"space={space} bits={bits} artifact_tile_k={artifact_tk} "
            f"tactic_tile_k={' '.join(tactic)} compact_rows={c.group(1)} stages={' '.join(stages)}")


def fnv1a64(data: bytes) -> str:
    value = 14695981039346656037
    for byte in data:
        value ^= byte
        value = (value * 1099511628211) & 0xFFFFFFFFFFFFFFFF
    return f"{value:016x}"


def macro(text: str, name: str):
    match = re.search(rf'^#define\s+{re.escape(name)}\s+(?:"([0-9a-f]+)"|(\d+))\s*$', text, re.M)
    return next((value for value in match.groups() if value is not None), None) if match else None


def fail(message: str, argv=None, table=None) -> int:
    # The hint quotes the arguments THIS table declares. Printing a fixed dense/int4/TK64 line next to a failure
    # about some other table is how an operator regenerates the wrong file and reports the gate as broken.
    #
    # AND THE FALLBACK MUST NOT LOOK RUNNABLE. It used to be the literal `4 64 --space=dense 2 3 4 6 8 12`, which
    # omits --tactic-tk, --compact-rows and --prune -- so it emits a DIFFERENT table from the one it is offered as
    # the repair for. Three call sites below had argv in scope and did not pass it, so on 2026-08-06 an emitter-hash
    # failure printed that line and it was one paste away from silently replacing 1164 rows with a narrower set. A
    # wrong command that looks right is worse than no command.
    args = " ".join(argv) if argv else "<the table declares no arguments -- see its provenance header>"
    out = table or "benchmarks/lowbit_dense_configs.inc"
    print(f"[dense-table] ERROR: {message}")
    print("[dense-table] regenerate from the repository root:")
    print("  c++ -std=c++17 -Iquactlize/include benchmarks/emit_tactic_configs.cpp -o /tmp/emit_tactic && \\")
    print(f"  /tmp/emit_tactic {args} > {out}")
    return 1


def first_difference(expected: bytes, actual: bytes) -> str:
    for line, (want, got) in enumerate(
            zip_longest(expected.splitlines(), actual.splitlines(), fillvalue=b"<end>"), 1):
        if want != got:
            return (f"first difference at line {line}: expected {want[:100]!r}, "
                    f"found {got[:100]!r}")
    return "byte content differs"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--table", type=Path, default=DEFAULT_TABLE,
                        help="table to validate (default: the committed dense table)")
    args = parser.parse_args()
    table = args.table.resolve()

    for path in (SPACE, EMITTER, table):
        if not path.is_file():
            return fail(f"missing {path}")

    actual = table.read_bytes()
    text = actual.decode()
    argv, declared = declared_args(text)
    if argv is None:
        return fail(f"{table}: {declared}; the gate regenerates using the arguments the table declares, "
                    f"so a table that declares none cannot be checked")
    stamped_rows = macro(text, "LOWBIT_DENSE_CFG_ROWS")
    stamped_space = macro(text, "LOWBIT_DENSE_CFG_SPACE_FNV1A64")
    stamped_emitter = macro(text, "LOWBIT_DENSE_CFG_EMITTER_FNV1A64")
    missing = [name for name, value in (("row count", stamped_rows), ("space hash", stamped_space),
                                        ("emitter hash", stamped_emitter)) if value is None]
    if missing:
        return fail(f"{table} has no {', '.join(missing)} provenance; it predates the durability guard", argv, table)

    listed_rows = len(re.findall(rb'^\s*X\(', actual, re.M))
    if int(stamped_rows) != listed_rows:
        return fail(f"{table} stamps {stamped_rows} rows but its X-macro contains {listed_rows}", argv, table)

    current_space = fnv1a64(SPACE.read_bytes())
    current_emitter = fnv1a64(EMITTER.read_bytes())
    if stamped_space != current_space:
        return fail(f"{table} space hash is {stamped_space}, current ppu_tactic_space.hpp is {current_space}", argv, table)
    if stamped_emitter != current_emitter:
        return fail(f"{table} emitter hash is {stamped_emitter}, current emit_tactic_configs.cpp is {current_emitter}", argv, table)

    compiler = os.environ.get("CXX", "c++")
    with tempfile.TemporaryDirectory(prefix="quactlize-dense-table-") as temp_dir:
        binary = Path(temp_dir) / "emit_tactic"
        built = subprocess.run(
            [compiler, "-std=c++17", f"-I{ROOT / 'quactlize' / 'include'}", str(EMITTER), "-o", str(binary)],
            cwd=ROOT, capture_output=True, text=True)
        if built.returncode:
            detail = built.stderr.strip().splitlines()
            return fail(f"current emitter does not compile with {compiler}: {detail[-1] if detail else 'no diagnostic'}", argv, table)
        emitted = subprocess.run([str(binary), *argv], cwd=ROOT, capture_output=True)
        if emitted.returncode:
            detail = emitted.stderr.decode(errors="replace").strip().splitlines()
            return fail(f"current emitter rejected the table's own declared arguments "
                        f"({' '.join(argv)}): {detail[-1] if detail else 'no diagnostic'}", argv, table)
        expected = emitted.stdout

    if actual != expected:
        return fail(
            f"{table} does not exactly match a freshly built emitter; {first_difference(expected, actual)}; "
            f"expected md5={hashlib.md5(expected).hexdigest()}, found md5={hashlib.md5(actual).hexdigest()}",
            argv, table)

    print(f"[dense-table] verified {declared} rows={listed_rows} space_fnv1a64={current_space} "
          f"emitter_fnv1a64={current_emitter}; exact regeneration matches")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
