#!/usr/bin/env python3
"""Emit the exact distinct accumulator-layout census consumed by L124."""

import collections
import glob
import pathlib
import re
import sys

repo = pathlib.Path(sys.argv[1]).resolve()
out = pathlib.Path(sys.argv[2]).resolve()
cases = set()
rows = 0

bench_files = glob.glob(str(repo / "benchmarks" / "lowbit_*configs.inc"))
ship_files = glob.glob(str(repo / "quactlize/include" / "ppu_*configs.inc"))
for name in bench_files:
    before = rows
    for line in pathlib.Path(name).read_text().splitlines():
        m = re.match(r"\s*X\((\d+),(\d+),(\d+),(\d+),(\d+),", line)
        if not m:
            continue
        tm, tn, _tk, wm, wn = map(int, m.groups())
        atom = 8 if tm == 8 and wm == 8 else 16
        cases.add((tm, tn, wm, wn, atom))
        rows += 1
    if rows == before:
        raise SystemExit(f"L124: parsed zero tactic rows from {name}")

for name in ship_files:
    before = rows
    for line in pathlib.Path(name).read_text().splitlines():
        m = re.match(
            r'\s*X\([^,]+,\s*"[^"]+",\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),',
            line,
        )
        if not m:
            continue
        tm, tn, wm, wn = map(int, m.groups())
        atom = 8 if tm == 8 and wm == 8 else 16
        cases.add((tm, tn, wm, wn, atom))
        rows += 1
    if rows == before:
        raise SystemExit(f"L124: parsed zero shipping rows from {name}")

if not bench_files or not ship_files or not cases or rows < len(cases):
    raise SystemExit("L124: tactic census is empty or internally inconsistent")
for tm, tn, wm, wn, atom in cases:
    if tm % wm or tn % wn or atom not in (8, 16):
        raise SystemExit(f"L124: illegal generated layout {(tm, tn, wm, wn, atom)}")
    if (atom == 8) != (tm == 8 and wm == 8):
        raise SystemExit(f"L124: atom selector mismatch {(tm, tn, wm, wn, atom)}")

# This is the actual TiledMMA cohort domain in the tables above, not a second
# Marlin admission list.  L124 consumes every layout before the Marlin-only
# CMake filter, so keeping all six cohorts visible here proves that widening
# that filter cannot silently select a layout the residue oracle never saw.
cohort_cases = collections.Counter(
    (tm // wm) * (tn // wn) for tm, tn, wm, wn, _atom in cases
)
expected_cohorts = {1, 2, 4, 8, 16, 32}
if set(cohort_cases) != expected_cohorts or any(cohort_cases[w] <= 0 for w in expected_cohorts):
    raise SystemExit(
        "L124: expected nonempty CTA-warp cohorts 1/2/4/8/16/32, got "
        + repr(dict(sorted(cohort_cases.items())))
    )

lines = [
    "// Generated by gen_l124_cases.py; do not edit.",
    f"#define L124_SOURCE_ROW_COUNT {rows}",
    f"#define L124_CASE_COUNT {len(cases)}",
    f"#define L124_COHORT_COUNT {len(cohort_cases)}",
    "#define L124_FOR_EACH_COHORT(X) \\",
]
ordered_cohorts = sorted(cohort_cases.items())
for i, (warps, count) in enumerate(ordered_cohorts):
    suffix = " \\" if i + 1 != len(ordered_cohorts) else ""
    lines.append(f"  X({warps},{warps * 32},{count}){suffix}")
lines += [
    "#define L124_FOR_EACH_CASE(X) \\",
]
ordered = sorted(cases)
for i, case in enumerate(ordered):
    suffix = " \\" if i + 1 != len(ordered) else ""
    lines.append("  X({},{},{},{},{}){}".format(*case, suffix))
out.write_text("\n".join(lines) + "\n")
cohort_text = ",".join(f"w{w}={n}" for w, n in ordered_cohorts)
print(
    f"L124 census: {rows} tactic rows -> {len(cases)} distinct accumulator layouts "
    f"({cohort_text})"
)
