#!/usr/bin/env python3
"""Emit the exact distinct accumulator-layout census consumed by L124."""

import glob
import pathlib
import re
import sys

repo = pathlib.Path(sys.argv[1]).resolve()
out = pathlib.Path(sys.argv[2]).resolve()
cases = set()
rows = 0

bench_files = glob.glob(str(repo / "benchmarks" / "lowbit_*configs.inc"))
ship_files = glob.glob(str(repo / "quactlize/include" / "ppu_*configs.inc"))
for name in bench_files:
    before = rows
    for line in pathlib.Path(name).read_text().splitlines():
        m = re.match(r"\s*X\((\d+),(\d+),(\d+),(\d+),(\d+),", line)
        if not m:
            continue
        tm, tn, _tk, wm, wn = map(int, m.groups())
        atom = 8 if tm == 8 and wm == 8 else 16
        cases.add((tm, tn, wm, wn, atom))
        rows += 1
    if rows == before:
        raise SystemExit(f"L124: parsed zero tactic rows from {name}")

for name in ship_files:
    before = rows
    for line in pathlib.Path(name).read_text().splitlines():
        m = re.match(
            r'\s*X\([^,]+,\s*"[^"]+",\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),',
            line,
        )
        if not m:
            continue
        tm, tn, wm, wn = map(int, m.groups())
        atom = 8 if tm == 8 and wm == 8 else 16
        cases.add((tm, tn, wm, wn, atom))
        rows += 1
    if rows == before:
        raise SystemExit(f"L124: parsed zero shipping rows from {name}")

if not bench_files or not ship_files or not cases or rows < len(cases):
    raise SystemExit("L124: tactic census is empty or internally inconsistent")
for tm, tn, wm, wn, atom in cases:
    if tm % wm or tn % wn or atom not in (8, 16):
        raise SystemExit(f"L124: illegal generated layout {(tm, tn, wm, wn, atom)}")
    if (atom == 8) != (tm == 8 and wm == 8):
        raise SystemExit(f"L124: atom selector mismatch {(tm, tn, wm, wn, atom)}")

lines = [
    "// Generated by gen_l124_cases.py; do not edit.",
    f"#define L124_SOURCE_ROW_COUNT {rows}",
    f"#define L124_CASE_COUNT {len(cases)}",
    "#define L124_FOR_EACH_CASE(X) \\",
]
ordered = sorted(cases)
for i, case in enumerate(ordered):
    suffix = " \\" if i + 1 != len(ordered) else ""
    lines.append("  X({},{},{},{},{}){}".format(*case, suffix))
out.write_text("\n".join(lines) + "\n")
print(f"L124 census: {rows} tactic rows -> {len(cases)} distinct accumulator layouts")
