// L20 (step 1) -- replace the offline with one DERIVED from the layouts, and prove it bit-identical first.
//
// The five relayout steps plus the fold repack are ~500 lines of hand-written index arithmetic. That is where the
// K>256 bug lived, and it is regenerated by hand for every new format. L18 pinned down why any of it is needed:
//
//     the ONLY reason an offline relayout exists is that MixGemmEmit != identity.
//
// So the placement is derivable:  for each physical (row, word, bit) the chain says which logical (n,k) belongs
// there -- LogicalTV for the swzl, MixGemmEmit for the converter, pi = frag.layout()^-1, partition_B for the mma --
// and the offline is just that walk.
//
// HOW THIS IS MADE SAFE. Not by replacing anything: by producing the buffer independently and comparing it
// BYTE FOR BYTE against preprocess_weights_for_mixed_gemm (+ nfold_regroup_gmem where the config folds). If the two
// agree bit-identically on every configuration the tree uses, then swapping them is safe by construction rather
// than by argument. The five steps stay in place until the box regression is green.
//
// The one non-positional piece is int4's +8 from add_bias_and_interleave_int4s. A layout says where a code goes, not
// what it becomes, so the value transform is applied explicitly here.
//
//   nvcc -std=c++17 -Istub_inc -I../../../../third_party/actlize/include -I.. l20_derived_offline.cu -o l20 && ./l20
#include "cute/tensor.hpp"
#include "cute/atom/mma_atom.hpp"
#include "cutlass/numeric_types.h"
#include "cutlass/fast_numeric_conversion_for_mix_gemm.h"
#include "unfused_weight_dequantize.hpp"
#include "legacy_pipeline.hpp"
#include <cstdio>
#include <vector>
#include <chrono>
using namespace cute;

struct F16Atom {};
namespace cute {
template <> struct MMA_Traits<F16Atom> {
  using ValTypeD=float; using ValTypeA=cutlass::half_t; using ValTypeB=cutlass::half_t; using ValTypeC=float;
  using Shape_MNK=Shape<_16,_16,_16>; using ThrID=Layout<_32>;
  using ALayout=Layout<Shape<Shape<_4,_8>,Shape<_2,_2,_2>>,Stride<Stride<_32,_1>,Stride<_16,_128,_8>>>;
  using BLayout=Layout<Shape<Shape<_4,_8>,Shape<_2,_2,_2>>,Stride<Stride<_32,_1>,Stride<_16,_128,_8>>>;
  using CLayout=Layout<Shape<Shape<_4,_8>,Shape<_4,_2>>,Stride<Stride<_16,_1>,Stride<_64,_8>>>;
};
}

// ---------------------------------------------------------------- the derived placement
// tile_map[(row*8 + wd)*CPW + j] = n_local*TK + k_local, over row in [0,Ng)
template <int Bits, int TM, int TN, int TK, int WM, int WN>
static std::vector<int> tile_map() {
  constexpr int WOM = TM/WM, WON = TN/WN, CPW = 32/Bits;
  constexpr int contig = TK*Bits/8, F = contig >= 32 ? 1 : 32/contig, Ng = TN/F;
  constexpr int RPI = WON*16, VEC = 4*32/Bits;
  using Mma = TiledMMA<MMA_Atom<F16Atom>, Layout<Shape<Int<WOM>,Int<WON>,_1>>,
                       Tile<Int<WOM*16>, Int<WON*16>, Int<TK>>>;
  auto sB = make_tensor(make_smem_ptr((cutlass::half_t*)nullptr),
                        make_layout(Shape<Int<TN>,Int<TK>>{}, Stride<Int<TK>,_1>{}));
  auto frag = Mma{}.get_thread_slice(0).partition_fragment_B(sB);
  const int NS = int(size(frag));
  // pi = frag.layout()^-1, and cute HAS this: right_inverse(Layout). It used to be a hand-rolled loop here (and in
  // seven sibling files); l30_should_have_been_cute.cu verifies the two agree on three shapes including int4's
  // production one. Worth replacing beyond tidiness: l20 is the file scheduled to become the production offline.
  auto pi = right_inverse(frag.layout());

  std::vector<int> m((size_t)Ng*8*CPW, -1);
  for (int t = 0; t < 32*WOM*WON; ++t) {
    const int lane = t%32, w = t/32, warp_n = w/WOM;
    auto part = Mma{}.get_thread_slice(t).partition_B(make_identity_tensor(make_shape(Int<TN>{},Int<TK>{})));
    for (int inst = 0; inst < Ng/RPI; ++inst)
      for (int v = 0; v < 4; ++v) {
        const int row = inst*RPI + 16*warp_n + (v/2)*8 + lane/4;
        const int wd  = (v%2)*4 + lane%4;
        for (int j = 0; j < CPW; ++j) {
          const int e = cutlass::MixGemmEmit<Bits>::index(j, v);
          const int flat = inst*VEC + e;
          if (flat < 0 || flat >= NS) continue;
          auto c = part(pi(flat));
          m[((size_t)row*8 + wd)*CPW + j] = int(get<0>(c))*TK + int(get<1>(c));
        }
      }
  }
  return m;
}

// write the buffer the kernel expects, straight from the tile map
//
// THE DESTINATION IS A cute LAYOUT, not three branches of index arithmetic. All three gmem forms are affine maps over
// the SAME physical-slot domain (j, wd, row, ki, tn) -- they differ only in the stride tuple, and the two that split
// ki into an inner AIU run and an outer 256-block are exactly what a HIERARCHICAL cute mode is for:
//
//   folded  (plane-major, l13)   : ki -> (RUNS, .) : (8*CPW,   nrow*W_ROW_OFF*CPW)
//   interleave-256 (F=1, l16)    : ki -> (RPS,  .) : (AiuElem, N*kCon)
//   NON-interleaved (RowsPerTile=-1, plain ColumnMajor [N][K]) : ki flat, stride TK
//
// So supporting RowsPerTile=-1 is a THIRD STRIDE TUPLE, not a third derivation: the source side
// (LogicalTV o MixGemmEmit o pi o partition_B, i.e. tile_map) answers "which logical (n,k) owns this physical slot"
// and is completely independent of how the buffer is interleaved. Dynamic (int) extents and strides are fine here --
// this is host code, so a cute Layout is just integer arithmetic with the shape written down instead of inlined.
template <int Bits, int TM, int TN, int TK, int WM, int WN, int RowsPerTile = 256>
static void place_derived(std::vector<int8_t>& out, const std::vector<int>& codes, int N, int K) {
  constexpr int CPW = 32/Bits, MASK = (1 << Bits) - 1;
  constexpr int contig = TK*Bits/8, F = contig >= 32 ? 1 : 32/contig, Ng = TN/F;
  const int kCon = 256, W_ROW_OFF = 256/CPW, RUNS = W_ROW_OFF/8;
  const int AiuByte = contig > 128 ? 128 : contig, AiuElem = AiuByte*8/Bits, RPS = kCon/AiuElem;
  const int nrow = N/F, KT = K/TK, NT = N/TN;
  static_assert(RowsPerTile == 256 || RowsPerTile == -1, "RowsPerTile is 256 (interleaved) or -1 (plain ColumnMajor)");
  static_assert(RowsPerTile != -1 || F == 1, "the -1 (non-interleaved) buffer has no folded form");

  // ONE domain, THREE stride tuples. Written with make_layout so the extents can be runtime N/K.
  auto dst = [&] {
    if constexpr (F > 1)
      return make_layout(make_shape (CPW, 8,   Ng,          make_shape(RUNS,  KT/RUNS),                 NT),
                         make_stride(  1,  CPW, W_ROW_OFF*CPW, make_stride(8*CPW, nrow*W_ROW_OFF*CPW),
                                     Ng*W_ROW_OFF*CPW));
    else if constexpr (RowsPerTile == 256)
      return make_layout(make_shape (CPW, 8,   Ng,   make_shape(RPS,     KT/RPS),  NT),
                         make_stride(  1,  CPW, kCon, make_stride(AiuElem, N*kCon), TN*kCon));
    else                                        // RowsPerTile == -1 : plain ColumnMajor [N][K], k contiguous
      return make_layout(make_shape (CPW, 8,   Ng, make_shape(KT, 1),      NT),
                         make_stride(  1,  CPW, K,  make_stride(TK, 0),    TN*K));
  }();

  auto m = tile_map<Bits,TM,TN,TK,WM,WN>();
  std::fill(out.begin(), out.end(), int8_t(0));
  for (int tn = 0; tn < NT; ++tn)
    for (int ki = 0; ki < KT; ++ki)
      for (int row = 0; row < Ng; ++row)
        for (int wd = 0; wd < 8; ++wd)
          for (int j = 0; j < CPW; ++j) {
            const int loc = m[((size_t)row*8 + wd)*CPW + j];
            if (loc < 0) continue;
            const int n = tn*TN + loc/TK, k = ki*TK + loc%TK;
            int val = codes[(size_t)n*K + k] & MASK;
            if (Bits == 4) val = (((int8_t)(val << 4) >> 4) + 8) & 0xF;   // add_bias_and_interleave_int4s
            // the ki mode is hierarchical in two of the three forms; cute splits it, so the walk stays flat here
            const int kin = (F > 1) ? (ki % RUNS) : (RowsPerTile == 256 ? (ki % RPS) : ki);
            const int kout = (F > 1) ? (ki / RUNS) : (RowsPerTile == 256 ? (ki / RPS) : 0);
            const size_t bitpos = (size_t)dst(make_coord(j, wd, row, make_coord(kin, kout), tn)) * Bits;
            out[bitpos/8] |= int8_t(val << (bitpos%8));
          }
}

// ---------------------------------------------------------------- the existing offline, for comparison
template <int Bits, int TN, int TK, int RowsPerTile = 256>
static void place_shipped(std::vector<int8_t>& out, const std::vector<int>& codes, int N, int K) {
  constexpr int Bits_ = Bits, EPB = 8/Bits_, MASK = (1 << Bits) - 1;
  constexpr int contig = TK*Bits/8, F = contig >= 32 ? 1 : 32/contig;
  const auto qtc = Bits==1 ? QuantTypeClass::PACKED_INT1_WEIGHT_ONLY
                 : Bits==2 ? QuantTypeClass::PACKED_INT2_WEIGHT_ONLY
                           : QuantTypeClass::PACKED_INT4_WEIGHT_ONLY;
  // the caller's packing: qT[n*K+k] packed [N][K], k contiguous
  std::vector<int8_t> packed((size_t)N*K/EPB, 0);
  for (size_t i = 0; i < (size_t)N*K; ++i)
    packed[i/EPB] |= int8_t((codes[i] & MASK) << (Bits*(i%EPB)));
  std::vector<int8_t> pre(packed.size());
  preprocess_weights_for_mixed_gemm<false,RowsPerTile,0>(pre.data(), packed.data(), {(size_t)K,(size_t)N}, qtc);
  if (F > 1) { std::vector<int8_t> f(pre.size());
               legacy::nfold_regroup_gmem(f.data(), pre.data(), {(size_t)K,(size_t)N}, TN, TK, Bits); pre.swap(f); }
  out = pre;
}

template <int Bits, int TM, int TN, int TK, int WM, int WN, int RowsPerTile = 256>
static bool compare(const char* tag, int N, int K) {
  constexpr int Bits_ = Bits, EPB = 8/Bits_, MASK = (1 << Bits) - 1;
  constexpr int contig = TK*Bits/8, F = contig >= 32 ? 1 : 32/contig;
  std::vector<int> codes((size_t)N*K);
  for (size_t i = 0; i < codes.size(); ++i) codes[i] = int((i*2654435761u >> 7) & MASK);
  std::vector<int8_t> a((size_t)N*K/EPB), b;
  place_derived<Bits,TM,TN,TK,WM,WN,RowsPerTile>(a, codes, N, K);
  place_shipped<Bits,TN,TK,RowsPerTile>(b, codes, N, K);
  size_t diff = 0; for (size_t i = 0; i < a.size(); ++i) if (a[i] != b[i]) ++diff;
  printf("  %-26s int%d (%d,%d,%d) w%dx%d F=%d RPT=%d %dx%d : %zu / %zu bytes differ  %s\n",
         tag, Bits, TM, TN, TK, WM, WN, F, RowsPerTile, N, K, diff, a.size(),
         diff ? "" : "<-- BIT-IDENTICAL");
  return diff == 0;
}

int main() {
  printf("L20 -- the derived offline vs the shipped one, byte for byte\n\n");
  bool ok = true;
  printf("  == fold configs\n");
  ok &= compare<1, 32, 128, 128, 32, 32>("int1 fold", 256, 512);
  ok &= compare<2, 64,  64,  64, 32, 32>("int2 fold", 256, 512);
  ok &= compare<2, 64, 128,  64, 32, 32>("int2 fold wideN", 256, 512);
  ok &= compare<4, 64,  64,  32, 32, 32>("int4 fold TK=32", 256, 512);
  printf("  == does the SHIPPED offline still match at WN=64? The offline is WN-independent (it only takes TN/TK/bits)\n");
  printf("     but the REQUIRED placement depends on WN through the fragment, so it can be right for only one WN.\n");
  ok &= compare<1, 32, 128, 128, 32, 64>("int1 TK128 WN=64", 256, 512);
  ok &= compare<1, 64, 128, 256, 32, 64>("int1 TK256 WN=64", 256, 512);
  printf("     => placement is WN-INVARIANT: pi and partition_B both move with MMA_N and the changes cancel.\n");
  printf("        So WN only changes the DELIVERY BOUND, not the required buffer. What forces a bit-granular packer\n");
  printf("        is TK: at int1/TK=64 a 32-bit word must carry two logical columns, which whole-word moves cannot do.\n");
  { std::vector<int> codes((size_t)256*512);
    for (size_t i = 0; i < codes.size(); ++i) codes[i] = int((i*2654435761u >> 7) & 1);
    std::vector<int8_t> a((size_t)256*512/8), b;
    place_derived<1,64,128,64,32,64>(a, codes, 256, 512);
    place_shipped<1,128,64>(b, codes, 256, 512);
    size_t d = 0; for (size_t i = 0; i < a.size(); ++i) if (a[i] != b[i]) ++d;
    printf("  int1 TK=64 WN=64 (needs bitpack)  256x512 : %zu / %zu bytes differ  %s\n", d, a.size(),
           d ? "<-- shipped offline CANNOT express it, as expected" : "<-- unexpectedly identical"); }
  printf("  == unfolded (F=1) configs, including int4's production shape\n");
  ok &= compare<4, 64,  64,  64, 32, 32>("int4 PRODUCTION", 128, 512);
  ok &= compare<2, 64,  64, 128, 32, 32>("int2 unfolded", 128, 512);
  ok &= compare<1, 64,  64, 256, 32, 32>("int1 unfolded", 128, 512);
  // ============================================================ the two things that can still VETO the swap
  // Byte-identity was never the open question after l20 passed; these were. Both are measurable here, no box needed.
  printf("\n  == REALISTIC SHAPES. Every config above is 256x512 or 128x512 -- a toy. The K>256 bug lived in the\n");
  printf("     interleave step, so the sizes that matter are the ones a real checkpoint has.\n");
  ok &= compare<4, 64,  64,  64, 32, 32>("int4 PROD 4096x4096",   4096, 4096);
  ok &= compare<1, 32, 128, 128, 32, 32>("int1 fold 4096x4096",   4096, 4096);
  ok &= compare<2, 64,  64,  64, 32, 32>("int2 fold 2560x1536",   2560, 1536);   // non-square
  ok &= compare<4, 64,  64,  64, 32, 32>("int4 PROD 4096x11008",  4096, 11008);  // FFN shape, 11008 = 43*256
  ok &= compare<1, 64,  64, 256, 32, 32>("int1 unfolded 4096x4096", 4096, 4096);

  // ============================================================ RowsPerTile = -1, as a THIRD STRIDE TUPLE
  // The question this answers: does dropping the five steps drop -1 support? No -- -1 is not a missing derivation, it
  // is a different destination stride tuple over the same physical-slot domain. The source side (tile_map) is
  // untouched. Compared against preprocess_weights_for_mixed_gemm<false,-1>, which skips the interleave step, so this
  // is the same byte-for-byte standard the 256 path is held to. -1 requires F == 1 (there is no folded non-interleaved
  // buffer), which the static_assert in place_derived enforces.
  printf("\n  == RowsPerTile = -1 (plain ColumnMajor): a third stride tuple, not a third derivation\n");
  ok &= compare<4, 64,  64,  64, 32, 32, -1>("int4 unfolded RPT=-1",  128, 512);
  ok &= compare<2, 64,  64, 128, 32, 32, -1>("int2 unfolded RPT=-1",  128, 512);
  ok &= compare<1, 64,  64, 256, 32, 32, -1>("int1 unfolded RPT=-1",  128, 512);
  ok &= compare<4, 64,  64,  64, 32, 32, -1>("int4 RPT=-1 4096x4096", 4096, 4096);
  printf("     => -1 was previously code with NO call site (27 instantiations in the tree all pass 256; the only -1\n");
  printf("        is one commented-out line) and NO numeric validation. As a layout it is now byte-identical-verified,\n");
  printf("        which is strictly better than what deleting the five steps would have removed.\n");

  // ============================================================ THE LOAD-BEARING CLAIM FOR KEEPING THE SIGNATURE
  // preprocess_weights_for_mixed_gemm takes (out, in, shape, qtc) and NO tile parameters, so if the derived walk is to
  // replace it without touching 35 call sites, the buffer it produces must not depend on the tile. That is implied by
  // every BIT-IDENTICAL line above (the shipped side is tile-independent by construction for F=1), but implied at ONE
  // tile per width is not the same as true. Check it directly: derived at tile A vs derived at tile B, same width.
  printf("\n  == TILE-INVARIANCE of the derived buffer (what lets the signature stay tile-free)\n");
  {
    auto cmp2 = [&](const char* tag, const std::vector<int8_t>& a, const std::vector<int8_t>& b) {
      size_t d = 0; for (size_t i = 0; i < a.size(); ++i) if (a[i] != b[i]) ++d;
      printf("     %-46s : %zu / %zu differ  %s\n", tag, d, a.size(), d ? "<-- TILE-DEPENDENT" : "invariant");
      return d == 0;
    };
    constexpr int N = 512, K = 1024;
    std::vector<int> codes((size_t)N*K);
    for (size_t i = 0; i < codes.size(); ++i) codes[i] = int((i*2654435761u >> 3) & 0xF);
    // int4, all four unfolded/folded tiles the tree uses
    { std::vector<int8_t> a((size_t)N*K*4/8), b(a.size()), c(a.size()), d(a.size());
      place_derived<4,64, 64, 64,32,32>(a, codes, N, K);
      place_derived<4,64,128, 64,32,64>(b, codes, N, K);
      place_derived<4,32, 64, 64,32,32>(c, codes, N, K);
      place_derived<4,64, 64,128,32,32>(d, codes, N, K);
      ok &= cmp2("int4 (64,64,64)w32x32 vs (64,128,64)w32x64", a, b);
      ok &= cmp2("int4 (64,64,64)w32x32 vs (32,64,64)w32x32",  a, c);
      // non-voting: differing here is the FINDING (the run length matters), not a failure.
      cmp2("int4 (64,64,64) vs (64,64,128) [run 32B vs 64B]", a, d); }
    // int2: TK=64 folds (F=2), TK=128 does not (F=1) -- so these MUST differ, and that is the point
    { std::vector<int8_t> a((size_t)N*K*2/8), b(a.size()), c(a.size());
      place_derived<2,64, 64, 64,32,32>(a, codes, N, K);
      place_derived<2,64,128, 64,32,32>(b, codes, N, K);
      place_derived<2,64, 64,128,32,32>(c, codes, N, K);
      ok &= cmp2("int2 TN 64 vs 128 at TK=64 (both F=2)", a, b);
      ok &= cmp2("int2 TK 64 F=2 vs TK 128 F=1 [both 32B run]", a, c); }
    // int1: TK=128 folds, TK=256 does not
    { std::vector<int8_t> a((size_t)N*K/8), b(a.size()), c(a.size());
      place_derived<1,32,128,128,32,32>(a, codes, N, K);
      place_derived<1,32,128,128,32,64>(b, codes, N, K);
      place_derived<1,64, 64,256,32,32>(c, codes, N, K);
      ok &= cmp2("int1 TK=128 w32x32 vs w32x64 (WN-invariance, again)", a, b);
      ok &= cmp2("int1 TK 128 F=2 vs TK 256 F=1 [both 32B run]", a, c); }
    // WHAT THE NUMBERS ACTUALLY SAY -- and it is not what I first wrote here. I predicted "dependent on TK only
    // through the fold factor F". Both halves are refuted above: int4 TK=64 vs TK=128 DIFFER although F=1 in both,
    // and int2 TK=64 (F=2) vs TK=128 (F=1) are IDENTICAL although F differs. The quantity that actually decides the
    // buffer is the AIU CONTIGUOUS RUN, min(F*TK*bits/8, 128) bytes:
    //     int4 TK=64  -> 32 B     int4 TK=128 -> 64 B     differ
    //     int2 TK=64  -> 2*16 = 32 B   int2 TK=128 -> 32 B     identical
    //     int1 TK=128 -> 2*16 = 32 B   int1 TK=256 -> 32 B     identical
    // The int2/int1 identities are the N-fold's design statement confirmed as a byte fact: folding F columns at TK is
    // the SAME gmem buffer as not folding at F*TK. And it names the one parameter a tile-free signature still needs --
    // the run length, which every caller already computes for legacy::nfold_regroup_gmem(fold_tn, fold_tk).
    auto runB = [](int bits, int tk) { const int c = tk*bits/8, f = c >= 32 ? 1 : 32/c; const int r = f*c; return r > 128 ? 128 : r; };
    printf("     => the invariant is the AIU CONTIGUOUS RUN min(F*TK*bits/8,128) B, NOT the fold factor:\n");
    printf("        int4 TK64=%dB TK128=%dB (differ)   int2 TK64=%dB TK128=%dB (same)   int1 TK128=%dB TK256=%dB (same)\n",
           runB(4,64), runB(4,128), runB(2,64), runB(2,128), runB(1,128), runB(1,256));
    printf("        invariant in TM, TN, WN -- so the signature needs the RUN LENGTH, not the tile.\n");
  }

  // Does the SHIPPED offline match int4 at TK=128 too, or is it silently tied to ONE run length per width? The
  // consequence matters for the swap: if it matches only one, then today's five steps are already TK-specific and the
  // derived walk is not losing generality by taking the run length as a parameter -- it is making an existing implicit
  // assumption explicit.
  // NOT a voting check: a mismatch here is a statement about the SHIPPED side, not a failure of the derived walk.
  printf("\n  == is the shipped offline tied to one run length per width? (mismatch EXPECTED, and it is a finding)\n");
  compare<4, 64,  64, 128, 32, 32>("int4 TK=128 (64 B run) vs shipped", 512, 1024);
  printf("     => it is. The five steps produce the 32 B-run buffer only, so int4 at TK=128 -- which\n");
  printf("        test_scalefirst_bench's I4(64,64,128,...) row actually launches -- runs on a buffer laid out for a\n");
  printf("        DIFFERENT run length. Harmless for a timing-only row, wrong for any numeric test at that shape.\n");
  printf("        So taking the run length as an explicit parameter is not a loss of generality; it makes an existing\n");
  printf("        implicit assumption visible.\n");

  printf("\n  == RUNTIME, the one number never taken. The SHIPPED path makes FIVE passes over the whole buffer (two\n");
  printf("     subbyte transposes, a row permute, interleave-256, an in-place bit interleave); the derived one makes\n");
  printf("     ONE, from a tile map computed once. If the derived walk were slower this would be a real cost at\n");
  printf("     checkpoint-conversion time, which is why it stayed an open item rather than an assumption.\n");
  {
    constexpr int N = 4096, K = 4096;
    std::vector<int> codes((size_t)N*K);
    for (size_t i = 0; i < codes.size(); ++i) codes[i] = int((i*2654435761u >> 5) & 0xF);
    std::vector<int8_t> a((size_t)N*K*4/8), b;
    auto t0 = std::chrono::steady_clock::now();
    place_derived<4,64,64,64,32,32>(a, codes, N, K);
    auto t1 = std::chrono::steady_clock::now();
    place_shipped<4,64,64>(b, codes, N, K);
    auto t2 = std::chrono::steady_clock::now();
    const double dms = std::chrono::duration<double, std::milli>(t1-t0).count();
    const double sms = std::chrono::duration<double, std::milli>(t2-t1).count();
    printf("     int4 4096x4096 (8 MB of codes):  derived %7.1f ms   shipped %7.1f ms   -> derived is %.2fx %s\n",
           dms, sms, sms > dms ? sms/dms : dms/sms, sms > dms ? "FASTER" : "SLOWER");
    printf("     (place_shipped includes the code->packed and packed->code marshalling the harness needs, so read\n");
    printf("      this as an order-of-magnitude check, not a benchmark.)\n");
  }

  printf("\n  == WHAT IS STILL OUT OF SCOPE: place_derived hardcodes the interleave-256 destination layout, so it\n");
  printf("     covers RowsPerTile=256 only. filter_and_run picks the interleaved kernel via (n%%256==0 && k%%256==0)\n");
  printf("     and otherwise runs a NON-interleaved path that preprocess_weights_for_mixed_gemm<..,-1> serves. That\n");
  printf("     branch has no derived equivalent yet -- so the five steps can be deleted for the interleaved path and\n");
  printf("     must stay for RowsPerTile=-1 until it is derived too.\n");
  printf("\n  ALL: %s\n", ok ? "PASS -- the derived placement can replace the five steps by construction" : "FAIL");
  return ok ? 0 : 1;
}
