#!/usr/bin/env python3
"""Close the exact FullyQuantized internal-sweep denominator.

The support authority is generated by ``fully_quantized_internal_matrix``;
device logs may replace only its two explicit compiled-admission states.  A
runtime, correctness, build, duplicate, or missing-record failure makes the
component INCOMPLETE.  S1 tensor-core and placed BC GEMV are full-output
results.  S2/S4/S8 are producer-only measurements whose real reducer is run
untimed and must close raw-fp16 correctness after every timing series.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
import math
import os
import pathlib
import re
import shutil
import statistics
import sys
from typing import Any

import fully_quantized_internal_matrix as matrix
import gen_fully_quantized_splitk_producer_units as generator


SCHEMA = "quactlize.fully_quantized_internal_sweep.v2"
INVENTORY_SCHEMA = "quactlize.gguf_internal_shape_inventory.v2"
PLAN_SCHEMA = "quactlize.fully_quantized_internal_plan.v1"
RESOLVED_MODELS_SCHEMA = "quactlize.internal_sweep.resolved_models.v1"
VALID_QTYPES = {10, 11, 12, 13, 14}
FULL = "FULL_OUTPUT"
PRODUCER = "PRODUCER_ONLY_REDUCER_EXCLUDED"
BLOCK_BYTES = {10: 84, 11: 110, 12: 144, 13: 176, 14: 210}
TC_PREFIX = "FQ_TC_CELL "
BC_PREFIX = "FQ_BC_CELL "
SHAPE_DONE_PREFIX = "FQ_SHAPE_DONE "
SHARD_RE = re.compile(r"^q(\d+)-a(\d+)-bc([01])$")
EXPECTED_SOURCE_HASHES = {
    "benchmarks/fully_quantized_splitk_producer_bench.hpp",
    "benchmarks/fully_quantized_splitk_producer_unit.inc",
    "benchmarks/test_fully_quantized_internal_sweep.cu",
    "quactlize/csrc/fq_internal_sweep.cmake.in",
    "quactlize/csrc/CMakeLists.txt.in",
    "quactlize/csrc/device/ppu_dense_layout.cu",
    "quactlize/include/dense_splitk_multiformat_ppu.cuh",
    "quactlize/include/dense_splitk_parallel_ppu.cuh",
    "quactlize/include/gguf_bc_vecdot.hpp",
    "quactlize/include/gguf_packed_unit.hpp",
    "quactlize/include/ppu_format_config.inc",
    "quactlize/include/ppu_group_schedule.hpp",
    "quactlize/include/ppu_tactic_space.hpp",
    "tests/helper.h",
    "tools/analyze_fully_quantized_internal_sweep.py",
    "tools/emit_fully_quantized_splitk_superset.cpp",
    "tools/fully_quantized_internal_matrix.py",
    "tools/gen_fully_quantized_splitk_producer_units.py",
    "tools/probe_box_identity.py",
    "tools/box_identity_schema.py",
    "tools/box_identity_probe.cpp",
    "tools/run_fully_quantized_internal_sweep_box.sh",
    "ci/check_fq_internal_runner_contract.py",
    "build.sh",
    "tree/quactlize/include",
    "tree/third_party/actlize/include",
    "tree/third_party/actlize/tools/util/include",
}


def sha256(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def canonical(value: Any) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"),
                      ensure_ascii=False)


def require_sha256(value: Any, field: str) -> str:
    text = str(value)
    if not re.fullmatch(r"[0-9a-f]{64}", text):
        raise ValueError(f"{field} must be a lowercase sha256")
    return text


def runtime_authority(raw_root: pathlib.Path, expected_shards: set[str],
                      run_contract_path: pathlib.Path,
                      generated_hashes: dict[str, str],
                      binary_hashes: dict[str, str]) -> dict[str, dict[str, Any]]:
    """Validate each run as one committed log/rc/authority transaction."""
    observed = {
        path.parent.name for pattern in ("q*-a*-bc*/run.log",
                                         "q*-a*-bc*/run.rc",
                                         "q*-a*-bc*/run.commit.json")
        for path in raw_root.glob(pattern)
    }
    if observed != expected_shards:
        raise ValueError(
            "runtime evidence shard set differs from exact binary graph: "
            f"missing={sorted(expected_shards-observed)} "
            f"extra={sorted(observed-expected_shards)}")
    contract_sha = sha256(run_contract_path)
    result: dict[str, dict[str, Any]] = {}
    for shard in sorted(expected_shards):
        directory = raw_root / shard
        log = directory / "run.log"
        rc_path = directory / "run.rc"
        commit_path = directory / "run.commit.json"
        if not all(path.is_file() for path in (log, rc_path, commit_path)):
            raise ValueError(f"runtime shard {shard} lacks log/rc/commit authority")
        rc_text = rc_path.read_text().strip()
        if not rc_text.isdigit() or not 0 <= int(rc_text) <= 255:
            raise ValueError(f"runtime shard {shard} has malformed run.rc")
        commit = json.loads(commit_path.read_text())
        expected = {
            "schema": "quactlize.fully_quantized_internal_sweep.run_commit.v1",
            "rc": int(rc_text),
            "run_log_sha256": sha256(log),
            "run_rc_sha256": sha256(rc_path),
            "run_contract_sha256": contract_sha,
            "generated_source_sha256": generated_hashes.get(shard),
            "binary_sha256": binary_hashes.get(shard),
        }
        if commit != expected or any(value is None for value in expected.values()):
            raise ValueError(f"runtime shard {shard} authority changed")
        result[shard] = {
            "rc": int(rc_text),
            "run_log_sha256": expected["run_log_sha256"],
            "run_rc_sha256": expected["run_rc_sha256"],
            "run_commit_sha256": sha256(commit_path),
        }
    return result


def _inventory_group_size(spec: dict[str, Any], qtype: int) -> int | str:
    counts = spec.get("qtype_counts")
    if not isinstance(counts, dict) or str(qtype) not in counts:
        raise ValueError(f"inventory-v2 lacks qtype_counts[{qtype}]")
    entry = counts[str(qtype)]
    traits = entry.get("traits") if isinstance(entry, dict) else None
    if not isinstance(traits, dict):
        raise ValueError(f"inventory-v2 qtype {qtype} lacks declared traits")
    known = traits.get("quant_group_size_known")
    group = traits.get("quant_group_size")
    if known is True:
        if isinstance(group, bool) or not isinstance(group, int) or group < 0:
            raise ValueError(
                f"inventory-v2 qtype {qtype} declares invalid group size {group!r}")
        # Zero is the explicit, known "not quantized in groups" value for
        # F32/F16/BF16-style GGUF types.  It remains visible in the finite
        # denominator as g0, but these quantized components must terminate it
        # as UNSUPPORTED rather than compile or rank it.
        return group
    if known is False and group == 0:
        return "UNKNOWN"
    raise ValueError(
        f"inventory-v2 qtype {qtype} has inconsistent group-size authority")


def _flat_inventory_shape(row: dict[str, Any], group_size: int | str
                          ) -> dict[str, Any]:
    """Validate one inventory-v2 row without reconstructing its identity.

    The v2 inventory, not this component, owns model/TP/route/grouped and
    source-tensor provenance.  Requiring every field here prevents a v1
    single-GGUF row from being silently upgraded with guessed defaults.
    """
    required = (
        "model_id", "dedup_key", "sources", "tp_world", "tp_rank",
        "tp_partition", "problem_kind", "qtype", "M", "N", "K", "L",
        "experts", "top_k", "active", "ragged", "shape_directory",
        "status", "reason",
    )
    missing = [name for name in required if name not in row]
    if missing:
        raise ValueError(
            f"inventory-v2 sweep shape {row.get('dedup_key', '<unknown>')} "
            f"lacks canonical fields {missing}")
    sources = row["sources"]
    if not isinstance(sources, list) or not sources:
        raise ValueError("inventory-v2 sources must be a nonempty list")
    tensors: list[str] = []
    for source in sources:
        if (not isinstance(source, (list, tuple)) or len(source) != 3 or
                not all(isinstance(item, str) and item for item in source)):
            raise ValueError(
                "inventory-v2 sources must contain [tensor,role,cell_id] triples")
        require_sha256(source[2], "inventory-v2 source cell_id")
        tensors.append(source[0])
    declared_tensors = row.get("source_tensors")
    if (not isinstance(declared_tensors, list) or not declared_tensors or
            not all(isinstance(item, str) and item for item in declared_tensors)):
        raise ValueError("inventory-v2 source_tensors must be a nonempty string list")
    if sorted(set(tensors)) != sorted(set(declared_tensors)):
        raise ValueError("inventory-v2 sources and source_tensors disagree")
    route = str(row["problem_kind"]).lower()
    if route not in {"dense", "grouped"}:
        raise ValueError(
            f"inventory-v2 problem_kind must be dense/grouped, got {route!r}")
    shape_id = require_sha256(row["dedup_key"], "inventory-v2 dedup_key")
    dimensions: dict[str, int] = {}
    for upper in ("M", "N", "K", "L"):
        value = row[upper]
        if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
            raise ValueError(f"inventory-v2 {shape_id} has invalid {upper}={value!r}")
        dimensions[upper.lower()] = value
    grouped = None
    if route == "dense":
        if any(row[name] is not None for name in
               ("experts", "top_k", "active", "ragged")):
            raise ValueError("dense inventory-v2 shape carries grouped identity")
        if dimensions["l"] != 1:
            raise ValueError("dense inventory-v2 shape must have L=1")
    else:
        for name in ("experts", "top_k", "active"):
            value = row[name]
            if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
                raise ValueError(
                    f"grouped inventory-v2 shape has invalid {name}={value!r}")
        ragged = row["ragged"]
        if not isinstance(ragged, str) or not ragged:
            raise ValueError("grouped inventory-v2 shape lacks ragged identity")
        if row["active"] > row["experts"] or row["top_k"] > row["experts"]:
            raise ValueError("grouped inventory-v2 active/top_k exceeds experts")
        if dimensions["l"] != row["experts"]:
            raise ValueError("grouped inventory-v2 L differs from experts")
        grouped = {
            "experts": row["experts"], "active": row["active"],
            "top_k": row["top_k"], "ragged": ragged,
        }
    status = str(row["status"])
    reason = str(row["reason"])
    if status not in {"SUPPORTED", "UNSUPPORTED"} or not reason:
        raise ValueError(
            f"inventory-v2 {shape_id} has invalid terminal {status}/{reason}")
    result = dict(row)
    result.update(dimensions)
    result["shape_id"] = shape_id
    result["problem_route"] = route
    result["source_tensors"] = sorted(set(tensors))
    result["group_size"] = group_size
    result["grouped"] = grouped
    result["inventory_status"] = status
    result["inventory_reason"] = reason
    return result


def _materialize_spec(spec: dict[str, Any], spec_path: pathlib.Path,
                      manifest_sha256: str) -> dict[str, Any]:
    if spec.get("schema") != INVENTORY_SCHEMA:
        raise ValueError(
            f"{spec_path}: expected {INVENTORY_SCHEMA}; v1/single-GGUF plans "
            "are deliberately not adapted")
    shapes = spec.get("sweep_shapes")
    if not isinstance(shapes, list) or not shapes:
        raise ValueError("inventory-v2 has no sweep_shapes")
    if spec.get("status") != "COMPLETE":
        raise ValueError("inventory-v2 is not COMPLETE")
    declared_count = spec.get("deduplicated_shape_count")
    if declared_count != len(shapes):
        raise ValueError(
            f"inventory-v2 shape denominator drift {len(shapes)}/{declared_count}")
    models = spec.get("models")
    if not isinstance(models, list) or not models:
        raise ValueError("inventory-v2 has no models")
    model_hashes: dict[str, str] = {}
    for model in models:
        if not isinstance(model, dict):
            raise ValueError("inventory-v2 models contains a non-object")
        model_id = str(model.get("model_id", ""))
        if not model_id or model_id in model_hashes:
            raise ValueError(f"inventory-v2 model ID empty/duplicate: {model_id!r}")
        model_hashes[model_id] = require_sha256(
            model.get("fileset_sha256"), f"{model_id}.fileset_sha256")
    if spec.get("model_count") != len(models):
        raise ValueError("inventory-v2 model denominator drift")
    resolved_set_sha256 = require_sha256(
        spec.get("resolved_set_sha256"), "resolved_set_sha256")
    inventory_provenance = spec.get("provenance")
    if not isinstance(inventory_provenance, dict):
        raise ValueError("inventory-v2 lacks provenance")
    gguf_hashes = inventory_provenance.get("gguf_hashes")
    if not isinstance(gguf_hashes, dict):
        raise ValueError("inventory-v2 provenance.gguf_hashes is not an object")
    gguf_hashes = {
        str(model): require_sha256(digest, f"gguf_hashes.{model}")
        for model, digest in gguf_hashes.items()
    }
    if gguf_hashes != model_hashes:
        raise ValueError("inventory-v2 provenance member map differs from models")
    gguf_set_sha256 = require_sha256(
        inventory_provenance.get("gguf_set_sha256"), "gguf_set_sha256")
    if gguf_set_sha256 != hashlib.sha256(
            canonical(gguf_hashes).encode("utf-8")).hexdigest():
        raise ValueError("inventory-v2 gguf_set_sha256 does not bind gguf_hashes")
    shape_directory = inventory_provenance.get("shape_directory")
    if not isinstance(shape_directory, dict) or set(shape_directory) != {"dense", "grouped"}:
        raise ValueError(
            "inventory-v2 provenance.shape_directory must define dense and grouped")
    if shape_directory != spec.get("shape_directory_contract"):
        raise ValueError("inventory-v2 shape-directory authorities disagree")
    workload_axes = spec.get("workload_axes")
    if not isinstance(workload_axes, dict):
        raise ValueError("inventory-v2 lacks workload_axes")
    cells: list[dict[str, Any]] = []
    for row in shapes:
        if not isinstance(row, dict):
            raise ValueError("inventory-v2 sweep_shapes contains a non-object")
        qtype = row.get("qtype")
        if isinstance(qtype, bool) or not isinstance(qtype, int) or qtype < 0:
            raise ValueError(f"inventory-v2 shape has invalid qtype={qtype!r}")
        cells.append(_flat_inventory_shape(
            row, _inventory_group_size(spec, qtype)))
    cell_models = {str(cell["model_id"]) for cell in cells}
    declared_models = set(model_hashes)
    if cell_models != declared_models:
        raise ValueError(
            "inventory-v2 model set differs from sweep-shape model set: "
            f"missing_shapes={sorted(declared_models-cell_models)} "
            f"unknown_models={sorted(cell_models-declared_models)}")
    identities = [canonical({
        key: cell[key] for key in (
            "model_id", "shape_id", "tp_world", "tp_rank", "tp_partition",
            "problem_route", "group_size", "grouped", "qtype", "m", "n", "k")
    }) for cell in cells]
    if len(identities) != len(set(identities)):
        raise ValueError("inventory-v2 expansion produced duplicate component shapes")
    plan = {
        "schema": PLAN_SCHEMA,
        "source_schema": INVENTORY_SCHEMA,
        "source_manifest": str(spec_path.resolve()),
        "provenance": {
            "shape_manifest_sha256": manifest_sha256,
            "gguf_hashes": gguf_hashes,
            "gguf_set_sha256": gguf_set_sha256,
            "resolved_set_sha256": resolved_set_sha256,
            "shape_directory": shape_directory,
            "workload_axes": workload_axes,
            "resolved_models_schema": spec.get("resolved_models_schema"),
            "format_registry_sha256": require_sha256(
                spec.get("format_registry_sha256"), "format_registry_sha256"),
        },
        "cells": cells,
    }
    return plan


def materialize_plan(spec_path: pathlib.Path, output: pathlib.Path) -> dict[str, Any]:
    spec = json.loads(spec_path.read_text())
    plan = _materialize_spec(spec, spec_path, sha256(spec_path))
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(plan, indent=2, sort_keys=True) + "\n")
    return plan


def load_plan(path: pathlib.Path) -> dict[str, Any]:
    plan = json.loads(path.read_text())
    if plan.get("schema") != PLAN_SCHEMA:
        raise ValueError(f"{path}: expected materialized schema {PLAN_SCHEMA}")
    cells = plan.get("cells")
    if not isinstance(cells, list) or not cells:
        raise ValueError("materialized plan has no cells")
    provenance = plan.get("provenance")
    if not isinstance(provenance, dict):
        raise ValueError("materialized plan lacks provenance")
    return plan


def _validate_resolved_document(plan: dict[str, Any], resolved: dict[str, Any],
                                source: str) -> None:
    if resolved.get("schema") != RESOLVED_MODELS_SCHEMA:
        raise ValueError(
            f"{source}: expected {RESOLVED_MODELS_SCHEMA}")
    models = resolved.get("models")
    if not isinstance(models, list) or not models:
        raise ValueError("resolved model set is empty")
    by_id: dict[str, dict[str, Any]] = {}
    for model in models:
        model_id = str(model.get("model_id", ""))
        if not model_id or model_id in by_id:
            raise ValueError(f"resolved model ID is empty/duplicate: {model_id!r}")
        require_sha256(model.get("fileset_sha256"), f"{model_id}.fileset_sha256")
        world = model.get("tp_world_size")
        if isinstance(world, bool) or not isinstance(world, int) or world < 1:
            raise ValueError(f"{model_id}: invalid tp_world_size={world!r}")
        by_id[model_id] = model
    resolved_hashes = {
        model_id: model["fileset_sha256"] for model_id, model in by_id.items()
    }
    provenance = plan["provenance"]
    if provenance.get("gguf_hashes") != resolved_hashes:
        raise ValueError("materialized plan GGUF member map differs from GGUF_SET")
    if provenance.get("shape_directory") != resolved.get("shape_directory"):
        raise ValueError("materialized plan shape_directory differs from GGUF_SET catalog")
    if provenance.get("workload_axes") != resolved.get("workload_axes"):
        raise ValueError("materialized plan workload_axes differs from GGUF_SET catalog")
    if provenance.get("resolved_set_sha256") != resolved.get("resolved_set_sha256"):
        raise ValueError("materialized plan resolved-set identity differs from GGUF_SET")
    cells_by_model: dict[str, list[dict[str, Any]]] = collections.defaultdict(list)
    for cell in plan["cells"]:
        model_id = str(cell["model_id"])
        if model_id not in by_id:
            raise ValueError(f"plan contains unbound model_id={model_id}")
        if int(cell["tp_world"]) != int(by_id[model_id]["tp_world_size"]):
            raise ValueError(f"{model_id}: plan TP world differs from resolved catalog")
        cells_by_model[model_id].append(cell)
    if set(cells_by_model) != set(by_id):
        raise ValueError(
            "materialized plan model set differs from resolved catalog: "
            f"missing={sorted(set(by_id)-set(cells_by_model))} "
            f"extra={sorted(set(cells_by_model)-set(by_id))}")
    for model_id, model_cells in cells_by_model.items():
        world = int(by_id[model_id]["tp_world_size"])
        ranks = {int(cell["tp_rank"]) for cell in model_cells}
        if ranks != {0}:
            raise ValueError(
                f"{model_id}: inventory-v2 represents symmetric TP kernels at rank 0, "
                f"got ranks={sorted(ranks)} for world={world}")


def validate_resolved_models(plan: dict[str, Any], resolved_path: pathlib.Path) -> None:
    resolved = json.loads(resolved_path.read_text())
    _validate_resolved_document(plan, resolved, str(resolved_path))


def parse_kv(line: str, prefix: str) -> dict[str, str]:
    if not line.startswith(prefix):
        raise ValueError(f"record lacks prefix {prefix!r}")
    fields: dict[str, str] = {}
    for token in line[len(prefix):].strip().split():
        if "=" not in token:
            raise ValueError(f"non key=value token in runtime record: {token!r}")
        key, value = token.split("=", 1)
        if key in fields:
            raise ValueError(f"duplicate runtime field {key!r}")
        fields[key] = value
    return fields


def parse_samples(text: str) -> list[float]:
    value = json.loads(text)
    if not isinstance(value, list):
        raise ValueError("samples is not an array")
    samples = [float(item) for item in value]
    if any(not math.isfinite(item) or item <= 0 for item in samples):
        raise ValueError(f"samples contain a non-positive/non-finite value: {samples}")
    return samples


def parse_shape(text: str) -> tuple[int, int, int]:
    match = re.fullmatch(r"(\d+)x(\d+)x(\d+)", text)
    if not match:
        raise ValueError(f"invalid shape {text!r}")
    shape = tuple(map(int, match.groups()))
    if min(shape) <= 0:
        raise ValueError(f"non-positive shape {shape}")
    return shape


def fold_for(bits: int, artifact: int) -> int:
    if bits == 0:
        return 1
    run_bits = bits * artifact
    if run_bits % 8:
        raise ValueError(f"non-byte plane run bits={bits} A={artifact}")
    run = run_bits // 8
    if run >= 32:
        return 1
    if run <= 0 or 32 % run:
        raise ValueError(f"plane run cannot fold to 32B: {run}")
    return 32 // run


def layout_for(fmt: matrix.Format, artifact: int) -> dict[str, Any]:
    low = fold_for(fmt.low_bits, artifact)
    high = fold_for(fmt.high_bits, artifact)
    return {
        "name": f"xplane-q{fmt.qtype}-a{artifact}-f{low}x{high}-packed-unit",
        "artifact_tile_k": artifact,
        "fold_n": {"low": low, "high": high},
        "metadata": "GGUF_PACKED_UNIT",
    }


def tactic_name(tactic: dict[str, Any]) -> str:
    return (f"{tactic['tile_m']}x{tactic['tile_n']}x{tactic['tactic_tile_k']}_"
            f"w{tactic['warp_m']}x{tactic['warp_n']}_s{tactic['stages']}_"
            f"bc{tactic['bchunk']}")


def runtime_symbol(qtype: int, artifact: int,
                   tactic: dict[str, Any], a_provider: str) -> str:
    row = matrix.Tactic(
        tactic["tile_m"], tactic["tile_n"], tactic["tactic_tile_k"],
        tactic["warp_m"], tactic["warp_n"], tactic["stages"],
        tactic["bchunk"], tactic.get("source_status", ""),
        tactic.get("source_reason", ""))
    return generator.symbol(qtype, artifact, row,
                            1 if a_provider == "packed-row" else 0)


def metric(shape: tuple[int, int, int], qtype: int, split: int,
           algorithm: str, us: float, partial_bytes: int,
           peak_tflops: float, hbm_gbs: float) -> tuple[float, float, str]:
    m, n, k = shape
    operations = 2.0 * m * n * k
    mfu = operations / us / (peak_tflops * 1e6) * 100.0
    resident = n * (k // 256) * BLOCK_BYTES[qtype]
    if algorithm == "bc-gemv":
        byte_count = resident + 2 * k + 4 * n
        kind = "DISTINCT_PACKED_WEIGHT_PLUS_A_PLUS_FP32_D"
    elif split == 1:
        byte_count = resident + 2 * m * k + 2 * m * n
        kind = "DISTINCT_PACKED_WEIGHT_PLUS_A_PLUS_FP16_D"
    else:
        byte_count = resident + 2 * m * k + partial_bytes
        kind = "PRODUCER_DISTINCT_PLUS_FP32_PARTIAL_WRITE_MODEL"
    mbu = byte_count / us / (hbm_gbs * 1000.0) * 100.0
    return mfu, mbu, kind


def cell_id(identity: dict[str, Any]) -> str:
    return hashlib.sha256(canonical(identity).encode()).hexdigest()


def plan_dim(plan_cell: dict[str, Any], lower: str) -> int:
    upper = lower.upper()
    if lower in plan_cell:
        return int(plan_cell[lower])
    return int(plan_cell[upper])


def workload_metadata(plan_cell: dict[str, Any],
                      registry_group_size: int | None = None) -> dict[str, Any]:
    """Emit the shared flat component schema; merger normalizes it once."""
    model_id = str(plan_cell.get("model_id", plan_cell.get("model", "model-unknown")))
    problem_route = str(plan_cell.get(
        "problem_route", plan_cell.get("route_class", "dense"))).lower()
    if problem_route not in {"dense", "grouped"}:
        route = str(plan_cell.get("route", ""))
        problem_route = "grouped" if route.startswith("grouped_") else "dense"
    raw_sources = plan_cell.get("source_tensors")
    if raw_sources is None:
        sources = plan_cell.get("sources")
        if isinstance(sources, list):
            raw_sources = [item.get("tensor") if isinstance(item, dict) else item
                           for item in sources]
    if not raw_sources:
        raw_sources = [str(plan_cell.get("tensor", "synthetic"))]
    shape_id = plan_cell.get("shape_id", plan_cell.get("id"))
    if not shape_id:
        dims = "x".join(str(plan_dim(plan_cell, key)) for key in ("m", "n", "k"))
        shape_id = f"{model_id}-{problem_route}-q{plan_cell['qtype']}-{dims}"
    grouped = plan_cell.get("grouped")
    if grouped is None:
        grouped_fields = {
            "experts": plan_cell.get("experts", plan_cell.get("E")),
            "active": plan_cell.get("active_experts", plan_cell.get("active")),
            "ragged": plan_cell.get("ragged"),
        }
        grouped = (grouped_fields if any(value is not None
                                         for value in grouped_fields.values())
                   else None)
    return {
        "model_id": model_id,
        "shape_id": str(shape_id),
        "source_tensors": sorted(set(map(str, raw_sources))),
        "tp_world": plan_cell.get("tp_world", plan_cell.get("tp_world_size", 1)),
        "tp_rank": plan_cell.get("tp_rank", 0),
        "tp_partition": plan_cell.get(
            "tp_partition", plan_cell.get("partition", "replicated")),
        "problem_route": problem_route,
        "group_size": plan_cell.get(
            "group_size", plan_cell.get("gs",
                registry_group_size if registry_group_size is not None else "UNKNOWN")),
        "grouped": grouped,
    }


def is_grouped(plan_cell: dict[str, Any]) -> bool:
    workload = workload_metadata(plan_cell)
    return workload["problem_route"] == "grouped"


def primary_tensor(plan_cell: dict[str, Any]) -> str:
    return workload_metadata(plan_cell)["source_tensors"][0]


def unsupported_cells(plan_cell: dict[str, Any], reason: str | None = None,
                      registry_group_size: int | None = None
                      ) -> list[dict[str, Any]]:
    qtype = int(plan_cell["qtype"])
    shape = {key: plan_dim(plan_cell, key) for key in ("m", "n", "k")}
    shape["l"] = int(plan_cell.get("l", plan_cell.get("L", 1)))
    workload = workload_metadata(plan_cell, registry_group_size)
    tensor = primary_tensor(plan_cell)
    artifact = int((plan_cell.get("canonical_scale_first_arrangement") or {})
                   .get("artifact_tile_k", 32))
    result = []
    algorithms = [(1, "bc-gemv"), *[(split, "tc-s1" if split == 1 else
                                      "tc-splitk")
                                     for split in matrix.SPLITS]]
    for split, algorithm in algorithms:
        identity = {
            "component": "fully_quantized", "tensor": tensor,
            "qtype": qtype, "shape": shape, "algorithm": algorithm,
            "S": split, "config": f"unsupported-fq-qtype-{qtype}",
            **workload,
        }
        result.append({
            "cell_id": cell_id(identity), "tensor": tensor,
            "qtype": qtype, "format": plan_cell.get("format", f"qtype-{qtype}"),
            "shape": shape, "layout": {"name": "UNSUPPORTED_FQ"},
            "FoldN": [1, 1], "ArtifactTileK": artifact,
            "algorithm": algorithm, "S": split,
            "metric_scope": FULL if algorithm in {"bc-gemv", "tc-s1"}
                            else PRODUCER,
            "config": identity["config"], "policy": "n/a", "grid": "n/a",
            "status": "UNSUPPORTED", "reason": reason or (
                "Q8_HAS_NO_SHIPPING_FULLY_QUANTIZED_READER" if qtype == 8 else
                "QTYPE_NOT_IN_FULLY_QUANTIZED_REGISTRY"),
            "route": "", "workspace_bytes": 0,
            **workload,
        })
    return result


def _require_runtime_parent(row: dict[str, str], parent: tuple[int, int, int],
                            record: str) -> None:
    qtype, artifact, bchunk = parent
    observed = (int(row["q"]), int(row["A"]))
    if observed != (qtype, artifact):
        raise ValueError(
            f"{record} record identity q/A={observed} differs from parent "
            f"q/A={(qtype, artifact)}")
    if record != "BC" and int(row["bchunk"]) != bchunk:
        raise ValueError(
            f"{record} record bchunk={row['bchunk']} differs from parent "
            f"bchunk={bchunk}")
    if record == "BC" and bchunk != 0:
        raise ValueError("BC record appeared under a bchunk=1 parent shard")


def read_runtime(raw_root: pathlib.Path,
                 expected_shapes_by_q: dict[int, set[tuple[int, int, int]]]
                 ) -> tuple[dict[tuple[Any, ...], dict],
                            dict[tuple[Any, ...], dict],
                            list[dict[str, Any]]]:
    tc: dict[tuple[Any, ...], dict] = {}
    bc: dict[tuple[Any, ...], dict] = {}
    failures: list[dict[str, Any]] = []
    for log in sorted(raw_root.glob("*/run.log")):
        parent_match = SHARD_RE.fullmatch(log.parent.name)
        if parent_match is None:
            failures.append({"log": str(log),
                             "reason": "runtime shard directory has invalid identity"})
            continue
        parent = tuple(map(int, parent_match.groups()))
        expected_shapes = expected_shapes_by_q.get(parent[0], set())
        completed_shapes: set[tuple[int, int, int]] = set()
        rc_path = log.with_name("run.rc")
        try:
            rc = int(rc_path.read_text().strip())
        except (OSError, ValueError):
            failures.append({"log": str(log), "reason": "missing/invalid run.rc"})
            continue
        text = log.read_text(errors="replace")
        if rc:
            failures.append({"log": str(log), "reason": f"runner rc={rc}"})
        for lineno, line in enumerate(text.splitlines(), 1):
            if line.startswith(TC_PREFIX):
                try:
                    row = parse_kv(line, TC_PREFIX)
                    _require_runtime_parent(row, parent, "TC")
                    shape = parse_shape(row["shape"])
                    if shape not in expected_shapes:
                        raise ValueError(
                            f"TC shape {shape} was not requested for q={parent[0]}")
                    key = (int(row["q"]), int(row["A"]), int(row["bchunk"]),
                           shape, row["symbol"], int(row["S"]))
                    if key in tc:
                        raise ValueError(f"duplicate TC key {key}")
                    tc[key] = row
                except (KeyError, TypeError, ValueError) as exc:
                    failures.append({"log": str(log), "line": lineno,
                                     "reason": str(exc)})
            elif line.startswith(BC_PREFIX):
                try:
                    row = parse_kv(line, BC_PREFIX)
                    _require_runtime_parent(row, parent, "BC")
                    shape = parse_shape(row["shape"])
                    if shape not in expected_shapes:
                        raise ValueError(
                            f"BC shape {shape} was not requested for q={parent[0]}")
                    key = (int(row["q"]), int(row["A"]), shape,
                           int(row["rpw"]))
                    if key in bc:
                        raise ValueError(f"duplicate BC key {key}")
                    bc[key] = row
                except (KeyError, TypeError, ValueError) as exc:
                    failures.append({"log": str(log), "line": lineno,
                                     "reason": str(exc)})
            elif line.startswith(SHAPE_DONE_PREFIX):
                try:
                    row = parse_kv(line, SHAPE_DONE_PREFIX)
                    _require_runtime_parent(row, parent, "SHAPE_DONE")
                    shape = parse_shape(row["shape"])
                    if shape not in expected_shapes:
                        raise ValueError(
                            f"completed shape {shape} was not requested for q={parent[0]}")
                    if shape in completed_shapes:
                        raise ValueError(f"duplicate FQ_SHAPE_DONE for {shape}")
                    if row.get("status") != "PASS":
                        raise ValueError(
                            f"FQ_SHAPE_DONE status={row.get('status','MISSING')}")
                    completed_shapes.add(shape)
                except (KeyError, TypeError, ValueError) as exc:
                    failures.append({"log": str(log), "line": lineno,
                                     "reason": str(exc)})
        if completed_shapes != expected_shapes:
            failures.append({
                "log": str(log),
                "reason": "FQ_SHAPE_DONE set differs from requested shape set",
                "missing": sorted(expected_shapes-completed_shapes),
                "extra": sorted(completed_shapes-expected_shapes),
            })
    return tc, bc, failures


def dynamic_status(row: dict[str, str], split: int) -> tuple[str, str]:
    expected_scope = ("FULL_OUTPUT" if split == 1 else
                      "PRODUCER_ONLY_REDUCER_UNTIMED_CORRECTNESS")
    if row.get("scope") != expected_scope:
        return "RUN_FAILED", (
            f"RUNTIME_SCOPE_MISMATCH_{row.get('scope','MISSING')}_EXPECTED_"
            f"{expected_scope}")
    state = row["state"]
    if state == "MEASURED":
        if int(row.get("raw_bad", "-1")) != 0:
            return "RUN_FAILED", "MEASURED_RECORD_HAS_RAW_MISMATCH"
        if split > 1 and row.get("reducer_untimed") != "1":
            return "RUN_FAILED", "SPLIT_PRODUCER_LACKS_UNTIMED_REDUCER_CLOSURE"
        return "MEASURED", ""
    inadmissible = {
        "SHIPPING_SHARED_STORAGE", "SPLIT_SHARED_STORAGE", "SPLIT_PARTITION",
        "INADMISSIBLE_PIPELINE_DEPTH", "REAL_CAN_IMPLEMENT",
        "PACKED_A_DECODE_ONLY_M_NOT_1",
    }
    if state in inadmissible:
        return "INADMISSIBLE", state
    return "RUN_FAILED", state


def checked_samples(row: dict[str, str], expected_count: int
                    ) -> tuple[list[float], float]:
    samples = parse_samples(row["samples"])
    if len(samples) != expected_count:
        raise ValueError(
            f"runtime sample denominator {len(samples)}/{expected_count}")
    computed = statistics.median(samples)
    reported = float(row["us"])
    if not math.isclose(reported, computed, rel_tol=0.0, abs_tol=1e-6):
        raise ValueError(
            f"reported median {reported} differs from samples median {computed}")
    return samples, computed


def terminal_from_base(base: dict[str, Any], plan_cell: dict[str, Any],
                       fmt: matrix.Format, tc_runtime: dict, bc_runtime: dict,
                       peak_tflops: float, hbm_gbs: float,
                       expected_samples: int,
                       missing: list[dict[str, Any]],
                       failures: list[dict[str, Any]],
                       consumed_tc: set[tuple[Any, ...]],
                       consumed_bc: set[tuple[Any, ...]]) -> dict[str, Any]:
    qtype = fmt.qtype
    shape_tuple = tuple(plan_dim(plan_cell, key) for key in ("m", "n", "k"))
    shape = {"m": shape_tuple[0], "n": shape_tuple[1], "k": shape_tuple[2], "l": 1}
    artifact = int(base["artifact_tile_k"])
    layout = layout_for(fmt, artifact)
    is_bc = base["algorithm"] == matrix.BC_ALGORITHM
    split = 1 if is_bc else int(base["split_k_slices"])
    algorithm = "bc-gemv" if is_bc else "tc-s1" if split == 1 else "tc-splitk"
    provider = base.get("a_provider", "standard-aiu")
    tensor = primary_tensor(plan_cell)
    config = (f"placed-bc-gemv-a{artifact}-rpw{base['tactic']['rows_per_warp']}"
              if is_bc else f"{tactic_name(base['tactic'])}-ap-{provider}")
    identity = {
        "component": "fully_quantized", "tensor": tensor,
        "qtype": qtype, "shape": shape, "layout": layout,
        "algorithm": algorithm, "S": split, "config": config,
        **workload_metadata(plan_cell, fmt.group_size),
    }
    cell = {
        "cell_id": cell_id(identity), "tensor": tensor,
        "qtype": qtype, "format": fmt.name, "shape": shape,
        "layout": layout, "FoldN": [layout["fold_n"]["low"], layout["fold_n"]["high"]],
        "ArtifactTileK": artifact, "algorithm": algorithm, "S": split,
        "metric_scope": FULL if split == 1 else PRODUCER,
        "config": config, "policy": "n/a", "grid": "n/a",
        "route": base.get("route") or "", "workspace_bytes": 0,
        **workload_metadata(plan_cell, fmt.group_size),
        "a_provider": provider,
        "a_provider_capacity_rows": base.get("a_provider_capacity_rows"),
    }
    if base["status"] in {"STATIC_REJECT", "UNSUPPORTED"}:
        cell.update(status="INADMISSIBLE" if base["status"] == "STATIC_REJECT"
                    else "UNSUPPORTED", reason=base["reason"])
        return cell

    runtime = None
    if is_bc:
        runtime_key = (qtype, artifact, shape_tuple,
                       int(base["tactic"]["rows_per_warp"]))
        runtime = bc_runtime.get(runtime_key)
        if runtime is not None:
            consumed_bc.add(runtime_key)
    else:
        tactic = base["tactic"]
        key = (qtype, artifact, int(tactic["bchunk"]), shape_tuple,
               runtime_symbol(qtype, artifact, tactic, provider), split)
        runtime = tc_runtime.get(key)
        if runtime is not None:
            consumed_tc.add(key)
    if runtime is None:
        cell.update(status="MISSING", reason="COMPILED_ADMISSION_RECORD_MISSING")
        missing.append({"cell_id": cell["cell_id"], "reason": cell["reason"]})
        return cell

    if not is_bc:
        runtime_capacity = int(runtime.get("provider_capacity_rows", "-1"))
        expected_capacity = int(base.get("a_provider_capacity_rows") or 0)
        if runtime_capacity != expected_capacity:
            cell.update(status="RUN_FAILED",
                        reason="A_PROVIDER_CAPACITY_RUNTIME_TYPE_MISMATCH")
            failures.append({"cell_id": cell["cell_id"], "reason": cell["reason"]})
            return cell

    if is_bc:
        state = runtime["state"]
        if runtime.get("scope") != "FULL_OUTPUT":
            status, reason = "RUN_FAILED", "RUNTIME_SCOPE_MISMATCH"
        elif state == "MEASURED" and int(runtime.get("raw_bad", "-1")) == 0:
            status, reason = "MEASURED", ""
        elif state.startswith("UNSUPPORTED"):
            status, reason = "INADMISSIBLE", state
        else:
            status, reason = "RUN_FAILED", state
    else:
        status, reason = dynamic_status(runtime, split)
    cell.update(status=status, reason=reason)
    if status == "MEASURED":
        try:
            samples, median = checked_samples(runtime, expected_samples)
        except (KeyError, TypeError, ValueError) as error:
            cell.update(status="RUN_FAILED",
                        reason=f"RUNTIME_SAMPLE_CONTRACT:{error}")
            failures.append({"cell_id": cell["cell_id"],
                             "reason": cell["reason"]})
            return cell
        partial = int(runtime.get("partial_bytes", "0"))
        mfu, mbu, kind = metric(shape_tuple, qtype, split, algorithm,
                                median, partial, peak_tflops, hbm_gbs)
        cell.update(raw_samples_us=samples, median_us=median,
                    MFU_pct=mfu, distinct_MBU_model_pct=mbu,
                    mbu_kind=kind, correctness="RAW-FP16/PASS",
                    workspace_bytes=partial)
    elif status == "RUN_FAILED":
        failures.append({"cell_id": cell["cell_id"], "reason": reason})
    return cell


def expected_runtime_shards(plan_cells: list[dict[str, Any]],
                            base_by_q: dict[int, list[dict[str, Any]]]
                            ) -> set[str]:
    active_qtypes = {
        int(cell["qtype"]) for cell in plan_cells
        if cell.get("inventory_status") == "SUPPORTED" and
           cell.get("problem_route") == "dense" and
           int(cell["qtype"]) in VALID_QTYPES
    }
    expected: set[str] = set()
    for qtype in active_qtypes:
        for artifact in matrix.ARTIFACT_TILE_K:
            for bchunk in matrix.BCHUNK_REQUESTS:
                need_tc = any(
                    int(base.get("artifact_tile_k") or -1) == artifact and
                    base.get("algorithm") != matrix.BC_ALGORITHM and
                    int(base.get("bchunk_requested") or 0) == bchunk and
                    base.get("status") == "FQ_COMPILED_TYPE_ADMISSION_REQUIRED"
                    for base in base_by_q[qtype])
                need_bc = bchunk == 0 and any(
                    int(base.get("artifact_tile_k") or -1) == artifact and
                    base.get("algorithm") == matrix.BC_ALGORITHM and
                    base.get("status") == "BC_COMPILED_TYPE_ADMISSION_REQUIRED"
                    for base in base_by_q[qtype])
                if need_tc or need_bc:
                    expected.add(f"q{qtype}-a{artifact}-bc{bchunk}")
    return expected


def expected_generated_shards(plan_cells: list[dict[str, Any]]) -> set[str]:
    active_qtypes = {
        int(cell["qtype"]) for cell in plan_cells
        if cell.get("inventory_status") == "SUPPORTED" and
           cell.get("problem_route") == "dense" and
           int(cell["qtype"]) in VALID_QTYPES
    }
    return {
        f"q{qtype}-a{artifact}-bc{bchunk}"
        for qtype in active_qtypes
        for artifact in matrix.ARTIFACT_TILE_K
        for bchunk in matrix.BCHUNK_REQUESTS
    }


def analyze(plan_path: pathlib.Path, raw_root: pathlib.Path,
            output: pathlib.Path, identity_path: pathlib.Path,
            source_hashes_path: pathlib.Path, binary_hashes_path: pathlib.Path,
            run_contract_path: pathlib.Path,
            attempt_id: str,
            peak_tflops: float, hbm_gbs: float) -> int:
    if not re.fullmatch(r"[A-Za-z0-9._:-]+", attempt_id):
        raise ValueError("orchestration attempt ID is empty or malformed")
    plan = load_plan(plan_path)
    run_contract = json.loads(run_contract_path.read_text())
    if run_contract.get("schema") != (
            "quactlize.fully_quantized_internal_sweep.run_contract.v1"):
        raise ValueError("run-contract schema mismatch")
    expected_samples = int(run_contract.get("iterations", 0))
    if expected_samples <= 0:
        raise ValueError("run-contract iterations must be positive")
    if (float(run_contract.get("peak_tflops", 0)) != peak_tflops or
            float(run_contract.get("hbm_gbs", 0)) != hbm_gbs):
        raise ValueError("analysis metric denominators differ from run contract")
    if run_contract.get("plan_sha256") != sha256(plan_path):
        raise ValueError("run contract does not bind the analyzed plan")
    plan_cells = plan["cells"]
    formats = {fmt.qtype: fmt for fmt in matrix.parse_formats()}
    base_by_q: dict[int, list[dict[str, Any]]] = collections.defaultdict(list)
    for base in matrix.expanded_cells(list(formats.values())):
        base_by_q[int(base["qtype"])].append(base)
    expected_shapes_by_q: dict[int, set[tuple[int, int, int]]] = (
        collections.defaultdict(set))
    for plan_cell in plan_cells:
        qtype = int(plan_cell["qtype"])
        if (plan_cell.get("inventory_status") == "SUPPORTED" and
                plan_cell.get("problem_route") == "dense" and
                qtype in VALID_QTYPES):
            expected_shapes_by_q[qtype].add(tuple(
                plan_dim(plan_cell, key) for key in ("m", "n", "k")))
    tc_runtime, bc_runtime, failures = read_runtime(
        raw_root, expected_shapes_by_q)
    consumed_tc: set[tuple[Any, ...]] = set()
    consumed_bc: set[tuple[Any, ...]] = set()
    missing: list[dict[str, Any]] = []
    cells: list[dict[str, Any]] = []
    expected = 0
    for plan_cell in plan_cells:
        qtype = int(plan_cell["qtype"])
        if plan_cell.get("inventory_status") != "SUPPORTED":
            unsupported = unsupported_cells(
                plan_cell,
                "INVENTORY_" + str(plan_cell.get(
                    "inventory_reason", "UNSUPPORTED")),
                formats[qtype].group_size if qtype in formats else None)
            cells.extend(unsupported); expected += len(unsupported)
            continue
        if is_grouped(plan_cell):
            unsupported = unsupported_cells(
                plan_cell, "GROUPED_FULLY_QUANTIZED_SWEEP_NOT_REGISTERED",
                formats[qtype].group_size if qtype in formats else None)
            cells.extend(unsupported); expected += len(unsupported)
            continue
        if qtype not in VALID_QTYPES:
            unsupported = unsupported_cells(
                plan_cell, registry_group_size=(
                    formats[qtype].group_size if qtype in formats else None))
            cells.extend(unsupported); expected += len(unsupported)
            continue
        bases = base_by_q[qtype]
        expected += len(bases)
        for base in bases:
            cells.append(terminal_from_base(
                base, plan_cell, formats[qtype], tc_runtime, bc_runtime,
                peak_tflops, hbm_gbs, expected_samples, missing, failures,
                consumed_tc, consumed_bc))
    extra_tc = sorted(set(tc_runtime) - consumed_tc, key=repr)
    extra_bc = sorted(set(bc_runtime) - consumed_bc, key=repr)
    if extra_tc or extra_bc:
        failures.append({
            "reason": "unconsumed runtime records",
            "tc_examples": list(map(repr, extra_tc[:8])),
            "bc_examples": list(map(repr, extra_bc[:8])),
        })
    ids = [cell["cell_id"] for cell in cells]
    duplicates = [key for key, count in collections.Counter(ids).items() if count != 1]
    if duplicates:
        failures.append({"reason": "duplicate cell IDs", "examples": duplicates[:8]})
    if len(cells) != expected:
        failures.append({"reason": f"denominator mismatch {len(cells)}/{expected}"})
    nonterminal = [cell for cell in cells if cell["status"] not in
                   {"MEASURED", "INADMISSIBLE", "UNSUPPORTED", "BUILD_REJECT"}]
    status = "COMPLETE" if not missing and not failures and not nonterminal else "INCOMPLETE"
    source_document = json.loads(source_hashes_path.read_text())
    if not isinstance(source_document, dict):
        raise ValueError("source-hashes document is not an object")
    root_sha = str(source_document.get("root_sha", ""))
    actlize_sha = str(source_document.get("actlize_sha", ""))
    if not re.fullmatch(r"[0-9a-f]{40}", root_sha) or not re.fullmatch(
            r"[0-9a-f]{40}", actlize_sha):
        raise ValueError("source-hashes root/actlize SHA is invalid")
    source_hashes = source_document.get("source_hashes")
    if not isinstance(source_hashes, dict) or not source_hashes:
        raise ValueError("source-hashes document lacks source_hashes")
    if set(source_hashes) != EXPECTED_SOURCE_HASHES:
        raise ValueError(
            "source-hashes set differs from the component source authority: "
            f"missing={sorted(EXPECTED_SOURCE_HASHES-set(source_hashes))} "
            f"extra={sorted(set(source_hashes)-EXPECTED_SOURCE_HASHES)}")
    for name, digest in source_hashes.items():
        require_sha256(digest, f"source_hashes.{name}")
    generated_hashes = source_document.get("generated_shards")
    if not isinstance(generated_hashes, dict):
        raise ValueError("source-hashes document lacks generated_shards")
    expected_generated = expected_generated_shards(plan_cells)
    if set(generated_hashes) != expected_generated:
        raise ValueError(
            "generated source shard set differs from exact plan graph: "
            f"missing={sorted(expected_generated-set(generated_hashes))} "
            f"extra={sorted(set(generated_hashes)-expected_generated)}")
    for name, digest in generated_hashes.items():
        require_sha256(digest, f"generated_shards.{name}")
    published_source_hashes = dict(source_hashes)
    published_source_hashes.update({
        f"generated/{name}": digest
        for name, digest in generated_hashes.items()
    })
    binary_hashes = json.loads(binary_hashes_path.read_text())
    if not isinstance(binary_hashes, dict) or not binary_hashes:
        raise ValueError("binary-hashes document is empty")
    for name, digest in binary_hashes.items():
        require_sha256(digest, f"binary_hashes.{name}")
    expected_shards = expected_runtime_shards(plan_cells, base_by_q)
    if set(binary_hashes) != expected_shards:
        raise ValueError(
            "binary shard set differs from exact runtime graph: "
            f"missing={sorted(expected_shards-set(binary_hashes))} "
            f"extra={sorted(set(binary_hashes)-expected_shards)}")
    runtime_hashes = runtime_authority(
        raw_root, expected_shards, run_contract_path,
        generated_hashes, binary_hashes)
    identity = json.loads(identity_path.read_text())
    if run_contract.get("identity_sha256") != sha256(identity_path):
        raise ValueError("run contract does not bind the analyzed device identity")
    plan_provenance = plan["provenance"]
    status_counts = collections.Counter(cell["status"] for cell in cells)
    summary = {
        "schema": SCHEMA, "component": "fully_quantized", "status": status,
        "expected_cells": expected, "status_counts": dict(status_counts),
        "missing": missing, "failures": failures,
        "measurement_contract": {
            "full_output": "placed BC GEMV and direct tensor-core S1 only",
            "producer_only": "S2/S4/S8 excludes reducer timing but requires untimed real reducer raw-fp16 closure",
            "cross_scope_ranking": "forbidden",
            "peak_tflops": peak_tflops,
            "hbm_gbs": hbm_gbs,
        },
        "provenance": {
            "root_sha": root_sha,
            "actlize_sha": actlize_sha,
            # Generated units are part of the same flat source-hash authority
            # so merge_internal_full_sweep preserves them without a second
            # provenance schema.  The named map remains for direct inspection.
            "device": identity, "source_hashes": published_source_hashes,
            "generated_source_hashes": generated_hashes,
            "binary_hashes": binary_hashes,
            "runtime_hashes": runtime_hashes,
            "run_contract": run_contract,
            "orchestration_attempt_id": attempt_id,
            "shape_manifest_sha256": require_sha256(
                plan_provenance.get("shape_manifest_sha256"),
                "plan.provenance.shape_manifest_sha256"),
            "gguf_hashes": plan_provenance.get("gguf_hashes"),
            "gguf_set_sha256": require_sha256(
                plan_provenance.get("gguf_set_sha256"),
                "plan.provenance.gguf_set_sha256"),
            "shape_directory": plan_provenance.get("shape_directory"),
        },
        "cells": cells,
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    encoded = json.dumps(summary, indent=2, sort_keys=True) + "\n"
    current = output.with_name(output.name + f".current.{os.getpid()}")
    with current.open("w", encoding="utf-8") as stream:
        stream.write(encoded)
        stream.flush()
        os.fsync(stream.fileno())
    os.replace(current, output)
    print(f"[fq-internal] status={status} denominator={expected} "
          f"measured={status_counts.get('MEASURED',0)} "
          f"inadmissible={status_counts.get('INADMISSIBLE',0)} "
          f"unsupported={status_counts.get('UNSUPPORTED',0)} "
          f"missing={len(missing)} failures={len(failures)} summary={output}")
    return 0 if status == "COMPLETE" else 1


def self_test() -> int:
    # Bind this producer to the shared flat schema rather than merely proving
    # that its own JSON is internally self-consistent.
    import merge_internal_full_sweep as merger

    line = ("FQ_TC_CELL q=12 A=64 bchunk=0 shape=1x4096x4096 symbol=x "
            "tm=8 tn=128 tk=256 wm=8 wn=16 stages=3 provider=packed-row "
            "provider_capacity_rows=1 S=4 "
            "scope=PRODUCER_ONLY_REDUCER_UNTIMED_CORRECTNESS state=MEASURED "
            "us=9.5 raw_bad=0 reducer_untimed=1 shipping_smem=1 split_smem=2 "
            "partial_bytes=65536 samples=[9.4,9.5,9.6]")
    row = parse_kv(line, TC_PREFIX)
    assert parse_shape(row["shape"]) == (1,4096,4096)
    assert parse_samples(row["samples"]) == [9.4,9.5,9.6]
    assert checked_samples(row, 3) == ([9.4, 9.5, 9.6], 9.5)
    try:
        checked_samples(row, 4)
    except ValueError as error:
        assert "denominator" in str(error)
    else:
        raise AssertionError("short runtime sample vector stayed green")
    wrong_median = dict(row, us="9.7")
    try:
        checked_samples(wrong_median, 3)
    except ValueError as error:
        assert "median" in str(error)
    else:
        raise AssertionError("reported median drift stayed green")
    assert dynamic_status(row, 4) == ("MEASURED", "")
    _require_runtime_parent(row, (12, 64, 0), "TC")
    cross_shard = dict(row, A="128")
    try:
        _require_runtime_parent(cross_shard, (12, 64, 0), "TC")
    except ValueError as error:
        assert "differs from parent" in str(error)
    else:
        raise AssertionError("cross-shard runtime record stayed green")
    planted = dict(row, reducer_untimed="0")
    assert dynamic_status(planted, 4)[0] == "RUN_FAILED"
    wrong_scope = dict(row, scope="FULL_OUTPUT")
    assert dynamic_status(wrong_scope, 4)[0] == "RUN_FAILED"
    packed_wrong_band = dict(row, state="PACKED_A_DECODE_ONLY_M_NOT_1")
    assert dynamic_status(packed_wrong_band, 4) == (
        "INADMISSIBLE", "PACKED_A_DECODE_ONLY_M_NOT_1")
    gguf_hashes = {"future-model": "a" * 64}
    resolved_set_sha = "c" * 64
    source_a = "d" * 64
    source_b = "e" * 64
    inventory = {
        "schema": INVENTORY_SCHEMA,
        "status": "COMPLETE",
        "resolved_models_schema": RESOLVED_MODELS_SCHEMA,
        "resolved_set_sha256": resolved_set_sha,
        "provenance": {
            "gguf_hashes": gguf_hashes,
            "gguf_set_sha256": hashlib.sha256(
                canonical(gguf_hashes).encode("utf-8")).hexdigest(),
            "shape_directory": {
                "dense": "m{m}_n{n}_k{k}_g{group_size}",
                "grouped": (
                    "m{m}_n{n}_k{k}_g{group_size}_e{experts}_a{active}_"
                    "{ragged_profile}"),
            },
        },
        "shape_directory_contract": {
            "dense": "m{m}_n{n}_k{k}_g{group_size}",
            "grouped": (
                "m{m}_n{n}_k{k}_g{group_size}_e{experts}_a{active}_"
                "{ragged_profile}"),
        },
        "workload_axes": {"dense": {"decode_m": [1], "prefill_m": [4]},
                          "grouped": {"decode_tokens": [1],
                                      "prefill_tokens": [4]}},
        "format_registry_sha256": "f" * 64,
        "model_count": 1,
        "models": [{"model_id": "future-model",
                    "fileset_sha256": gguf_hashes["future-model"],
                    "tp_world_size": 2}],
        "qtype_counts": {
            "0": {"traits": {"quant_group_size": 0,
                                "quant_group_size_known": True}},
            "20": {"traits": {"quant_group_size": 32,
                                "quant_group_size_known": True}},
        },
        "sweep_shapes": [{
            "model_id": "future-model", "dedup_key": key,
            "sources": [["future", "attn_q", source]],
            "source_tensors": ["future"],
            "tp_world": 2, "tp_rank": 0, "tp_partition": "n",
            "problem_kind": "dense", "qtype": 20,
            "M": m, "N": 1, "K": 256, "L": 1,
            "experts": None, "top_k": None, "active": None,
            "ragged": None, "shape_directory": f"m{m}_n1_k256_g32",
            "status": "UNSUPPORTED", "reason": "IQ4_NL_NOT_REGISTERED",
        } for key, source, m in (("1" * 64, source_a, 1),
                                  ("2" * 64, source_b, 4))],
    }
    inventory["deduplicated_shape_count"] = len(inventory["sweep_shapes"])
    inventory["sweep_shapes"].append({
        **inventory["sweep_shapes"][0],
        "dedup_key": "3" * 64,
        "sources": [["future-f32", "attn_q", "4" * 64]],
        "source_tensors": ["future-f32"],
        "qtype": 0,
        "M": 8,
        "shape_directory": "m8_n1_k256_g0",
        "status": "UNSUPPORTED",
        "reason": "QTYPE_NOT_REGISTERED",
    })
    inventory["deduplicated_shape_count"] = len(inventory["sweep_shapes"])
    materialized = _materialize_spec(
        inventory, pathlib.Path("/workspace/synthetic-inventory-v2.json"),
        "b" * 64)
    assert materialized["schema"] == PLAN_SCHEMA
    assert [cell["m"] for cell in materialized["cells"]] == [1, 4, 8]
    assert [cell["group_size"] for cell in materialized["cells"]] == [32, 32, 0]
    assert all(cell["tp_rank"] == 0 for cell in materialized["cells"])
    assert expected_generated_shards(materialized["cells"]) == set()
    orphan_model = json.loads(json.dumps(inventory))
    orphan_model["models"].append({
        "model_id": "orphan-model", "fileset_sha256": "9" * 64,
        "tp_world_size": 1,
    })
    orphan_model["model_count"] = 2
    orphan_model["provenance"]["gguf_hashes"]["orphan-model"] = "9" * 64
    orphan_model["provenance"]["gguf_set_sha256"] = hashlib.sha256(
        canonical(orphan_model["provenance"]["gguf_hashes"]).encode("utf-8")
    ).hexdigest()
    try:
        _materialize_spec(
            orphan_model, pathlib.Path("/workspace/orphan-model.json"),
            "b" * 64)
    except ValueError as error:
        assert "model set differs" in str(error)
    else:
        raise AssertionError("declared model without a sweep shape stayed green")
    planted_v1 = dict(inventory, schema="quactlize.gguf_internal_shape_inventory.v1")
    try:
        _materialize_spec(planted_v1, pathlib.Path("/workspace/v1.json"), "b" * 64)
    except ValueError as error:
        assert "expected" in str(error) and "v1" in str(error)
    else:
        raise AssertionError("inventory v1 was silently adapted")
    missing_identity = json.loads(json.dumps(inventory))
    del missing_identity["sweep_shapes"][0]["tp_partition"]
    try:
        _materialize_spec(
            missing_identity, pathlib.Path("/workspace/missing.json"), "b" * 64)
    except ValueError as error:
        assert "tp_partition" in str(error)
    else:
        raise AssertionError("missing TP identity was guessed")
    resolved = {
        "schema": RESOLVED_MODELS_SCHEMA,
        "resolved_set_sha256": resolved_set_sha,
        "shape_directory": inventory["shape_directory_contract"],
        "workload_axes": inventory["workload_axes"],
        "models": [{
            "model_id": "future-model", "fileset_sha256": "a" * 64,
            "tp_world_size": 2,
        }],
    }
    # Validate the same logic without writing a synthetic file by spelling out
    # its two decisive conditions here; the CLI path additionally parses and
    # validates the versioned JSON before a real build.
    _validate_resolved_document(materialized, resolved, "synthetic-resolved")
    wrong_rank = json.loads(json.dumps(materialized))
    wrong_rank["cells"][0]["tp_rank"] = 1
    try:
        _validate_resolved_document(wrong_rank, resolved, "wrong-rank")
    except ValueError as error:
        assert "rank 0" in str(error)
    else:
        raise AssertionError("nonrepresentative TP rank stayed green")
    future = unsupported_cells({
        "qtype": 20, "m": 1, "n": 1, "k": 256,
        "tensor": "future", "format": "IQ4_X", "model_id": "future-model",
        "tp_world": 2, "tp_rank": 0, "partition": "n",
    })
    assert len(future) == 5
    assert {cell["algorithm"] for cell in future} == {
        "bc-gemv", "tc-s1", "tc-splitk"}
    assert all(cell["model_id"] == "future-model" and
               cell["tp_world"] == 2 and
               cell["tp_rank"] == 0 and
               cell["tp_partition"] == "n" for cell in future)
    grouped = unsupported_cells({
        "qtype": 12, "M": 8, "N": 4096, "K": 4096,
        "tensor": "experts", "format": "Q4_K", "model_id": "moe",
        "route": "grouped_fully_quantized", "route_class": "grouped",
        "E": 256, "active": 8, "ragged": "one-heavy",
    }, "GROUPED_FULLY_QUANTIZED_SWEEP_NOT_REGISTERED")
    assert len(grouped) == 5
    assert all(cell["problem_route"] == "grouped" and
        cell["grouped"] == {
            "experts": 256, "active": 8, "ragged": "one-heavy"}
        for cell in grouped)
    normalized = [
        merger.normalize_cell("fully_quantized", SCHEMA, cell, ordinal)
        for ordinal, cell in enumerate([*future, *grouped])
    ]
    assert len(normalized) == 10
    assert {cell["problem_route"] for cell in normalized} == {"dense", "grouped"}
    # Denominator negative: deleting one runtime record is represented as a
    # named MISSING terminal and therefore cannot produce COMPLETE.
    assert "MISSING" not in {"MEASURED", "INADMISSIBLE", "UNSUPPORTED", "BUILD_REJECT"}
    # Exercise the durable run transaction itself, not just its source-side
    # checker.  Deleting run.rc from an otherwise intact shard must be red.
    authority_root = (pathlib.Path("/workspace") /
                      f"quactlize-fq-runtime-authority-selftest-{os.getpid()}")
    if authority_root.exists() or authority_root.parent.resolve() != pathlib.Path(
            "/workspace").resolve():
        raise AssertionError(f"unsafe/existing self-test path {authority_root}")
    shard = "q12-a64-bc0"
    shard_dir = authority_root / shard
    shard_dir.mkdir(parents=True)
    try:
        contract = authority_root / "run-contract.json"
        contract.write_text("{}\n")
        log = shard_dir / "run.log"
        rc_path = shard_dir / "run.rc"
        commit_path = shard_dir / "run.commit.json"
        log.write_text("FQ_SHAPE_DONE shape=1x1x1\n")
        rc_path.write_text("0\n")
        generated = {shard: "a" * 64}
        binaries = {shard: "b" * 64}
        commit = {
            "schema": "quactlize.fully_quantized_internal_sweep.run_commit.v1",
            "rc": 0,
            "run_log_sha256": sha256(log),
            "run_rc_sha256": sha256(rc_path),
            "run_contract_sha256": sha256(contract),
            "generated_source_sha256": generated[shard],
            "binary_sha256": binaries[shard],
        }
        commit_path.write_text(json.dumps(commit, sort_keys=True) + "\n")
        evidence = runtime_authority(
            authority_root, {shard}, contract, generated, binaries)
        assert evidence[shard]["rc"] == 0
        rc_path.unlink()
        try:
            runtime_authority(authority_root, {shard}, contract,
                              generated, binaries)
        except ValueError as error:
            assert "lacks log/rc/commit" in str(error)
        else:
            raise AssertionError("deleted run.rc stayed green")
    finally:
        shutil.rmtree(authority_root)
    print("[fq-internal:self-test] PASS parser, qtype0-g0 terminal UNSUPPORTED, "
          "reducer-closure/scope RED, "
          "packed-A M>1 INADMISSIBLE, future/grouped 5-algorithm "
          "UNSUPPORTED_FQ with model/TP/ragged identity, shared-merger schema "
          "bridge, exact inventory-v2 field mapping, inventory-v1/missing-TP "
          "and nonrepresentative-rank RED, orphan-model/cross-shard RED, "
          "missing-cell fail-close, and committed run-sidecar deletion RED")
    return 0


def list_plan(plan_path: pathlib.Path) -> int:
    plan = load_plan(plan_path)
    for ordinal, cell in enumerate(plan["cells"]):
        print("\t".join(str(value) for value in (
            ordinal, cell["shape_id"], cell["qtype"], plan_dim(cell, "m"),
            plan_dim(cell, "n"), plan_dim(cell, "k"),
            cell["model_id"], cell["problem_route"],
            cell.get("inventory_status", "UNSUPPORTED"))))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--materialize-plan", type=pathlib.Path,
                        help=f"strict {INVENTORY_SCHEMA} input")
    parser.add_argument("--materialized-output", type=pathlib.Path)
    parser.add_argument("--list-plan", type=pathlib.Path)
    parser.add_argument("--validate-plan", type=pathlib.Path)
    parser.add_argument("--gguf-set", type=pathlib.Path)
    parser.add_argument("--plan", type=pathlib.Path)
    parser.add_argument("--raw-root", type=pathlib.Path)
    parser.add_argument("--output", type=pathlib.Path)
    parser.add_argument("--identity", type=pathlib.Path)
    parser.add_argument("--source-hashes", type=pathlib.Path)
    parser.add_argument("--binary-hashes", type=pathlib.Path)
    parser.add_argument("--run-contract", type=pathlib.Path)
    parser.add_argument("--attempt-id")
    parser.add_argument("--peak-tflops", type=float, default=500.0)
    parser.add_argument("--hbm-gbs", type=float, default=2766.0)
    args = parser.parse_args()
    try:
        if args.self_test:
            return self_test()
        if args.materialize_plan:
            if args.materialized_output is None:
                parser.error("--materialize-plan requires --materialized-output")
            plan = materialize_plan(args.materialize_plan, args.materialized_output)
            print(f"[fq-internal-plan] PASS shapes={len(plan['cells'])} "
                  f"output={args.materialized_output.resolve()}")
            return 0
        if args.list_plan:
            return list_plan(args.list_plan)
        if args.validate_plan:
            if args.gguf_set is None:
                parser.error("--validate-plan requires --gguf-set")
            plan = load_plan(args.validate_plan)
            validate_resolved_models(plan, args.gguf_set)
            print(f"[fq-internal-plan] PASS resolved-set models="
                  f"{len({cell['model_id'] for cell in plan['cells']})} "
                  f"shapes={len(plan['cells'])}")
            return 0
        required = (args.plan, args.raw_root, args.output, args.identity,
                    args.source_hashes, args.binary_hashes, args.run_contract)
        if any(value is None for value in required) or not args.attempt_id:
            parser.error("analysis requires plan/raw-root/output/identity/source-hashes/"
                         "binary-hashes/run-contract")
        return analyze(args.plan, args.raw_root, args.output, args.identity,
                       args.source_hashes, args.binary_hashes,
                       args.run_contract, args.attempt_id,
                       args.peak_tflops, args.hbm_gbs)
    except (AssertionError, KeyError, OSError, RuntimeError, TypeError,
            ValueError, json.JSONDecodeError) as exc:
        print(f"[fq-internal] FAIL: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
