// Emit the dense FullyQuantized fixed-Split-K candidate superset.
//
// The generic tactic emitter applies common_topology_exclusion(), whose
// shared-memory term models fp16 ScaleFirst metadata at the minimum runtime
// group size.  Packed GGUF metadata has a different compiled shared footprint,
// so that table is not an authority for FullyQuantized kernels.  This emitter
// shares the raw axes and common_static_sweep_exclusion() with production, but
// deliberately defers stage/shared admission to the real FQ Shipping and
// Split kernel types generated by the benchmark.

#include <cstdio>
#include <cstdlib>
#include <cstring>

#include "ppu_format_config.hpp"
#include "ppu_tactic_space.hpp"

namespace {

using namespace ppu_tactics;

FormatSpec const* format_for_qtype(int qtype) {
  char const* name = nullptr;
  switch (qtype) {
    case 10: name = "i2"; break;
    case 11: name = "Q3_K"; break;
    case 12: name = "i4"; break;
    case 13: name = "Q5_K"; break;
    case 14: name = "Q6_K"; break;
    default: return nullptr;
  }
  for (auto const& spec : kFormats)
    if (std::strcmp(spec.name, name) == 0) return &spec;
  return nullptr;
}

char const* exclusion_name(Exclusion exclusion) {
  switch (exclusion) {
    case Exclusion::None: return "NONE";
    case Exclusion::AtomAlignment: return "ATOM_ALIGNMENT";
    case Exclusion::WarpDoesNotDivideTile: return "WARP_DOES_NOT_DIVIDE_TILE";
    case Exclusion::TooManyWarps: return "TOO_MANY_WARPS";
    case Exclusion::AccumulatorRegisters: return "ACCUMULATOR_REGISTERS";
    case Exclusion::ArtifactTileKDoesNotTileTacticK:
      return "ARTIFACT_TILEK_DOES_NOT_TILE_TACTIC_K";
    case Exclusion::ArtifactLowRun: return "ARTIFACT_LOW_RUN";
    case Exclusion::ArtifactHighRun: return "ARTIFACT_HIGH_RUN";
    case Exclusion::LowFoldDoesNotDivideTileN:
      return "LOW_FOLD_DOES_NOT_DIVIDE_TILE_N";
    case Exclusion::HighFoldDoesNotDivideTileN:
      return "HIGH_FOLD_DOES_NOT_DIVIDE_TILE_N";
    case Exclusion::LowDelivery: return "LOW_DELIVERY";
    case Exclusion::HighDelivery: return "HIGH_DELIVERY";
    case Exclusion::MinimumStageSmem: return "MINIMUM_STAGE_SMEM";
    case Exclusion::EpilogueSharedStorage:
      return "EPILOGUE_SHARED_STORAGE";
    case Exclusion::ProducerWarpN: return "PRODUCER_WARP_N";
    case Exclusion::ProducerMap: return "PRODUCER_MAP";
    case Exclusion::ProducerConsumerLayout:
      return "PRODUCER_CONSUMER_LAYOUT";
    case Exclusion::BChunkUnsupportedBits: return "BCHUNK_UNSUPPORTED_BITS";
  }
  return "UNKNOWN";
}

}  // namespace

int main(int argc, char** argv) {
  if (argc < 4) {
    std::fprintf(stderr,
                 "usage: emit_fully_quantized_splitk_superset "
                 "<qtype:10..14> <artifact-tk> <tactic-tk|0=all> [stage ...]\n");
    return 2;
  }
  int const qtype = std::atoi(argv[1]);
  int const artifact_tk = std::atoi(argv[2]);
  int const requested_tactic_tk = std::atoi(argv[3]);
  FormatSpec const* spec = format_for_qtype(qtype);
  if (!spec || artifact_tk <= 0 || requested_tactic_tk < 0) {
    std::fprintf(stderr, "invalid qtype/artifact/tactic tuple\n");
    return 2;
  }
  int stages[32];
  int stage_count = 0;
  for (int i = 4; i < argc; ++i) stages[stage_count++] = std::atoi(argv[i]);
  if (stage_count == 0) {
    stages[0] = 2; stages[1] = 3; stages[2] = 4;
    stage_count = 3;
  }

  int raw = 0, eligible = 0, rejected = 0;
  for (int tactic_tk : kTileK) {
    if (requested_tactic_tk && tactic_tk != requested_tactic_tk) continue;
    for (int tm : kTileM)
      for (int tn : kTileN)
        for (int wm : kWarpM)
          for (int wn : kWarpN)
            for (int bchunk : kBChunkModes)
              for (int si = 0; si < stage_count; ++si) {
              int const stage = stages[si];
              Candidate const candidate{
                  *spec, tm, tn, tactic_tk, wm, wn, artifact_tk, bchunk};
              Exclusion const exclusion = common_static_sweep_exclusion(candidate);
              ++raw;
              if (exclusion == Exclusion::None) ++eligible;
              else ++rejected;
              std::printf(
                  "FQ_SUPERSET_ROW q=%d A=%d tm=%d tn=%d tk=%d wm=%d "
                  "wn=%d stages=%d bchunk=%d status=%s reason=%s\n",
                  qtype, artifact_tk, tm, tn, tactic_tk, wm, wn, stage,
                  bchunk,
                  exclusion == Exclusion::None ? "TYPE_ADMISSION_REQUIRED"
                                                : "STATIC_REJECT",
                  exclusion == Exclusion::None ? "FQ_SHARED_FOOTPRINT_DEFERRED"
                                                : exclusion_name(exclusion));
              }
  }
  std::printf("FQ_SUPERSET_SUMMARY q=%d A=%d raw=%d eligible=%d rejected=%d "
              "stage_count=%d tactic_tk=%s "
              "admission=REAL_FQ_COMPILED_TYPE_REQUIRED\n",
              qtype, artifact_tk, raw, eligible, rejected, stage_count,
              requested_tactic_tk ? argv[3] : "all-shared-kTileK");
  return raw == eligible + rejected ? 0 : 1;
}
