#!/usr/bin/env python3
"""Fit exact Q8 replacements from reviewed full-call measurements."""
import hashlib
import json
import math
from pathlib import Path
import re
import statistics

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / 'docs/measurements/local_closure_replay_ppu_20260916.json'
MATCHED = ROOT / 'policies/kpack_smallm_matched_v1.json'
OUTPUT = ROOT / 'policies/kpack_q8_vector_v1.json'
MODEL = ROOT / 'docs/measurements/model_decode_promotions_20260916.json'
READERS = ROOT / 'docs/measurements/model_gemv_20260917.json'


def recipe(name):
    match = re.fullmatch(r'reuse-v([01])-c([48])-w([248])-p([248])-s([1248])', name)
    if not match:
        raise ValueError('invalid Q8 control recipe')
    values = list(map(int, match.groups()))
    if values[1] * values[3] > 32:
        raise ValueError('invalid Q8 output tile')
    return values


def fit(evidence, matched):
    q8 = evidence['q8']
    if q8['numeric'] != 'PASS' or q8['contexts'] != 12480 or len(q8['performance']) != 50:
        raise ValueError('incomplete Q8 evidence')
    exact = {tuple(r['key']): r for r in matched['exact']}
    rows, retained, seen = [], [], set()
    for r in q8['performance']:
        p = r['point']; ch = p['channels']
        key = [8, 2 if ch else 0, p['n'], p['k'], 256 if ch else 1,
               8 if ch else 1, ch or 1, p['tokens'], p['compute']]
        if tuple(key) in seen:
            raise ValueError('duplicate Q8 evidence')
        seen.add(tuple(key))
        old, new = (r['best'][str(a)] for a in (0, 1))
        if not all(math.isfinite(x['median_us']) and x['median_us'] > 0 and
                   len(x['round_medians']) == 6 for x in (old, new)):
            raise ValueError('invalid Q8 timing')
        delta = 100 * (new['median_us'] / old['median_us'] - 1)
        if abs(delta - r['delta_pct']) > 1e-8:
            raise ValueError('Q8 timing verdict differs')
        baseline, candidate = recipe(old['config']), recipe(new['config'])
        incumbent = exact.get(tuple(key))
        if ch:
            # This reader campaign used 16 resident experts. Do not call
            # its indexed timings an exact 256-expert model comparison.
            reason = 'KEEP_INDEXED_E16_NOT_MODEL_E256'
        elif delta >= 0:
            reason = 'READER_REGRESSION'
        elif not incumbent:
            reason = 'NO_EXACT_INCUMBENT'
        elif incumbent['config']['kind'] != 'simt':
            reason = 'KEEP_TC_NO_MATCHED_VECTOR_COMPARISON'
        elif [incumbent['config'][k] for k in ('variant','columns','warps','values','split')] != baseline:
            reason = 'KEEP_DIFFERENT_SIMT_RECIPE'
        else:
            candidate[0] += 4
            rows.append(dict(key=key, baseline=baseline, candidate=candidate,
                             old_us=old['median_us'], new_us=new['median_us'],
                             result_sha256=r['result_sha256']))
            continue
        retained.append(dict(key=key, reason=reason))
    return dict(schema='quactlize.q8-vector-policy.v1', rows=rows, retained=retained,
                archive_sha256=evidence['archive_sha256'],
                scope='EXACT_F32_IO_MEASURED_SIMT_REPLACEMENT_TC_UNCHANGED')


def header(policy):
    text = '#pragma once\n// Generated by tools/fit_kpack_q8_vector.py.\n'
    text += 'namespace quactlize::q8_vector_data {\n'
    text += 'struct Row { int mode,n,k,experts,topk,channels,tokens,compute; int baseline[5],candidate[5]; };\n'
    text += 'inline constexpr Row kRows[] = {\n'
    for r in policy['rows']:
        key = ','.join(map(str, r['key'][1:]))
        old = ','.join(map(str, r['baseline']))
        new = ','.join(map(str, r['candidate']))
        text += f'  {{{key},{{{old}}},{{{new}}}}},\n'
    text += '};\n'
    text += 'struct TcRow { int n,k; char const* symbol; int tm,tn,tk,wm,wn,stages,ap,dn,split; int candidate[5]; };\n'
    text += 'inline constexpr TcRow kTcRows[] = {\n'
    for r in policy.get('tc_rows', []):
        c=r['baseline'];shape=','.join(map(str,(r['key'][2],r['key'][3])))
        geometry=','.join(str(c[k]) for k in ('tm','tn','tk','wm','wn','stages','ap','dn','split'))
        recipe=','.join(map(str,r['candidate']))
        text += f'  {{{shape},"{c["symbol"]}",{geometry},{{{recipe}}}}},\n'
    return text + '};\n}\n'


def append_model_topology(policy, matched, evidence):
    if evidence.get('schema') != 'quactlize.model-decode-promotions.v1':
        raise ValueError('model reader evidence schema differs')
    rows=[r for r in evidence['rows'] if r['name']=='q8-2048-4096']
    if len(rows)!=1 or rows[0]['arm']!='v5-c8-w4-p4-s8-r1':
        raise ValueError('Q8 topology winner differs')
    r=rows[0];key=[8,0,2048,4096,1,1,1,1,0]
    baseline=[1,4,8,4,1];candidate=[5,8,4,4,8]
    incumbent=next((x for x in matched['exact'] if x['key']==key),None)
    if (not incumbent or incumbent['config']['kind']!='simt' or
            [incumbent['config'][k] for k in ('variant','columns','warps','values','split')]!=baseline or
            any(x['key']==key for x in policy['rows'])):
        raise ValueError('Q8 topology incumbent differs')
    times=[]
    for arm in ('shipping',r['arm']):
        rounds=r['samples'][arm]
        if len(rounds)!=6 or any(len(x)!=15 or any(not math.isfinite(v) or v<=0 for v in x) for x in rounds):
            raise ValueError('Q8 topology confirmation differs')
        times.append(statistics.median(statistics.median(x) for x in rounds))
    checks=[x for x in r['numeric'] if x.get('key')==r['arm']]
    negative=r['negatives'].get(r['arm'],{})
    if (times[1]>=times[0] or len(checks)!=3 or {x['repeat'] for x in checks}!={0,1,2} or
            any(not math.isfinite(x['error']) or x['error']>=.005 or
                x.get('reducer_matched_bits') is not True for x in checks) or
            negative.get('negative')!='ZERO_A_REJECTED' or negative.get('replays')!=3 or
            r['cold_weight_bytes']<2.25*r['l2']['l2_bytes']):
        raise ValueError('Q8 topology numeric/timing evidence differs')
    policy['rows'].append(dict(key=key,baseline=baseline,candidate=candidate,
        old_us=times[0],new_us=times[1],result_sha256=r['result_sha256'],
        archive_sha256=r['archive_sha256'],reducer='ORDERED_FLOAT2_ALIGNED_M1'))
    return policy


def append_model_readers(policy, matched, evidence):
    if (evidence.get('schema')!='quactlize.model-gemv-review.v1' or evidence.get('status')!='PASS' or
            evidence.get('numeric_checks')!=510 or evidence.get('event_samples')!=2160 or
            evidence.get('reimported_reports')!=16 or len(evidence.get('records',[]))!=8):
        raise ValueError('model reader evidence incomplete')
    exact={tuple(r['key']):r for r in matched['exact']}
    points={r['point']:r for r in evidence['records']}
    if len(points)!=8 or policy.get('tc_rows'):
        raise ValueError('duplicate model reader evidence')
    policy['tc_rows']=[]
    for name,n,k,recipe in (('q8-shared-down',2048,512,[5,4,2,4,1]),
                            ('q8-qkv',8192,2048,[5,8,4,4,1]),
                            ('q8-attn-gate',4096,2048,[5,4,8,4,1])):
        r=points[name];p=r['point_definition'];key=[8,0,n,k,1,1,1,1,0]
        if (r['decision']!='EXACT_M1_INTEGRATION_CANDIDATE' or r['compute']!='F16' or
                r['input_output']!='F32' or p['q']!=8 or p['n']!=n or p['k']!=k or
                p['mode']!=0 or p['compute']!=0 or p['channels']!=1 or p['paired'] or
                len(r['round_deltas_pct'])!=6 or
                any(not math.isfinite(x) or x>=0 for x in r['round_deltas_pct']) or
                [r['config'][x] for x in ('variant','columns','warps','values','split')]!=recipe):
            raise ValueError('model reader scope or winner differs')
        old=r['confirmation']['incumbent'];incumbent=exact[tuple(key)]['config']
        record=dict(key=key,candidate=recipe,old_us=r['incumbent_us'],new_us=r['candidate_us'],
                    result_sha256=r['point_sha256'],archive_sha256=evidence['archive_sha256'])
        if name=='q8-shared-down':
            target=next(x for x in policy['rows'] if x['key']==key)
            prior=[old['config'][x] for x in ('variant','columns','warps','values','split')]
            if target['candidate']!=prior or incumbent['kind']!='simt':
                raise ValueError('model reader prior SIMT differs')
            target.update(record,comparison_baseline=prior)
        else:
            expected=old['config']
            fields=('symbol','qtype','tm','tn','tk','wm','wn','stages','ap','dn','persistent','split')
            if (old['kind']!='tc' or incumbent['kind']!='tc' or incumbent['route']!=1 or
                    expected['route']!='sf-dense' or any(incumbent[x]!=expected[x] for x in fields) or
                    incumbent['grid_mode']!=0 or incumbent['grid_b']!=0):
                raise ValueError('model reader TC incumbent differs')
            policy['tc_rows'].append(record|dict(baseline=expected))
    policy['scope']='EXACT_F32_IO_MEASURED_REPLACEMENT_INCLUDING_TWO_MATCHED_TC_POINTS'
    return policy


def main():
    matched=json.loads(MATCHED.read_text())
    result = append_model_topology(fit(json.loads(EVIDENCE.read_text()),matched),matched,json.loads(MODEL.read_text()))
    result = append_model_readers(result,matched,json.loads(READERS.read_text()))
    result['reader_evidence_sha256'] = hashlib.sha256(READERS.read_bytes()).hexdigest()
    result['model_evidence_sha256'] = hashlib.sha256(MODEL.read_bytes()).hexdigest()
    result['evidence_sha256'] = hashlib.sha256(EVIDENCE.read_bytes()).hexdigest()
    result['matched_sha256'] = hashlib.sha256(MATCHED.read_bytes()).hexdigest()
    OUTPUT.write_text(json.dumps(result, indent=2) + '\n')
    OUTPUT.with_suffix('.hpp').write_text(header(result))
    print(f"Q8_VECTOR_POLICY admitted={len(result['rows'])} tc_replacements={len(result['tc_rows'])} retained={len(result['retained'])}")


if __name__ == '__main__':
    main()
