#!/usr/bin/env python3
"""Replace only contemporaneously measured Q8 SIMT incumbents, never a TC ticket."""
import hashlib
import json
import math
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / 'docs/measurements/local_closure_replay_ppu_20260916.json'
MATCHED = ROOT / 'policies/kpack_smallm_matched_v1.json'
OUTPUT = ROOT / 'policies/kpack_q8_vector_v1.json'


def recipe(name):
    match = re.fullmatch(r'reuse-v([01])-c([48])-w([248])-p([248])-s([1248])', name)
    if not match:
        raise ValueError('invalid Q8 control recipe')
    values = list(map(int, match.groups()))
    if values[1] * values[3] > 32:
        raise ValueError('invalid Q8 output tile')
    return values


def fit(evidence, matched):
    q8 = evidence['q8']
    if q8['numeric'] != 'PASS' or q8['contexts'] != 12480 or len(q8['performance']) != 50:
        raise ValueError('incomplete Q8 evidence')
    exact = {tuple(r['key']): r for r in matched['exact']}
    rows, retained, seen = [], [], set()
    for r in q8['performance']:
        p = r['point']; ch = p['channels']
        key = [8, 2 if ch else 0, p['n'], p['k'], 256 if ch else 1,
               8 if ch else 1, ch or 1, p['tokens'], p['compute']]
        if tuple(key) in seen:
            raise ValueError('duplicate Q8 evidence')
        seen.add(tuple(key))
        old, new = (r['best'][str(a)] for a in (0, 1))
        if not all(math.isfinite(x['median_us']) and x['median_us'] > 0 and
                   len(x['round_medians']) == 6 for x in (old, new)):
            raise ValueError('invalid Q8 timing')
        delta = 100 * (new['median_us'] / old['median_us'] - 1)
        if abs(delta - r['delta_pct']) > 1e-8:
            raise ValueError('Q8 timing verdict differs')
        baseline, candidate = recipe(old['config']), recipe(new['config'])
        incumbent = exact.get(tuple(key))
        if ch:
            # This reader campaign used 16 resident experts. Do not call
            # its indexed timings an exact 256-expert model comparison.
            reason = 'KEEP_INDEXED_E16_NOT_MODEL_E256'
        elif delta >= 0:
            reason = 'READER_REGRESSION'
        elif not incumbent:
            reason = 'NO_EXACT_INCUMBENT'
        elif incumbent['config']['kind'] != 'simt':
            reason = 'KEEP_TC_NO_MATCHED_VECTOR_COMPARISON'
        elif [incumbent['config'][k] for k in ('variant','columns','warps','values','split')] != baseline:
            reason = 'KEEP_DIFFERENT_SIMT_RECIPE'
        else:
            candidate[0] += 4
            rows.append(dict(key=key, baseline=baseline, candidate=candidate,
                             old_us=old['median_us'], new_us=new['median_us'],
                             result_sha256=r['result_sha256']))
            continue
        retained.append(dict(key=key, reason=reason))
    return dict(schema='quactlize.q8-vector-policy.v1', rows=rows, retained=retained,
                archive_sha256=evidence['archive_sha256'],
                scope='EXACT_F32_IO_MEASURED_SIMT_REPLACEMENT_TC_UNCHANGED')


def header(policy):
    text = '#pragma once\n// Generated by tools/fit_kpack_q8_vector.py.\n'
    text += 'namespace quactlize::q8_vector_data {\n'
    text += 'struct Row { int mode,n,k,experts,topk,channels,tokens,compute; int baseline[5],candidate[5]; };\n'
    text += 'inline constexpr Row kRows[] = {\n'
    for r in policy['rows']:
        key = ','.join(map(str, r['key'][1:]))
        old = ','.join(map(str, r['baseline']))
        new = ','.join(map(str, r['candidate']))
        text += f'  {{{key},{{{old}}},{{{new}}}}},\n'
    return text + '};\n}\n'


def main():
    result = fit(json.loads(EVIDENCE.read_text()), json.loads(MATCHED.read_text()))
    result['evidence_sha256'] = hashlib.sha256(EVIDENCE.read_bytes()).hexdigest()
    result['matched_sha256'] = hashlib.sha256(MATCHED.read_bytes()).hexdigest()
    OUTPUT.write_text(json.dumps(result, indent=2) + '\n')
    OUTPUT.with_suffix('.hpp').write_text(header(result))
    print(f"Q8_VECTOR_POLICY admitted={len(result['rows'])} retained={len(result['retained'])} TC_UNCHANGED")


if __name__ == '__main__':
    main()
