#!/usr/bin/env python3
"""Export the fitted host selector as SDK-free C++17 tables.

This does not instantiate or launch kernels. A consumer must bind the complete
returned runtime identity to a matching compiled inventory, check can_implement,
and explicitly decide whether to admit an unmeasured interpolation proposal.
"""

import argparse
import json
from pathlib import Path

import kpack_policy as policy


def generate(model):
    if model.get("schema") != policy.SCHEMA or model["device"] != {
        "name": "PPU-ZW810",
        "compute_units": 72,
    }:
        raise ValueError("unsupported policy schema/device")
    configs = sorted(model["configurations"])
    config_index = {c: i for i, c in enumerate(configs)}
    nodes, points, families = [], [], []

    def tree(node):
        if node is None:
            return -1
        index = len(nodes)
        nodes.append(None)
        if "config" in node:
            nodes[index] = (config_index[node["config"]], 0, 0, -1, -1)
        else:
            nodes[index] = (
                -1,
                node["axis"],
                node["le"],
                tree(node["left"]),
                tree(node["right"]),
            )
        return index

    for family in model["families"]:
        q, route, n, k, gs, experts = family["key"]
        start = len(points)
        for f in family["observed"]:
            points.append((f[0], f[1] if len(f) > 1 else 0, 0))
        for b in family["blocked"]:
            f = b["features"]
            points.append((f[0], f[1] if len(f) > 1 else 0, 1))
        bounds = family["bounds"] or [[0, 0]] * len(family["axes"])
        second = bounds[1] if len(bounds) > 1 else [0, 0]
        families.append(
            (
                q,
                policy.ROUTES.index(route),
                n,
                k,
                gs,
                experts,
                *bounds[0],
                *second,
                start,
                len(points) - start,
                tree(family["tree"]),
            )
        )
    quote = json.dumps
    config_rows = []
    for cid in configs:
        c = model["configurations"][cid]
        fields = [
            quote(cid),
            quote(c["symbol"]),
            quote(c["algorithm"]),
            str(c["qtype"]),
            str(policy.ROUTES.index(c["route"])),
            *(
                str(c[k])
                for k in (
                    "tm",
                    "tn",
                    "tk",
                    "wm",
                    "wn",
                    "stages",
                    "ap",
                    "dn",
                    "persistent",
                    "split",
                    "grid",
                    "layout",
                )
            ),
            str(("implicit", "fixed", "ordinary").index(c["grid_mode"])),
            c["mapping_id"] + "ULL",
        ]
        config_rows.append("  {" + ", ".join(fields) + "},")

    def table(name, rows):
        return (
            f"inline constexpr {name} k{name}s[] = {{\n"
            + "\n".join("  {" + ", ".join(map(str, row)) + "}," for row in rows)
            + "\n};\n"
        )

    if not configs or not nodes or not points:
        raise ValueError("cannot export an empty policy")
    return f"""// Generated by tools/generate_kpack_policy_header.py; do not edit.
// Host selection only. This header is NOT a compiled kernel inventory.
#pragma once
#include <cstdint>
#include <cstring>
namespace quactlize_kpack_policy {{
inline constexpr char kPolicySha256[] = "{policy.digest(model)}";
enum class Route {{ FqDense, SfDense, FqGrouped, SfGrouped }};
enum class Status {{ NoMeasuredPolicy, MeasuredPolicy, InterpolatedProposal }};
struct Query {{
  int qtype, n, k, group_size;
  Route route;
  int m = 0, total_rows = 0, max_rows = 0, experts = 1;
  int compute_units = 72;
  char const* device_name = "PPU-ZW810";
  std::uint64_t mapping_id = 0;
}};
struct Config {{
  char const *id, *symbol, *algorithm;
  int qtype, route, tm, tn, tk, wm, wn, stages, ap, dn, parent_persistent, split, grid, layout, grid_mode;
  std::uint64_t mapping_id;
}};
struct Selection {{
  Status status = Status::NoMeasuredPolicy;
  Config const* config = nullptr;
  int grid = 0;
}};
namespace detail {{
struct Node {{ int config, axis, le, left, right; }};
struct Point {{ int x, y, blocked; }};
struct Family {{ int qtype, route, n, k, gs, experts, xmin, xmax, ymin, ymax, first, count, root; }};
inline constexpr Config kConfigs[] = {{
{chr(10).join(config_rows)}
}};
{table('Node', nodes)}
{table('Point', points)}
{table('Family', families).replace('kFamilys', 'kFamilies')}
}} // namespace detail
inline Selection select(Query const& q) {{
  using namespace detail;
  int route = static_cast<int>(q.route);
  bool grouped = route >= 2;
  int gs = q.qtype == 12 || q.qtype == 13 ? 32 : 16;
  std::uint64_t mapping = q.qtype == 12 ? 0x51344b5034540001ULL : 0x514b504b54000001ULL;
  int x = grouped ? q.total_rows : q.m, y = grouped ? q.max_rows : 0;
  if (route < 0 || route > 3 || q.qtype < 10 || q.qtype > 14 ||
      q.n <= 0 || q.n % 16 || q.k <= 0 || q.k % 256 || q.group_size != gs ||
      x <= 0 || q.experts <= 0 || (!grouped && q.experts != 1) ||
      (grouped && (y <= 0 || y > x || std::int64_t(x) > std::int64_t(y) * q.experts)) ||
      q.compute_units != 72 || !q.device_name || std::strcmp(q.device_name, "PPU-ZW810") ||
      q.mapping_id != mapping) return {{}};
  for (auto const& f : kFamilies) {{
    if (f.qtype != q.qtype || f.route != route || f.n != q.n || f.k != q.k ||
        f.gs != q.group_size || f.experts != q.experts) continue;
    bool observed = false;
    for (int i = f.first; i < f.first + f.count; ++i) {{
      auto const& p = kPoints[i];
      if (p.x != x || p.y != y) continue;
      if (p.blocked) return {{}};
      observed = true;
    }}
    if (f.root < 0 || x < f.xmin || x > f.xmax || y < f.ymin || y > f.ymax) return {{}};
    int index = f.root;
    while (kNodes[index].config < 0) {{
      auto const& node = kNodes[index];
      index = (node.axis == 0 ? x : y) <= node.le ? node.left : node.right;
    }}
    auto const& c = kConfigs[kNodes[index].config];
    if (q.k % (c.tk * c.split) || (c.ap && (grouped || q.m != 1)) ||
        (route == 1 && c.tm == 8 && q.m >= 8) ||
        (route == 0 && ((c.tm == 8 && q.m > 64) || (c.split != 1 && q.m >= 64)))) return {{}};
    std::int64_t grid = c.grid;
    if (c.grid_mode == 2) grid = ((std::int64_t(q.m) + c.tm - 1) / c.tm) * ((std::int64_t(q.n) + c.tn - 1) / c.tn);
    if (grid > INT32_MAX) return {{}};
    return {{observed ? Status::MeasuredPolicy : Status::InterpolatedProposal, &c, int(grid)}};
  }}
  return {{}};
}}
}} // namespace quactlize_kpack_policy
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("policy", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    if args.output.exists() or args.output.is_symlink():
        parser.error("output already exists; use a fresh path")
    try:
        header = generate(json.loads(args.policy.read_text()))
        with args.output.open("x") as f:
            f.write(header)
    except (OSError, KeyError, ValueError) as error:
        parser.error(str(error))
    print(f"KPACK_POLICY_HEADER path={args.output} sdk_required=0 kernel_inventory=0")


if __name__ == "__main__":
    main()
