#!/usr/bin/env python3
"""Regenerate the CMake input for the finite GEMV tactic authority.

The C++ header is the authority.  This script only serialises its ``--units``
view so CMake does not need to compile and run a helper during configuration.
The local gate regenerates the file and requires byte equality.
"""

from __future__ import annotations

import argparse
import csv
import io
from pathlib import Path
import subprocess
import tempfile


ROOT = Path(__file__).resolve().parent.parent
EMITTER = ROOT / "dev/fold_derivation/emit_gemv_tactic_space.cpp"
DEFAULT_OUTPUT = ROOT / "benchmarks/gemv_tactic_units.cmake"


def emit() -> str:
    with tempfile.TemporaryDirectory(prefix="qz-gemv-units-") as td:
        exe = Path(td) / "emit"
        build = subprocess.run(
            ["g++", "-std=c++17", "-I", str(ROOT / "quactlize/include"),
             str(EMITTER), "-o", str(exe)],
            cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        )
        if build.returncode:
            raise RuntimeError("cannot build tactic emitter:\n" + build.stdout)
        run = subprocess.run([str(exe), "--units"], cwd=ROOT, text=True,
                             stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        if run.returncode:
            raise RuntimeError("tactic emitter rejected its unit view:\n" + run.stdout)

    rows: list[str] = []
    census = None
    for row in csv.reader(io.StringIO(run.stdout)):
        if not row:
            continue
        if row[0] == "UNIT":
            if len(row) != 8:
                raise RuntimeError(f"malformed UNIT row: {row}")
            rows.append("|".join(row[1:]))
        elif row[0] == "UNIT_CENSUS" and row[1] == "compile_units":
            census = int(row[2])
    if census != len(rows) or census != 540 or len(set(rows)) != len(rows):
        raise RuntimeError(
            f"unit view is not the finite 540-row set: census={census} "
            f"rows={len(rows)} unique={len(set(rows))}")

    body = [
        "# GENERATED by tools/generate_gemv_tactic_units.py -- do not edit.",
        "# Source authority: gemv_lowbit/gemv_tactic_space.hpp.",
        f"set(_GEMV_AUTHORITY_UNIT_COUNT {len(rows)})",
        "set(_GEMV_AUTHORITY_UNITS",
    ]
    body.extend(f'  "{row}"' for row in rows)
    body.append(")")
    return "\n".join(body) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    wanted = emit()
    if args.check:
        got = args.output.read_text() if args.output.is_file() else ""
        if got != wanted:
            print(f"[gemv-tactic-units] FAIL stale or missing {args.output}")
            return 1
        print("[gemv-tactic-units] PASS: 540 compile units exactly match the C++ authority")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(wanted)
    print(f"wrote {args.output} (540 units)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
