#!/usr/bin/env bash
# Focused fresh-process diagnosis for the two non-TM8 failures that block the
# final A09 campaign.  This is not a sweep and draws no performance conclusion.
# Each exact shipping parent is generated by its canonical matrix authority and
# compiled in its own CMake tree, so a sticky device error or PPUToolchain's
# source-name object rule cannot leak between arms.
set -u -o pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
SOURCE_SHA="$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || true)"
SOURCE_SHORT="${SOURCE_SHA:0:8}"
if [ -n "${OUT:-}" ]; then
  RUN_DIR="$(realpath -m -- "$OUT")"
elif [ -d /workspace ] && [ -w /workspace ]; then
  RUN_DIR="/workspace/quactlize-a09-blockers-${SOURCE_SHORT}-$(date -u +%Y%m%dT%H%M%SZ)-$$"
else
  RUN_DIR="${TMPDIR:-/tmp}/quactlize-a09-blockers-${SOURCE_SHORT}-$(date -u +%Y%m%dT%H%M%SZ)-$$"
fi

FQ_SYMBOL=fqk_tc_q12_l1_a0_tm64_tn128_tk64_wm16_wn32_s4_bc0_ap0_dn32
SF_SUBJECT_SYMBOL=sf_q12_a0_tm256_tn256_tk128_wm16_wn128_s2_bc0_ap0_dn32
SF_CONTROL_SYMBOL=sf_q12_a0_tm256_tn256_tk128_wm32_wn128_s2_bc0_ap0_dn32
FQ_SEED=0x740e23673ecf70c7
SF_SEED=0x6a09e667f3bcc909

fail() {
  printf '[a09-blockers] FAIL phase=%s artifacts=%s\n' "$1" "$RUN_DIR" >&2
  return 1
}

generate_arms() {
  python3 -B "$ROOT/tools/gen_fully_quantized_kpack_discovery_units.py" \
    --qtype 12 --parent-begin 1417 --parent-count 1 --per-unit 1 \
    --out-dir "$RUN_DIR/generated/fq-dense" \
    >"$RUN_DIR/results/fq-dense.generate.log" 2>&1 || return 1
  python3 -B "$ROOT/tools/gen_scalefirst_internal_units.py" \
    --qtype 12 --artifact-tk 0 --bchunk 0 --weight-layout 1 \
    --select-symbol "$SF_SUBJECT_SYMBOL" --per-unit 1 \
    --out-dir "$RUN_DIR/generated/sf-subject" \
    >"$RUN_DIR/results/sf-subject.generate.log" 2>&1 || return 1
  python3 -B "$ROOT/tools/gen_scalefirst_internal_units.py" \
    --qtype 12 --artifact-tk 0 --bchunk 0 --weight-layout 1 \
    --select-symbol "$SF_CONTROL_SYMBOL" --per-unit 1 \
    --out-dir "$RUN_DIR/generated/sf-control" \
    >"$RUN_DIR/results/sf-control.generate.log" 2>&1 || return 1
  printf '[a09-blockers] generated fq=1417 sf=4738/4750\n'
}

build_device_limits_probe() {
  local output="$RUN_DIR/build/a09_device_limits_probe"
  local log="$RUN_DIR/results/device-limits.build.log"
  local -a compiler include_flags
  read -r -a compiler <<<"${CXX:-c++}"
  [ "${#compiler[@]}" -gt 0 ] || return 1
  include_flags=(-I "$PPU_SDK_ROOT/include")
  if [ -d "$PPU_SDK_ROOT/targets/x86_64-linux/include" ]; then
    include_flags+=(-I "$PPU_SDK_ROOT/targets/x86_64-linux/include")
  fi
  "${compiler[@]}" -std=c++17 -DSWITCH_TO_HGGCRT \
    "${include_flags[@]}" "$ROOT/tools/a09_device_limits_probe.cpp" \
    -o "$output" -L "$PPU_SDK_ROOT/lib" \
    -Wl,-rpath,"$PPU_SDK_ROOT/lib" -Wl,--no-as-needed \
    -Wl,--allow-shlib-undefined \
    -lhg_wrapper -lhggc_wrapper -lhggcrt1 -lhggc -ldl \
    >"$log" 2>&1
}

build_arm() {
  local arm=$1 family=$2 target=$3
  local generated="$RUN_DIR/generated/$arm"
  local build="$RUN_DIR/build/$arm"
  local log="$RUN_DIR/results/$arm.build.log"
  local -a family_env=()
  case "$family" in
    fq)
      family_env=(
        "FQ_SWEEP_GENERATED_DIR=$generated"
        FQ_SWEEP_QTYPE=12 FQ_SWEEP_ARTIFACT_TK=0 FQ_SWEEP_BCHUNK=0
        FQ_SWEEP_PACKED_FORMAT=0 FQ_SWEEP_WEIGHT_LAYOUT=1)
      ;;
    sf)
      family_env=(
        "SCALEFIRST_SWEEP_GENERATED_DIR=$generated"
        SCALEFIRST_SWEEP_QTYPE=12 SCALEFIRST_SWEEP_ARTIFACT_TK=0
        SCALEFIRST_SWEEP_BCHUNK=0 SCALEFIRST_SWEEP_WEIGHT_LAYOUT=1)
      ;;
    *) return 1 ;;
  esac
  printf '[a09-blockers] build arm=%s family=%s jobs=%s\n' \
    "$arm" "$family" "$JOBS_PER_BUILD"
  env -u CC -u CXX -u CMAKE_GENERATOR -u CMAKE_TOOLCHAIN_FILE \
    -u FQ_SWEEP_GENERATED_DIR -u FQ_GROUPED_KPACK_GENERATED_DIR \
    -u FQ_A02_Q3_GENERATED_DIR -u FQ_KQUANT_PERF_QTYPE \
    -u SCALEFIRST_SWEEP_GENERATED_DIR \
    -u SCALEFIRST_GROUPED_KPACK_GENERATED_DIR \
    PPU_BUILD_DIR="$build" PPU_BUILD_RESUME=0 \
    PPU_PRESERVE_STALE_BUILD_TREES=1 \
    PPU_ARCHS=ppu0010 PPU_SDK="$PPU_SDK_ROOT" JOBS="$JOBS_PER_BUILD" \
    QUACTLIZE_KPACK_GLOBAL_PREFLIGHT_RECEIPT="$PREFLIGHT" \
    "${family_env[@]}" TARGET="$target" "$ROOT/build.sh" >"$log" 2>&1
  local rc=$?
  if [ "$rc" -ne 0 ]; then
    printf '[a09-blockers] build failed arm=%s rc=%s log=%s\n' \
      "$arm" "$rc" "$log" >&2
    tail -120 "$log" >&2
  else
    printf '[a09-blockers] build complete arm=%s\n' "$arm"
  fi
  return "$rc"
}

run_fq() {
  local binary="$RUN_DIR/build/fq-dense/ppu_targets/test_fully_quantized_internal_sweep"
  local log="$RUN_DIR/results/fq-dense.run.log" rc=0
  "$binary" --shape=7x8192x5120 --iterations=1 \
    --correctness-repeats=1 --only-split=1 --bc-mode=skip \
    --schedule-seed="$FQ_SEED" >"$log" 2>&1 || rc=$?
  printf '%d\n' "$rc" >"$RUN_DIR/results/fq-dense.rc"
  printf '[a09-blockers] run arm=fq-dense fresh_process=1 rc=%d\n' "$rc"
  grep -E '^FQ_(KPACK4_FIXTURE|SHARD|TC_CELL|SHAPE_DONE) ' "$log" || true
}

run_sf() {
  local arm=$1
  local binary="$RUN_DIR/build/$arm/ppu_targets/test_scalefirst_internal_sweep"
  local log="$RUN_DIR/results/$arm.run.log" rc=0
  "$binary" --shape=16x4096x2048 --algorithm=nonpersistent \
    --fixture=exact --fixture-binding --iterations=1 \
    --correctness-repeats=1 --schedule-seed="$SF_SEED" \
    >"$log" 2>&1 || rc=$?
  printf '%d\n' "$rc" >"$RUN_DIR/results/$arm.rc"
  printf '[a09-blockers] run arm=%s fresh_process=1 rc=%d\n' "$arm" "$rc"
  grep -E '^(SF_(SHARD|FIXTURE|ATTEMPT|CELL|COMPLETE|FATAL))' "$log" || true
}

main() {
  local default_sdk=${PPU_SDK:-${PPU_HOME:-}}
  [ -n "$SOURCE_SHA" ] || { fail source_head; return 1; }
  [ -n "$default_sdk" ] || { fail missing_ppu_sdk; return 1; }
  PPU_SDK_ROOT="$(realpath -e -- "$default_sdk" 2>/dev/null)" || {
    fail invalid_ppu_sdk; return 1;
  }
  [ -x "$PPU_SDK_ROOT/bin/hgcc" ] || { fail sdk_lacks_hgcc; return 1; }
  case "${CUDA_VISIBLE_DEVICES:-}" in
    ''|*,*|*[!0-9]*) fail one_numeric_CUDA_VISIBLE_DEVICES_required; return 1 ;;
  esac
  case "${JOBS:-48}" in
    ''|*[!0-9]*|0) fail invalid_JOBS; return 1 ;;
  esac
  JOBS_PER_BUILD=${JOBS:-48}
  if [ "$JOBS_PER_BUILD" -gt 64 ]; then
    fail JOBS_exceeds_64_per_parallel_build; return 1
  fi
  if [ -n "${PPU_DEFS:-}" ] || [ -n "${PPU_EXTRA_DEFS:-}" ]; then
    fail ambient_ppu_defs; return 1
  fi
  if [ -e "$RUN_DIR" ]; then
    fail output_already_exists; return 1
  fi
  mkdir -p "$RUN_DIR"/{generated,build,inputs,results} || {
    fail create_output; return 1;
  }
  PREFLIGHT="$RUN_DIR/inputs/kpack-global-preflight.json"

  bash -n "$ROOT/tools/run_a09_remaining_blockers_box.sh" || {
    fail runner_syntax; return 1;
  }
  python3 -B "$ROOT/ci/check_a09_remaining_blockers.py" || {
    fail static_contract; return 1;
  }
  if ! python3 -B "$ROOT/tools/kpack_global_build_preflight.py" create \
      --root "$ROOT" --output "$PREFLIGHT" \
      >"$RUN_DIR/results/global-preflight.log" 2>&1; then
    tail -120 "$RUN_DIR/results/global-preflight.log" >&2
    fail global_preflight; return 1
  fi
  if ! build_device_limits_probe; then
    tail -120 "$RUN_DIR/results/device-limits.build.log" >&2
    fail build_device_limits_probe; return 1
  fi
  if ! "$RUN_DIR/build/a09_device_limits_probe" \
      >"$RUN_DIR/results/device-limits.log" 2>&1; then
    cat "$RUN_DIR/results/device-limits.log" >&2
    fail run_device_limits_probe; return 1
  fi
  cat "$RUN_DIR/results/device-limits.log"
  if ! generate_arms; then
    fail generate; return 1
  fi
  if ! python3 -B "$ROOT/ci/check_a09_remaining_blockers.py" \
      --validate-generated-dir "$RUN_DIR"; then
    fail generated_authority; return 1
  fi

  local fq_pid subject_pid control_pid fq_rc=0 subject_rc=0 control_rc=0
  build_arm fq-dense fq test_fully_quantized_internal_sweep &
  fq_pid=$!
  build_arm sf-subject sf test_scalefirst_internal_sweep &
  subject_pid=$!
  build_arm sf-control sf test_scalefirst_internal_sweep &
  control_pid=$!
  printf '[a09-blockers] parallel builds started pids=%s,%s,%s\n' \
    "$fq_pid" "$subject_pid" "$control_pid"
  wait "$fq_pid" || fq_rc=$?
  wait "$subject_pid" || subject_rc=$?
  wait "$control_pid" || control_rc=$?
  [ "$fq_rc" -eq 0 ] || { fail build_fq_dense; return 1; }
  [ "$subject_rc" -eq 0 ] || { fail build_sf_subject; return 1; }
  [ "$control_rc" -eq 0 ] || { fail build_sf_control; return 1; }

  # These are three distinct executable invocations.  A launch failure in one
  # process cannot poison either control, which is the point of this gate.
  run_fq
  run_sf sf-subject
  run_sf sf-control

  local check_rc=0
  python3 -B "$ROOT/ci/check_a09_remaining_blockers.py" \
    --validate-run-dir "$RUN_DIR" | tee "$RUN_DIR/results/check.log" || \
    check_rc=${PIPESTATUS[0]}
  [ "$check_rc" -eq 0 ] || { fail device_results; return 1; }

  sha256sum \
    "$RUN_DIR/generated/fq-dense/manifest.json" \
    "$RUN_DIR/generated/sf-subject/manifest.json" \
    "$RUN_DIR/generated/sf-control/manifest.json" \
    "$RUN_DIR/build/fq-dense/ppu_targets/test_fully_quantized_internal_sweep" \
    "$RUN_DIR/build/sf-subject/ppu_targets/test_scalefirst_internal_sweep" \
    "$RUN_DIR/build/sf-control/ppu_targets/test_scalefirst_internal_sweep" \
    "$RUN_DIR/results/fq-dense.run.log" \
    "$RUN_DIR/results/sf-subject.run.log" \
    "$RUN_DIR/results/sf-control.run.log" \
    "$RUN_DIR/results/device-limits.log" \
    "$RUN_DIR/build/a09_device_limits_probe" \
    "$ROOT/tools/a09_device_limits_probe.cpp" \
    "$ROOT/tools/run_a09_remaining_blockers_box.sh" \
    "$ROOT/ci/check_a09_remaining_blockers.py" \
    >"$RUN_DIR/results/authority.sha256" || {
    fail authority_hash; return 1;
  }
  printf 'A09_REMAINING_BLOCKERS_DIAGNOSTIC verdict=DIAGNOSTIC_COMPLETE source=%s actlize=%s fresh_processes=3 artifacts=%s\n' \
    "$SOURCE_SHA" "$(git -C "$ROOT/third_party/actlize" rev-parse HEAD)" \
    "$RUN_DIR"
}

main "$@"
