#!/usr/bin/env python3
"""Validate a native dispatch package before allowing model execution."""

import argparse
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from quactlize.runtime.compiler import Compiler, sha, source_contract
from quactlize.runtime.tuning import digest
from tools.kpack_jit import module_source


PREFILL_MODEL_EXPORTS = frozenset({'quactlize_kpack_dequant_v1'} | {
    'quactlize_kpack_prefill_' + name + '_v1'
    for name in ('query', 'prepare', 'run', 'destroy', 'error', 'provider_image')})

# The small-M model profile is consumed by the private v0.3 caller. Check the
# actual dynamic exports, not just a receipt generated by the same old build.
SMALLM_MODEL_EXPORTS = {
    'libquactlize_kpack_dispatch.so': frozenset('quactlize_kpack_dispatch_' + name for name in (
        'open_v1 close_v1 query_v1 prepare_v1 run_v1 destroy_v1 error_v1 enable_jit_v1 '
        'bind_llama_indexed_v1 query_dense_io_v1 prepare_dense_io_v1 query_decode_v1 '
        'query_smallm_v1 prefill_v1 moe_create_v1 moe_create_v2 moe_create_v3 '
        'moe_run_v1 moe_run_router_v1 moe_destroy_v1 moe_simt_scratch_v1 moe_bind_finish_v1').split()),
    'libquactlize_ppu_execution.so': frozenset('quactlize_kpack_' + name for name in (
        'gemv_query_v1 gemv_run_v1 sf_prepare_v1 simt_query_v1 simt_run_v1 '
        'q4_decode_select_v1 q4_decode_run_v1 q4_decode_cast_v1 '
        'q4_decode_indexed_prepare_v1 q4_decode_indexed_finish_v1 '
        'moe_simt_query_v1 moe_simt_bind_v1 moe_mixed_stage_v1 moe_weighted_finish_v1').split()),
}
COMPUTE_MODEL_EXPORTS = {
    'libquactlize_kpack_dispatch.so': frozenset('quactlize_kpack_dispatch_' + name for name in (
        'query_compute_v1 prepare_compute_v1 prepare_dense_io_v2 query_smallm_v2 moe_create_v4').split()),
    'libquactlize_ppu_execution.so': frozenset('quactlize_kpack_' + name for name in (
        'simt_query_v2 simt_run_v2 moe_mixed_stage_v2 moe_weighted_finish_v2').split()),
}


def require_exports(path, names):
    """Read the host ELF symbol table; do not dlopen or initialize a GPU."""
    path = Path(path)
    with path.open('rb') as stream:
        if stream.read(4) != b'\x7fELF':
            raise ValueError('not an ELF runtime library: ' + str(path))
    result = subprocess.run(['nm', '-D', '--defined-only', str(path)],
                            capture_output=True, text=True)
    if result.returncode:
        raise ValueError('cannot inspect runtime exports: ' + str(path) + ': ' + result.stderr.strip())
    exports = {line.split()[-1].split('@')[0] for line in result.stdout.splitlines() if line.split()}
    missing = set(names) - exports
    if missing:
        raise ValueError('model ABI missing in ' + str(path) + ': ' + ', '.join(sorted(missing)))


def prefill_paths(root, receipt, *, sdk=None):
    """Verify the optional composition closure, never load a device runtime."""
    root = Path(root).resolve(strict=True)
    names = {'library': 'libquactlize_ppu_prefill.so',
             'receipt': 'prefill-runtime.json', 'helper': 'kpack_deepgemm_prewarm.py'}
    if not isinstance(receipt, dict):
        raise ValueError('prefill package receipt is missing')
    for field, name in names.items():
        path = root / name
        if (receipt.get(field) != name or path.is_symlink() or
                not path.is_file() or sha(path) != receipt.get(field + '_sha256')):
            raise ValueError('prefill payload differs: ' + name)
    build = json.loads((root / names['receipt']).read_text())
    if (build.get('schema') != 'quactlize.prefill-runtime.v1' or
            build.get('library') != names['library'] or
            build.get('sha256') != receipt['library_sha256']):
        raise ValueError('prefill build/library identity differs')
    require_exports(root / names['library'], PREFILL_MODEL_EXPORTS)
    if sdk is not None:
        for name, expected in build['runtime'].items():
            if Path(name).name != name or sha(Path(sdk) / 'lib' / name) != expected:
                raise ValueError('prefill SDK runtime differs: ' + name)
    return list(names.values())


def pack_paths(root, receipt):
    """Validate the Quactlize producer independently of any caller build."""
    root = Path(root).resolve(strict=True)
    expected = {'pack/libquactlize_ppu_pack.so', 'pack/manifest.json'}
    if receipt.get('schema') != 'quactlize.kpack-producer-package.v1' or set(receipt.get('files', {})) != expected:
        raise ValueError('packer package payload set differs')
    for name, digest in receipt['files'].items():
        path = root / name
        if path.is_symlink() or not path.resolve(strict=True).is_relative_to(root) or sha(path) != digest:
            raise ValueError('packer payload differs: ' + name)
    build = json.loads((root / 'pack/manifest.json').read_text())
    if (build.get('schema') != 'quactlize.kpack-device-pack-build.v1' or
            build.get('library') != 'libquactlize_ppu_pack.so' or
            build.get('sha256') != receipt['files']['pack/libquactlize_ppu_pack.so']):
        raise ValueError('packer build/library identity differs')
    return sorted(expected)


def model_paths(root, model):
    """Read-only validation of historical prebuilt caller packages."""
    root = Path(root).resolve(strict=True)
    if model.get('schema') != 'quactlize.q4-model-deployment.v1':
        raise ValueError('model deployment schema differs')
    commit = model.get('llama_source_commit', '')
    if len(commit) != 40 or any(c not in '0123456789abcdef' for c in commit):
        raise ValueError('model caller source commit differs')
    files, links = model.get('files', {}), model.get('links', {})
    required = {f'llama/bin/{name}' for name in ('llama-server', 'llama-batched-bench', 'llama-perplexity')}
    required |= {'pack/libquactlize_ppu_pack.so', 'pack/manifest.json'}
    if not required <= files.keys() or files.keys() & links.keys():
        raise ValueError('model deployment payload set differs')
    for name, expected in files.items():
        path = root / name
        if (not (name.startswith('llama/bin/') or name.startswith('pack/')) or
                path.is_symlink() or not path.resolve(strict=True).is_relative_to(root) or sha(path) != expected):
            raise ValueError('model payload differs: ' + name)
    for name, target in links.items():
        path = root / name
        if (not name.startswith('llama/bin/') or '/' in target or not path.is_symlink() or
                str(path.readlink()) != target or not path.resolve(strict=True).is_relative_to(root/'llama/bin')):
            raise ValueError('model library link differs: ' + name)
    return list(files) + list(links)


def verify(root, *, sdk=None):
    root = Path(root).resolve(strict=True)
    m = json.loads((root / "manifest.json").read_text())
    if (m.get("schema") != "quactlize.kpack-native-dispatch.v1" or
        not isinstance(m.get("modules"), list) or
        (not m["modules"] and m.get("jit_required") is not True)):
        raise ValueError("native package schema or module set differs")
    for name, field in (
        ("libquactlize_kpack_dispatch.so", "dispatch_sha256"),
        ("libquactlize_ppu_execution.so", "execution_sha256"),
    ):
        if sha(root / name) != m[field]:
            raise ValueError("native payload differs: " + name)
    if "decode_policy" in m:
        receipt = m["decode_policy"]
        path = (root / receipt["path"]).resolve(strict=True)
        if (path.parent != root or sha(path) != receipt["sha256"] or
            m["execution_receipt"].get("q4_decode_policy_sha256") != receipt["sha256"]):
            raise ValueError("decode policy/execution identity differs")
    if 'smallm_policy' in m:
        receipt=m['smallm_policy']
        if (receipt.get('path')!='smallm-policy.json' or (root/'smallm-policy.json').is_symlink() or
                sha(root/'smallm-policy.json')!=receipt['sha256'] or
                m['policy_hashes'].get('policies/kpack_smallm_v1.hpp')!=receipt['header_sha256'] or
                not m['execution_receipt'].get('simt_configs')):
            raise ValueError('small-M policy/execution identity differs')
        for name, required in SMALLM_MODEL_EXPORTS.items():
            require_exports(root / name, required)
    if 'smallm_matched_policy' in m:
        receipt=m['smallm_matched_policy']
        if (receipt.get('path')!='smallm-matched-policy.json' or (root/receipt['path']).is_symlink() or
                sha(root/receipt['path'])!=receipt['sha256'] or
                m['policy_hashes'].get('policies/kpack_smallm_matched_v1.hpp')!=receipt['header_sha256']):
            raise ValueError('matched small-M policy identity differs')
        require_exports(root/'libquactlize_kpack_dispatch.so',{'quactlize_kpack_dispatch_query_smallm_v3'})
    if 'q8_vector_policy' in m:
        receipt=m['q8_vector_policy']
        if (receipt.get('path')!='q8-vector-policy.json' or (root/receipt['path']).is_symlink() or
                sha(root/receipt['path'])!=receipt['sha256'] or
                m['policy_hashes'].get('policies/kpack_q8_vector_v1.hpp')!=receipt['header_sha256'] or
                not {4,5}<={r['variant'] for r in m['execution_receipt']['simt_configs']['8']}):
            raise ValueError('Q8 vector policy/execution identity differs')
    if 'compute_contract' in m:
        c=m['compute_contract']
        execution=m['execution_receipt'].get('simt_compute_v2',{})
        if (c.get('schema')!='quactlize.explicit-compute.v1' or c.get('formats')!=[8,10,11,12,13,14] or
            execution.get('compute')!=['f16','bf16'] or execution.get('formats')!=c['formats']):
            raise ValueError('compute host/execution contract differs')
        for name, required in COMPUTE_MODEL_EXPORTS.items():
            require_exports(root/name,required)
        if 'metadata' in c:
            if (c['metadata']!='KQUANT_DIRECT_BF16_V1_Q8_ORIGINAL_F16' or c.get('grouped_abi')!=4 or c.get('sf_abi')!=2):
                raise ValueError('typed BF16 metadata contract differs')
            require_exports(root/'libquactlize_kpack_dispatch.so',{
                'quactlize_kpack_dispatch_prepare_compute_v2','quactlize_kpack_dispatch_prefill_compute_v1'})
            require_exports(root/'libquactlize_ppu_execution.so',{'quactlize_kpack_sf_prepare_v2'})
            if 'prefill' in m:
                require_exports(root/'libquactlize_ppu_prefill.so',{'quactlize_kpack_dequant_v2'})
    if 'prefill' in m:
        prefill_paths(root, m['prefill'], sdk=sdk)
    elif (root / 'libquactlize_ppu_prefill.so').exists():
        raise ValueError('unmanifested prefill runtime would arm the model loader')
    if 'bf16_gate' in m:
        from dev.bf16_compute.run import validate_package
        receipt=m['bf16_gate']
        if (receipt.get('path')!='bf16/manifest.json' or
                sha(root/'bf16/manifest.json')!=receipt.get('sha256')):
            raise ValueError('BF16 gate receipt differs')
        gate=validate_package(root/'bf16')
        if (len(gate['cases'])!=receipt.get('cases') or len(gate['modules'])!=receipt.get('modules') or
                (gate.get('reused_execution') or {}).get('sha256')!=m['execution_sha256'] or
                any(r['identity']['base_source_contract']!=m['jit_source_contract'] for r in
                    [*gate['modules'].values(),*gate.get('matched_modules',{}).values()])):
            raise ValueError('BF16 gate execution/module contract differs from model')
    if 'local_optimization_gate' in m:
        from tools.attach_kpack_local_gates import payload_paths
        payload_paths(root,m['local_optimization_gate'],sdk=sdk)
    if 'q4_bf16_gate' in m:
        from dev.bf16_fastpath.gate import verified
        receipt=m['q4_bf16_gate']
        if receipt.get('path')!='q4-bf16-gate/manifest.json' or sha(root/receipt['path'])!=receipt.get('sha256'):
            raise ValueError('typed Q4 gate receipt differs')
        gate,library=verified(root/'q4-bf16-gate')
        if (gate['sha256']!=m['execution_sha256'] or
                str(library.relative_to(root))!=receipt.get('library') or
                gate['plan']['denominator']!=receipt.get('denominator')):
            raise ValueError('typed Q4 gate image/denominator differs from model')
    if 'moe_mixed_gate' in m:
        gate=m['moe_mixed_gate']
        if (gate.get('schema')!='quactlize.moe-mixed-gate.v1' or gate.get('stage_cases')!=80 or
                gate.get('chain_cases')!=24 or len(gate.get('simt_binaries',[]))!=1):
            raise ValueError('mixed MoE gate denominator differs')
        item=gate['simt_binaries'][0]
        if item.get('path')!='mixed-stages' or (root/'mixed-stages').is_symlink() or sha(root/'mixed-stages')!=item.get('sha256'):
            raise ValueError('mixed MoE stage binary differs')
    if 'model' in m:
        model_paths(root, m['model'])
    if 'pack' in m:
        pack_paths(root, m['pack'])
    if m.get("jit_required") or "jit_source_contract" in m:
        if source_contract(m.get("jit_source_identity", {})) != m.get("jit_source_contract"):
            raise ValueError("JIT source contract differs")
        if sdk is not None:
            # Constructor hashes inputs only: no cache directory, compilation,
            # runtime loading or GPU work. Reject stale bundles before a sweep.
            identity = Compiler(sdk, root / ".source-check-unused").identity
            if source_contract(identity) != m["jit_source_contract"]:
                changed = [key for key in ("kernel", "flags", "generator")
                           if identity[key] != m["jit_source_identity"][key]]
                raise ValueError("JIT checkout differs from dispatcher (" + ",".join(changed)
                                 + "); rebuild the small dispatcher")
    seen = set()
    for r in m["modules"]:
        if (
            r["key"] in seen
            or len(r["key"]) != 64
            or any(c not in "0123456789abcdef" for c in r["key"])
        ):
            raise ValueError("duplicate/invalid module key")
        seen.add(r["key"])
        expected = "modules/" + r["key"] + "/kernel.so"
        path = (root / expected).resolve(strict=True)
        if (
            r["path"] != expected
            or not path.is_relative_to(root)
            or sha(path) != r["sha256"]
        ):
            raise ValueError("module payload differs: " + r["key"])
        source = module_source(r)
        if (
            digest(dict(identity=r["identity"], parent=r["parent"], source=source))
            != r["key"]
        ):
            raise ValueError("module compiler identity differs")
    return m


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("bundle", type=Path)
    p.add_argument("--sdk", type=Path, help="also check the live JIT source contract, without compiling")
    a = p.parse_args()
    manifest = verify(a.bundle, sdk=a.sdk)
    print(
        f"KPACK_NATIVE_PACKAGE VERIFIED modules={len(manifest['modules'])} "
        f"execution_sha256={manifest['execution_sha256']} device_admission=PENDING"
    )
